scripts/ci/release-npm-next-tag.sh
scripts/ci/setup-npm.sh

Only trigger a npm release if the npm relevant packages changed. Docs and other configs are skipped

ci(release): Only trigger an npm release if packages changed

---

CONTRIBUTING.md

Make clearer that forks should create a branch and not work on the master branch directly.

docs: Updated Contribution Guide

---

.travis.yml
scripts/ci/release-npm-next-tag.sh

Create PR after version bump in RC Build

---

.travis.yml

WIP: Fixed travis.yml deploy condition

---

.travis.yml
scripts/ci/release-npm-next-tag.sh

WIP: Remove travis deploy condition

---

package.json
packages/charts/package.json
packages/fiori3/package.json
yarn.lock

chore(web-components): Update UI5 Web Components to v0.11.1

---

packages/main/__karma_snapshots__/AnalyticalTable.md
packages/main/src/components/AnalyticalTable/index.tsx

fix(AnalyticalTable): BusyIndicator works again

---

config/jestsetup.ts
packages/charts/src/components/BarChart/BarChart.test.tsx
packages/charts/src/components/BarChart/Placeholder.tsx
packages/charts/src/components/BarChart/__snapshots__/BarChart.test.tsx.snap
packages/charts/src/components/BarChart/demo.stories.tsx
packages/charts/src/components/BarChart/index.tsx
packages/charts/src/components/ColumnChart/ColumnChart.test.tsx
packages/charts/src/components/ColumnChart/__snapshots__/ColumnChart.test.tsx.snap
packages/charts/src/components/ColumnChart/demo.stories.tsx
packages/charts/src/components/ColumnChart/index.tsx
packages/charts/src/components/DonutChart/DonutChart.test.tsx
packages/charts/src/components/DonutChart/__snapshots__/DonutChart.test.tsx.snap
packages/charts/src/components/DonutChart/demo.stories.tsx
packages/charts/src/components/DonutChart/index.tsx
packages/charts/src/components/LineChart/LineChart.test.tsx
packages/charts/src/components/LineChart/__snapshots__/LineChart.test.tsx.snap
packages/charts/src/components/LineChart/demo.stories.tsx
packages/charts/src/components/LineChart/index.tsx
packages/charts/src/components/PieChart/PieChart.test.tsx
packages/charts/src/components/PieChart/__snapshots__/PieChart.test.tsx.snap
packages/charts/src/components/PieChart/demo.stories.tsx
packages/charts/src/components/PieChart/index.tsx
packages/charts/src/components/RadarChart/index.tsx
shared/tests/serializer/content-loader-serializer.js

Added snapshot tests for placeholders

fix(Charts): Show Loading Placeholder

---

packages/main/__karma_snapshots__/FilterBar.md
packages/main/src/components/FilterBar/demo.stories.tsx
packages/main/src/components/FilterBar/index.tsx
packages/main/src/components/FilterItem/FilterItem.jss.ts
packages/main/src/components/FilterItem/index.tsx

Removing unnecessary Rerenders

Refactor FilterItem

---

config/paths.js
package.json
packages/base/package.json
packages/charts/package.json
packages/charts/rollup.config.js
packages/charts/src/components/MicroBarChart/index.tsx
packages/charts/src/components/RadarChart/index.tsx
packages/charts/src/index.ts
packages/charts/src/lib/BarChart.ts
packages/charts/src/lib/ColumnChart.ts
packages/charts/src/lib/DonutChart.ts
packages/charts/src/lib/LineChart.ts
packages/charts/src/lib/MicroBarChart.ts
packages/charts/src/lib/PieChart.ts
packages/charts/src/lib/RadarChart.ts
packages/charts/src/lib/RadialChart.ts
packages/docs/.storybook/config.js
packages/main/package.json
scripts/rollup/bundles.js
scripts/rollup/packaging.js
scripts/rollup/results.json
shared/rollup/configFactory.js
yarn.lock

feat(Charts): Added per chart lib export

---

packages/main/__karma_snapshots__/FilterBar.md
packages/main/__karma_snapshots__/VariantManagement.md
packages/main/src/components/VariantManagement/VariantManagement.karma.tsx
packages/main/src/components/VariantManagement/demo.stories.tsx
packages/main/src/components/VariantManagement/index.tsx

fix(VariantManagement): initialSelectedKey prop is working as intended

---

packages/main/__karma_snapshots__/FilterBar.md
packages/main/src/components/FilterBar/FilterBar.karma.tsx
packages/main/src/components/FilterBar/demo.stories.tsx
packages/main/src/components/FilterItem/index.tsx
packages/main/src/enums/FilterType.ts

feat(FilterItem): Add MultiSelect option to FilterTypes

---

packages/main/src/interfaces/CommonProps.ts

fix: adding ref to CommonProps interface

---

packages/charts/src/util/populateData.ts

fix(charts): Repeats the color palette at more than twelve datasets

---

config/jest.config.js
config/karma.webpack.config.js
packages/charts/package.json
packages/charts/src/components/BarChart/index.tsx
packages/charts/src/components/ColumnChart/index.tsx
packages/charts/src/components/DonutChart/index.tsx
packages/charts/src/components/LineChart/index.tsx
packages/charts/src/components/PieChart/index.tsx
packages/charts/src/components/RadarChart/index.tsx
packages/charts/src/components/RadialChart/index.tsx
packages/charts/src/config.ts
packages/charts/src/internal/ChartLegend.ts
packages/charts/src/themes/Utils.ts
packages/charts/src/util/Utils.ts
packages/docs/.storybook/TableComponent.tsx
packages/docs/.storybook/config.js
packages/docs/.storybook/decorators/withStyleInfo.tsx
packages/docs/.storybook/webpack.config.js
packages/docs/Badges.tsx
packages/docs/Welcome.tsx
packages/main/src/components/AnalyticalCard/demo.stories.tsx
packages/main/src/components/MessageToast/demo.stories.tsx
scripts/rollup/bundles.js
scripts/rollup/results.json
shared/tests/mock/UI5WebComponent.js
tsconfig.json
yarn.lock

- Charts are now using UI5 CSS Variables for labels, legends, etc.
- Legend and Radial Chart are now using UI5 Web Components

feat(Charts): Use UI5 CSS Variables

---

README.md

docs(Configuration): Added Cozy/Compact Note

---

packages/main/src/components/Spinner/index.tsx

fix(Spinner): Accept style prop

---

packages/base/npm/index.esm.js
packages/charts/npm/index.esm.js
packages/main/npm/index.esm.js
scripts/rollup/build.js
scripts/rollup/bundles.js
scripts/rollup/packaging.js
scripts/rollup/results.json
shared/rollup/configFactory.js
tsconfig.json

Overhaul build setup:
- Generate typings in correct path
- Do not create a `dev` and a `prod` ES6 Bundle as minification has no affect.
Fixes #90

Overhaul Build Setup

---

packages/main/src/components/FilterBar/__snapshots__/FilterBar.test.tsx.snap
packages/main/src/components/VariantManagement/__snapshots__/VariantManagement.test.tsx.snap
packages/main/src/components/VariantManagement/index.tsx

fix(VariantManagement): disabled prop disables onClick events

---

package.json
yarn.lock

docs(storybook): Update to v5.2.0

---

packages/main/src/components/AnalyticalTable/columnHeader/ColumnHeaderModal.tsx
packages/main/src/components/AnalyticalTable/columnHeader/index.tsx
packages/main/src/components/AnalyticalTable/demo/demo.stories.tsx
packages/main/src/components/AnalyticalTable/index.tsx

feat(AnalyticalTable): add onSort callback to Table

---

packages/main/package.json
packages/main/src/components/AnalyticalTable/AnayticalTable.jss.ts
packages/main/src/components/AnalyticalTable/Resizer/index.tsx
packages/main/src/components/AnalyticalTable/__snapshots__/AnalyticalTable.test.tsx.snap
packages/main/src/components/AnalyticalTable/columnHeader/index.tsx
packages/main/src/components/AnalyticalTable/index.tsx
packages/main/src/components/AnalyticalTable/types/ColumnType.ts
yarn.lock

Closes #116 
Updated to react-table v7.0.0-beta.0

feat(AnalyticalTable): make columns resizable

---

packages/base/package.json

fix(base): Added missing react peer dependency

---

packages/main/src/components/Grid/Grid.stories.tsx
packages/main/src/components/Grid/Grid.test.tsx
packages/main/src/components/Grid/__snapshots__/Grid.test.tsx.snap
packages/main/src/components/Grid/index.tsx
shared/tests/utils.tsx

refactor(Grid): Replace withStyles HOC with forwardRef

---

packages/main/src/components/FilterBar/FilterBar.jss.ts

fix(FilterBar): Added scrolling and wrapping for small screens

---

packages/main/src/webComponents/StandardListItem/index.tsx

chore(StandardListItem): allow passing ReactNode to StandardListItem

---

packages/charts/src/components/BarChart/__snapshots__/BarChart.test.tsx.snap
packages/charts/src/components/ColumnChart/__snapshots__/ColumnChart.test.tsx.snap
packages/charts/src/components/DonutChart/__snapshots__/DonutChart.test.tsx.snap
packages/charts/src/components/LineChart/__snapshots__/LineChart.test.tsx.snap
packages/charts/src/components/PieChart/__snapshots__/PieChart.test.tsx.snap
packages/charts/src/interfaces/ChartBaseProps.ts
packages/charts/src/internal/useSizeMonitor.ts
packages/charts/src/internal/withChartContainer.tsx
packages/charts/src/util/ChartBaseDefaultProps.ts

fix(Charts): dynamic chart size

---

packages/main/src/components/SideNavigation/SideNavigation.test.tsx
packages/main/src/components/SideNavigation/__snapshots__/SideNavigation.test.tsx.snap
packages/main/src/components/SideNavigation/demo.stories.tsx
packages/main/src/components/SideNavigation/index.tsx
packages/main/src/components/SideNavigationListItem/index.tsx

fix(SideNavigation): fix tooltip support

---

packages/main/src/components/SideNavigation/index.tsx

fix(SideNavigation): Don't render zero if no footerItems present

---

packages/main/src/components/AnalyticalTable/hooks/useTableRowStyling.ts
packages/main/src/components/AnalyticalTable/index.tsx
packages/main/src/components/AnalyticalTable/virtualization/VirtualTableBody.tsx

fix(AnalyticalTable): fix table row selection

---

packages/main/src/components/AnalyticalTable/hooks/useTableScrollHandles.ts
packages/main/src/components/AnalyticalTable/index.tsx
packages/main/src/components/AnalyticalTable/virtualization/Cell.tsx
packages/main/src/components/AnalyticalTable/virtualization/VirtualTableBody.tsx
packages/main/src/enums/AnalyticalTableScrollMode.ts
packages/main/src/index.ts
packages/main/src/interfaces/AnalyticalTableDomRef.ts
packages/main/src/lib/AnalyticalTableScrollMode.ts

fix: add key to Cell component
feat: offer scrollTo and scrollToItem methods on table ref

feat(AnalyticalTable): offer scrollTo and scrollToItem methods on table ref

---

packages/main/src/components/AnalyticalTable/demo/demo.stories.tsx
packages/main/src/components/AnalyticalTable/hooks/useRowSelection.ts
packages/main/src/components/AnalyticalTable/hooks/useTableRowStyling.ts
packages/main/src/components/AnalyticalTable/index.tsx

What do you prefer, selectedRowKey(e.g. row_5) or selectedRowIndex(e.g. 5)?

feat(AnalyticalTable): control row selection by prop

---

packages/docs/Welcome.stories.mdx
packages/docs/styling/MyCustomElement.jsx
packages/docs/styling/MyCustomElement.tsx
packages/docs/styling/Styling.stories.mdx

docs(styling): Add guide on how to reuse styling

---

packages/main/src/components/AnalyticalTable/ColumnHeader/index.tsx
packages/main/src/components/AnalyticalTable/demo/demo.stories.tsx
packages/main/src/components/AnalyticalTable/index.tsx
packages/main/src/components/AnalyticalTable/types/ColumnType.ts

fix(AnalyticalTable): Handle disableGrouping in column level

---

README.md

docs(Readme): Add bundlephobia bundle sizes

---

packages/main/src/components/AnalyticalTable/demo/demo.stories.tsx
packages/main/src/components/AnalyticalTable/index.tsx

feat(AnalyticalTable): Added missing property to dependency array

---

config/jestsetup.ts
packages/base/package.json
packages/base/src/polyfill/Edge.ts
packages/base/src/polyfill/IE11.ts
packages/charts/src/internal/useSizeMonitor.ts
packages/main/package.json
packages/main/src/components/ObjectPage/demo.stories.tsx
packages/main/src/components/ObjectPage/index.tsx

enable scroll by dragging scrollbar
use ResizeObserver to get notified of layout updates of ObjectPage content to recalculate filler div height

fix(ObjectPage): enable scroll by dragging scrollbar

---

packages/main/src/components/AnalyticalTable/hooks/useTableRowStyling.ts

fix(AnalyticalTable): Enabled copying of text content inside of non-clickable rows.

---

packages/main/src/components/AnalyticalTable/ColumnHeader/Resizer.tsx
packages/main/src/components/AnalyticalTable/ColumnHeader/index.tsx
packages/main/src/components/AnalyticalTable/hooks/useTableRowStyling.ts
packages/main/src/components/AnalyticalTable/hooks/useWindowResize.ts

fix(AnalyticalTable): Fixed resizable columns and horizontal scrolling

---

packages/main/src/components/AnalyticalTable/AnalyticalTable.test.tsx
packages/main/src/components/AnalyticalTable/AnayticalTable.jss.ts
packages/main/src/components/AnalyticalTable/__snapshots__/AnalyticalTable.test.tsx.snap
packages/main/src/components/AnalyticalTable/demo/demo.stories.tsx
packages/main/src/components/AnalyticalTable/hooks/useTableRowStyling.ts
packages/main/src/components/AnalyticalTable/index.tsx
packages/main/src/components/AnalyticalTable/virtualization/VirtualTableBody.tsx
shared/tests/utils.tsx

Add prop `alternateRowColor` for improving table readability.

feat(AnalyticalTable): Add prop alternateRowColor

---

packages/main/src/components/AnalyticalTable/ColumnHeader/ColumnHeaderModal.tsx
packages/main/src/components/AnalyticalTable/ColumnHeader/index.tsx
packages/main/src/components/AnalyticalTable/__snapshots__/AnalyticalTable.test.tsx.snap

chore(AnalyticalTable): add tooltip to Table Column Header

---

packages/main/src/components/AnalyticalTable/ColumnHeader/index.tsx
packages/main/src/components/AnalyticalTable/__snapshots__/AnalyticalTable.test.tsx.snap
packages/main/src/components/AnalyticalTable/index.tsx
packages/main/src/components/AnalyticalTable/virtualization/VirtualTableBody.tsx
packages/main/src/components/AnalyticalTable/virtualization/VirtualTableRow.tsx

chore(AnalyticalTable): Add aria attributes

---

packages/main/src/components/AnalyticalTable/hooks/useWindowResize.ts
packages/main/src/components/AnalyticalTable/virtualization/VirtualTableBody.tsx

fix(AnalyticalTable): Adjust table content for hidden columns and if minWidth is set

---

packages/charts/src/index.ts
packages/charts/src/lib/BarChartPlaceholder.tsx
packages/charts/src/lib/ColumnChartPlaceholder.tsx
packages/charts/src/lib/LineChartPlaceholder.tsx
packages/charts/src/lib/PieChartPlaceholder.tsx
packages/main/src/index.ts
packages/main/src/lib/TablePlaceholder.ts

chore: Export Placeholder Loadings

---

packages/main/package.json
packages/main/src/components/AnalyticalTable/__snapshots__/AnalyticalTable.test.tsx.snap
packages/main/src/components/AnalyticalTable/index.tsx
packages/main/src/components/AnalyticalTable/tableReducer/reducer.ts
yarn.lock

Upgraded react-table to beta.20, removed setState, added reducer

feat(AnalyticalTable): Upgrade react-table to beta.20

---

.github/workflows/nodejs.yml
.travis.yml
scripts/ci/release-snapshot.sh

ci: Build npm snapshot with github actions

---

lerna.json

chore(release): Use fixed version instead of independent version

---

package.json
packages/docs/.storybook/addons.js
packages/docs/.storybook/presets.js
packages/main/package.json
packages/main/src/components/AnalyticalTable/hooks/useTableCellStyling.ts
packages/main/src/components/AnalyticalTable/hooks/useTableHeaderStyling.ts
packages/main/src/components/AnalyticalTable/hooks/useTableRowStyling.ts
packages/main/src/components/AnalyticalTable/hooks/useToggleRowExpand.ts
scripts/rollup/results.json
yarn.lock

BREAKING CHANGE: Update `react-table` to `v7.0.0-rc.15`

feat(AnalyticalTable): Update react-table to v7.0.0-rc.15

---

packages/main/src/components/SegmentedButton/index.tsx

fix(SegmentedButton): Adding null check before accessing html node

---

packages/main/src/components/AnalyticalTable/ColumnHeader/index.tsx
packages/main/src/components/AnalyticalTable/__snapshots__/AnalyticalTable.test.tsx.snap
packages/main/src/components/AnalyticalTable/index.tsx

fix(AnalyticalTable): fix initial resizing and horizontal overflow

---

packages/main/src/components/Loader/index.tsx

Was crashing due to inconsinstent hook calls

fix(Loader): Call usePassThroughHooks early return

---

.github/workflows/nodejs.yml
.github/workflows/npm-snapshot-release.yml

ci: Create NPM Snapshot Release Action

---

packages/main/src/components/AnalyticalTable/index.tsx
packages/main/src/components/AnalyticalTable/tableReducer/stateReducer.ts

fix(AnalyticalTable): re-enable setting isVisible property on column to show/hide columns

---

packages/main/src/components/ObjectPage/index.tsx

fix(ObjectPage): Don't wrap header content if image is an avatar

---

packages/charts/src/components/LineChart/demo.stories.tsx
packages/charts/src/config.ts

fix(charts): add some top padding on charts to prevent cut off labels

---

packages/main/src/components/ObjectPage/ObjectPage.jss.ts

fix(ObjectPage): Fix floating of custom header content

---

packages/main/src/components/ObjectPage/index.tsx

fix(ObjectPage): fix crash when unmounted ObjectPage tries to asynchronously set scrollbar height

---

packages/main/src/components/AnalyticalTable/hooks/useTableRowStyling.ts
packages/main/src/components/AnalyticalTable/virtualization/VirtualTableBody.tsx
packages/main/src/components/AnalyticalTable/virtualization/VirtualTableRow.tsx

fix(AnalyticalTable): fixed alternateRowColor sort bug

---

packages/main/src/components/Avatar/Avatar.jss.ts
packages/main/src/components/Avatar/Avatar.test.tsx
packages/main/src/components/Avatar/__snapshots__/Avatar.test.tsx.snap
packages/main/src/components/Avatar/index.tsx
packages/main/src/webComponents/Icon/demo.stories.tsx

fix(Avatar): Icon resize + remove deprecated onPress prop from Icon demo

---

packages/main/src/components/AnalyticalTable/__snapshots__/AnalyticalTable.test.tsx.snap
packages/main/src/components/AnalyticalTable/defaults/LoadingComponent/TablePlaceholder.tsx
packages/main/src/components/AnalyticalTable/index.tsx

fix(AnalyticalTable): Fix Loading Shimmer to take full table width

---

packages/base/src/styling/CssSizeVariables.ts
packages/main/src/components/AnalyticalCard/AnalyticalCard.jss.ts

fix(ThemingParameters): Add temporary quick fix for missing variables

---

docs/welcome/Welcome.stories.mdx

fix(Documentation): replace onPress with onClick

---

.storybook/preview.js
packages/main/src/components/ObjectPage/CollapsedAvatar.tsx
packages/main/src/components/ObjectPage/ObjectPage.jss.ts

fix(ObjectPage): RTL support for Header

---

packages/main/src/components/Grid/Grid.jss.ts

fix(Grid): Float items correctly in RTL mode

---

packages/base/src/hooks/useViewportRange.ts
packages/main/src/components/Grid/Grid.jss.ts
packages/main/src/components/Grid/Grid.stories.tsx
packages/main/src/components/Grid/index.tsx
packages/main/src/components/Loader/demo.stories.tsx
packages/main/src/components/Loader/index.tsx
packages/main/src/components/Spinner/index.tsx

fix(Loader/Spinner/Grid): Fix memory leaks by cleanup effects

---

packages/main/src/components/ObjectPage/ObjectPage.jss.ts
packages/main/src/components/ObjectPage/index.tsx

Limiting the ObjectPage Margin Bottom to the window height.
Closes #373

fix(ObjectPage): Prevent infinite grow

---

packages/main/src/components/ObjectPage/index.tsx

fix(ObjectPage): Fix event for changing selected section

---

packages/main/src/components/ObjectPage/ObjectPage.jss.ts
packages/main/src/components/ObjectPage/ObjectPageHeader.tsx
packages/main/src/components/ObjectPage/__snapshots__/ObjectPage.test.tsx.snap
packages/main/src/components/ObjectPage/index.tsx

fix(ObjectPage): Don't wrap title and subtitle

---

packages/charts/src/components/BarChart/BarChart.tsx
packages/charts/src/components/BarChart/BarRechart.stories.tsx
packages/charts/src/components/ColumnChart/ColumnChart.tsx
packages/charts/src/components/ColumnChart/ColumnRechart.stories.tsx
packages/charts/src/components/ComposedChart/ComposedChart.stories.tsx
packages/charts/src/components/ComposedChart/index.tsx
packages/charts/src/components/LineChart/LineChart.tsx
packages/charts/src/components/LineChart/LineRechart.stories.tsx
packages/charts/src/hooks/useChartMargin.ts
packages/charts/src/hooks/useResolveDataKeys.ts
packages/charts/src/interfaces/RechartBaseProps.ts
packages/charts/src/internal/CustomElements.tsx
packages/charts/src/resources/DemoProps.ts

fixes: check for secondary dimension, customized chart margin

fixes: secondary dimension, chart margin

---

packages/main/src/components/ThemeProvider/index.tsx

fix(RTL): add dir="rtl" to html tag when running in RTL

---

packages/main/src/interfaces/AnalyticalTableColumnDefinition.ts

fix(AnalyticalTableColumnDefinition): Add prop typing to ComponentType

---

packages/main/src/components/Form/Form.jss.ts
packages/main/src/components/Form/__snapshots__/Form.test.tsx.snap
packages/main/src/components/Form/index.tsx
packages/main/src/components/FormGroup/index.tsx
packages/main/src/components/FormItem/index.tsx
packages/main/src/components/Grid/__snapshots__/Grid.test.tsx.snap
packages/main/src/components/Grid/index.tsx
packages/main/src/enums/GridPosition.ts
packages/main/src/lib/GridPosition.ts

fix(Grid): fix incorrect layout when rendered before Device was initialized

---

packages/main/src/components/AnalyticalTable/hooks/useSingleRowStateSelection.ts
packages/main/src/components/AnalyticalTable/index.tsx

fix(AnalyticalTable): don't select row when an actionable element was clicked

---

packages/main/src/components/AnalyticalTable/hooks/useDynamicColumnWidths.ts
packages/main/src/components/AnalyticalTable/index.tsx
packages/main/src/components/AnalyticalTable/tableReducer/stateReducer.ts
packages/main/src/components/AnalyticalTable/util/deepCompare.ts

refactor(AnalyticalTable): Remoe unneccessary render cycle caused by async ResizeObserver init

---

packages/main/src/internal/withWebComponent.tsx
packages/main/src/webComponents/Table/Table.stories.tsx

fix(withWebComponent): If fragment is passed as slot, return the children of the corresponding fragment

---

packages/main/src/components/AnalyticalTable/hooks/useRowSelectionColumn.tsx
packages/main/src/components/AnalyticalTable/hooks/useSingleRowStateSelection.ts

fix(AnalyticalTable): fix multi-select checkbox

---

packages/charts/src/components/BarChart/BarChart.tsx
packages/charts/src/components/BarChart/BarRechart.stories.tsx
packages/charts/src/components/ColumnChart/ColumnChart.tsx
packages/charts/src/components/ComposedChart/ComposedChart.stories.tsx
packages/charts/src/components/ComposedChart/index.tsx
packages/charts/src/components/LineChart/LineChart.tsx
packages/charts/src/components/LineChart/LineRechart.stories.tsx
packages/charts/src/components/PieChart/PieChart.tsx
packages/charts/src/components/RadarChart/RadarChart.tsx
packages/charts/src/components/RadialChart/RadialChart.tsx
packages/charts/src/hooks/useLabelElements.ts
packages/charts/src/resources/DemoProps.ts

fix(displaying labels in bar chart): add data label hook

---

packages/main/src/components/Bar/index.tsx

fix(Bar): make slot props optional

---

packages/charts/package.json
packages/charts/src/hooks/useSizeMonitor.ts

fix(charts): Debounce resize handler

---

packages/main/src/components/AnalyticalTable/index.tsx

fix(AnalyticalTable): Debounce resize handler

---

packages/main/src/components/MessageBox/index.tsx

fix(MessageBox): Enable closing with esc key

---

packages/main/src/components/AnalyticalTable/AnayticalTable.jss.ts

fix(AnalyticalTable): prevent overflow y on parent container

---

packages/main/src/components/AnalyticalTable/AnalyticalTable.mdx
packages/main/src/components/AnalyticalTable/AnalyticalTable.stories.tsx
packages/main/src/components/AnalyticalTable/index.tsx

docs(AnalyticalTable): document all supported options

---

packages/main/src/webComponents/DurationPicker/DurationPicker.stories.tsx
packages/main/src/webComponents/DurationPicker/__snapshots__/DurationPicker.test.tsx.snap
packages/main/src/webComponents/DurationPicker/index.tsx

fix(DurationPicker): use correct value for defaultProp maxValue

---

packages/main/src/components/AnalyticalCard/demo.stories.tsx

fix(AnalyticalCard): fix line-chart in demo

---

packages/main/src/components/FilterBar/FilterBar.jss.ts
packages/main/src/components/FilterBar/FilterBar.test.tsx
packages/main/src/components/FilterBar/__snapshots__/FilterBar.test.tsx.snap
packages/main/src/components/FilterBar/index.tsx
packages/main/src/components/ObjectPage/CollapsedAvatar.tsx
packages/main/src/components/ObjectPage/ObjectPage.jss.ts
packages/main/src/components/ObjectPage/ObjectPage.test.tsx
packages/main/src/components/ObjectPage/ObjectPageAnchorBar.tsx
packages/main/src/components/ObjectPage/ObjectPageHeader.tsx
packages/main/src/components/ObjectPage/__snapshots__/ObjectPage.test.tsx.snap
packages/main/src/components/ObjectPage/index.tsx
packages/main/src/components/ObjectPage/useObserveHeights.ts
packages/main/src/components/Toolbar/OverflowPopover.tsx
packages/main/src/components/Toolbar/index.tsx

fixed in ObjectPage:
-  `image` in collapsed header now has a width of `3rem` to prevent resizing to 0px*0px dimension 
- The pin-header button is working as intended again
- When resizing the window, the image in the collapsed header is now always shown

feat(FilterBar/ObjectPage): add toolbar + minor ObjectPage fixes

---

packages/main/src/components/MessageBox/MessageBox.jss.ts
packages/main/src/components/MessageBox/MessageBox.test.tsx
packages/main/src/components/MessageBox/__snapshots__/MessageBox.test.tsx.snap
packages/main/src/components/MessageBox/demo.stories.tsx
packages/main/src/components/MessageBox/index.tsx

fix(MessageBox): allow custom action texts

---

packages/charts/src/components/BarChart/BarChart.tsx
packages/charts/src/components/ColumnChart/ColumnChart.tsx

fix(Bar-/Column Chart): displaying labels in stacked charts

---

packages/main/src/components/Form/Form.jss.ts
packages/main/src/components/Form/__snapshots__/Form.test.tsx.snap
packages/main/src/components/Form/index.tsx
packages/main/src/components/FormItem/index.tsx

feat(Form): add props to control labelSpan and columns for each size

---

packages/main/src/components/AnalyticalTable/AnayticalTable.jss.ts
packages/main/src/components/AnalyticalTable/__snapshots__/AnalyticalTable.test.tsx.snap
packages/main/src/components/AnalyticalTable/hooks/useStyling.ts

feat(AnalyticalTable): Horizontal scrollbar in fiori-design

---

packages/main/src/components/AnalyticalTable/hooks/useDynamicColumnWidths.ts
packages/main/src/components/AnalyticalTable/index.tsx

fix(AnalyticalTable): fix behavior of minWidth and add maxWidth support

---

packages/main/src/components/FilterBar/__snapshots__/FilterBar.test.tsx.snap
packages/main/src/components/FilterBar/demo.stories.tsx
packages/main/src/components/FilterBar/index.tsx

fix(FilterBar): replace fragments inside of toolbar, update story

---

.github/workflows/compressed-size.yml
.github/workflows/main.yml
.github/workflows/nodejs.yml
.github/workflows/npm-snapshot-release.yml

chore: update github workflows

---

packages/main/src/components/ObjectPage/ObjectPage.jss.ts
packages/main/src/components/ObjectPage/ObjectPageAnchorBar.tsx
packages/main/src/components/ObjectPage/ObjectPageAnchorButton.tsx
packages/main/src/components/ObjectPage/ObjectPageUtils.ts
packages/main/src/components/ObjectPage/demo.stories.tsx
packages/main/src/components/ObjectPage/index.tsx

fix(ObjectPage): support dynamically added sections

---

packages/main/src/components/AnalyticalTable/AnayticalTable.jss.ts
packages/main/src/components/AnalyticalTable/ColumnHeader/index.tsx
packages/main/src/components/AnalyticalTable/__snapshots__/AnalyticalTable.test.tsx.snap
packages/main/src/components/AnalyticalTable/types/ColumnType.ts

feat(AnalyticalTable): support resize on whole column

---

packages/main/src/components/AnalyticalTable/ColumnHeader/index.tsx
packages/main/src/components/AnalyticalTable/__snapshots__/AnalyticalTable.test.tsx.snap
packages/main/src/components/AnalyticalTable/index.tsx

fix(AnalyticalTable): prevent horizontal overflow if last column is resizable

---

packages/main/src/components/AnalyticalTable/hooks/useDynamicColumnWidths.ts

fix(AnalyticalTable): apply minWidth only if necessary

---

packages/main/src/components/AnalyticalTable/__snapshots__/AnalyticalTable.test.tsx.snap
packages/main/src/components/AnalyticalTable/hooks/useDragAndDrop.ts

fix(AnalyticalTable): fix wrong target index on column reordering

---

packages/main/src/webComponents/TimelineItem/__snapshots__/TimelineItem.test.tsx.snap
packages/main/src/webComponents/TimelineItem/index.tsx

fix(TimelineItem): use correct name

---

packages/main/src/components/MessageBox/MessageBox.jss.ts
packages/main/src/components/MessageBox/__snapshots__/MessageBox.test.tsx.snap
packages/main/src/components/MessageBox/index.tsx

fix(MessageBox): correctly align items in footer and fix header alignment in Safari

---

packages/main/src/components/AnalyticalTable/hooks/useSingleRowStateSelection.ts

fix(AnalyticalTable): prevent event bubbling of ui5 controls

---

packages/main/src/components/AnalyticalTable/index.tsx

fix(AnalyticalTable): don't crash if unsupported rowId is set as selectedRowIds key

---

packages/main/src/components/FilterBar/FilterBar.jss.ts
packages/main/src/components/FilterBar/FilterBarDialog.jss.ts
packages/main/src/components/FilterBar/__snapshots__/FilterBar.test.tsx.snap
packages/main/src/components/FilterBar/demo.stories.tsx
packages/main/src/components/FilterBar/index.tsx
packages/main/src/components/FilterBar/utils.tsx
packages/main/src/components/FilterGroupItem/FilterGroupItem.jss.ts
packages/main/src/components/FilterGroupItem/index.tsx

- add support for "Picker" components
- label doesn't display undefined if prop is not set
- fix `filterContainerWidth` prop in demo and in FilterBar
- filters in the dialog extend to available width

fix(FilterBar): support new web-components controls, fix layout and label

---

packages/main/src/components/AnalyticalTable/AnalyticalTable.test.tsx
packages/main/src/components/AnalyticalTable/__snapshots__/AnalyticalTable.test.tsx.snap
packages/main/src/components/AnalyticalTable/index.tsx

fix(AnalyticalTable): respect columnOrder prop

---

packages/main/src/components/AnalyticalTable/index.tsx

fix(AnalyticalTable): selectedRowIds can contain more than one digit per segment

---

.storybook/manager-head.html
.storybook/preview-head.html

fix(Storybook): use local default language for translatable texts

---

packages/charts/package.json
packages/charts/src/hooks/useObserveXAxisHeights.ts
packages/main/package.json
packages/main/src/components/AnalyticalTable/index.tsx
packages/main/src/components/ObjectPage/index.tsx
yarn.lock

chore: replace deprecated lodash per method packages with main lodash package

---

packages/main/src/components/AnalyticalTable/index.tsx
packages/main/src/components/FilterBar/index.tsx
packages/main/src/components/FilterItem/index.tsx
packages/main/src/components/VariantManagement/index.tsx
packages/main/src/interfaces/CommonProps.ts
packages/main/src/internal/withWebComponent.tsx

fix(CommonProps): add type definitions for HTML attributes

---

packages/base/src/hooks/usePassThroughHtmlProps.ts

+ Especially the [How to Contribute](https://github.com/SAP/ui5-webcomponents-react/blob/master/CONTRIBUTING.md#contribute-code) section 
---
Replace the use of `blacklist/whitelist` with `includelist/excludelist`, as per #702
In this case, include and exclude seems appropriate, because provided props are simply filtered and not rejected.

Replace use of 'blacklist/whitelist' with inclusive language

---

packages/main/package.json
yarn.lock

This will fix the issue with the AnalyticalTable in React.StrictMode

chore: update react-table & react-virtual

---

packages/main/src/components/AnalyticalTable/ColumnHeader/ColumnHeaderContainer.tsx
packages/main/src/components/AnalyticalTable/index.tsx

fix(AnalyticalTable): add missing keys

---

packages/main/src/webComponents/Tokenizer/Tokenizer.test.tsx
packages/main/src/webComponents/Tokenizer/__snapshots__/Tokenizer.test.tsx.snap

Transition from enzyme to react-testing-library

rewrite of tokenizer test

---

packages/main/src/webComponents/Token/Token.test.tsx
packages/main/src/webComponents/Token/__snapshots__/Token.test.tsx.snap

rewrite token test

---

packages/main/src/components/Page/Page.test.tsx
packages/main/src/components/Page/__snapshots__/Page.test.tsx.snap

rewrite page test

---

packages/main/src/components/Loader/Loader.test.tsx
packages/main/src/components/Loader/__snapshots__/Loader.test.tsx.snap

rewrite loader test

---

packages/main/src/components/Breadcrumbs/Breadcrumbs.test.tsx
packages/main/src/components/Breadcrumbs/__snapshots__/Breadcrumbs.test.tsx.snap

rewrite breadcrumbs test

---

packages/main/src/components/Text/Text.test.tsx
packages/main/src/components/Text/__snapshots__/Text.test.tsx.snap

rewrite text test

---

packages/main/src/components/AnalyticalTable/scrollbars/VerticalScrollbar.tsx

fix(AnalyticalTable): Prevent style warning when scrollbar is visible

---

packages/main/src/components/ObjectStatus/ObjectStatus.test.tsx
packages/main/src/components/ObjectStatus/__snapshots__/ObjectStatus.test.tsx.snap

rewrite ObjectStatus test

---

packages/base/package.json
packages/charts/package.json
packages/main/package.json

fix: update peer dependencies to support react 17

---

packages/main/src/components/ThemeProvider/ThemeProvider.test.tsx

test(ThemeProvider): rewrite test using react-testing-library

---

docs/2-MigrationGuide.stories.mdx
docs/3-Styling.stories.mdx
docs/styling/MyCustomElement.tsx
packages/main/src/components/ThemeProvider/ThemeProvider.test.tsx

docs: add name option to createUseStyles example

---

packages/main/src/webComponents/ProgressIndicator/ProgressIndicator.stories.mdx

docs(ProgressIndicator): enhance story

---

packages/main/src/webComponents/SideNavigation/SideNavigation.stories.mdx
packages/main/src/webComponents/SideNavigation/index.tsx

docs(SideNavigation): enhance story

---

packages/main/src/webComponents/Tree/Tree.stories.mdx

docs(Tree): enhance story

---

packages/main/src/webComponents/Toast/Toast.stories.mdx

docs(Toast): enhance story

---

packages/main/src/components/ActionSheet/ActionSheet.stories.mdx
packages/main/src/components/ActionSheet/index.tsx

docs(ActionSheet): enhance story, add JSDoc comments

---

packages/charts/src/components/MicroBarChart/MicroBarChart.test.tsx
packages/charts/src/components/MicroBarChart/__snapshots__/MicroBarChart.test.tsx.snap

rewrite of microBarChart-test

---

packages/main/src/i18n/messagebundle_en_GB.properties
packages/main/src/i18n/messagebundle_es_MX.properties

Translation Delivery

---

packages/main/src/components/DynamicPage/DynamicPage.stories.mdx
packages/main/src/components/DynamicPage/index.tsx

docs(DynamicPage): remove references to footer

---

packages/cra-template-seed/template/src/hooks/services/useTodos.js
packages/cra-template-seed/template/src/pages/Fallback/Fallback.js
packages/cra-template-seed/template/src/pages/Todo/Edit/TodoEdit.js
packages/cra-template-seed/template/src/pages/Todo/List/TodoListPaginatedItems.js

Refactoring of Hook Internal Logic

---

packages/charts/package.json
packages/charts/src/components/BarChart/BarChart.tsx
packages/charts/src/components/ColumnChart/ColumnChart.tsx
packages/charts/src/components/ComposedChart/index.tsx
yarn.lock

fix(charts): allow negative measures in stacked charts

---

packages/main/src/interfaces/CommonProps.ts
shared/stories/DocsCommonProps.ts

docs: remove non-essential common props from args table

---

.storybook/manager-head.html

docs(storybook): only add custom background-color to switch in args table

---

packages/main/src/components/Bar/Bar.jss.ts

fix(Bar): add border-radius to floating-footer

---

packages/main/src/components/AnalyticalCard/AnalyticalCard.test.tsx
packages/main/src/components/AnalyticalCard/__snapshots__/AnalyticalCard.test.tsx.snap
packages/main/src/components/AnalyticalCardHeader/AnalyticalCardHeader.jss.ts
packages/main/src/components/AnalyticalCardHeader/AnalyticalCardHeader.test.tsx
packages/main/src/components/AnalyticalCardHeader/__snapshots__/AnalyticalCardHeader.test.tsx.snap
packages/main/src/components/AnalyticalCardHeader/index.tsx

chore(AnalyticalCard): add tests, use correct CSSVar for bottom border, fix props docs

---

packages/main/src/components/DynamicPage/DynamicPage.jss.ts
packages/main/src/components/DynamicPageTitle/index.tsx

fix(DynamicPage): don't render unnecessary scrollbar & only show actions separator when needed

---

packages/main/src/components/AnalyticalTable/AnalyticalTable.stories.mdx
packages/main/src/components/AnalyticalTable/AnayticalTable.jss.ts
packages/main/src/components/AnalyticalTable/__snapshots__/AnalyticalTable.test.tsx.snap
packages/main/src/components/AnalyticalTable/defaults/Column/Expandable.tsx
packages/main/src/components/AnalyticalTable/hooks/useDragAndDrop.ts
packages/main/src/components/AnalyticalTable/hooks/useRowHighlight.tsx
packages/main/src/components/AnalyticalTable/hooks/useRowNavigationIndicator.tsx
packages/main/src/components/AnalyticalTable/hooks/useRowSelectionColumn.tsx

fix(AnalyticalTable): prevent crashes and unintended behavior in IE11

---

packages/main/src/components/AnalyticalTable/AnalyticalTable.test.tsx
packages/main/src/components/AnalyticalTable/ColumnHeader/ColumnHeaderContainer.tsx
packages/main/src/components/AnalyticalTable/__snapshots__/AnalyticalTable.test.tsx.snap

feat(AnalyticalTable): improve accessibility

---

packages/base/src/Device/index.ts

fix(Device): use named export to prevent typescript error

---

packages/charts/src/components/DonutChart/DonutChart.stories.mdx

docs(DonutChart): fix story args

---

packages/main/src/internal/__snapshots__/withWebComponent.test.tsx.snap
packages/main/src/internal/withWebComponent.test.tsx
packages/main/src/internal/withWebComponent.tsx

fix(Web Components): allow conditional rendering in slots

---

packages/main/src/components/AnalyticalTable/AnayticalTable.jss.ts
packages/main/src/components/AnalyticalTable/__snapshots__/AnalyticalTable.test.tsx.snap
packages/main/src/components/AnalyticalTable/index.tsx
shared/tests/index.tsx

fix(AnalyticalTable): remove unnecessary borders in column headers

---

packages/main/src/webComponents/ShellBar/ShellBar.stories.mdx
packages/main/src/webComponents/ShellBarItem/index.tsx

docs(ShellBar): add description for targetRef of ShellBarItem

---

packages/base/src/styling/CssSizeVariables.ts
packages/main/src/components/FormItem/index.tsx

fix(Form): position all labels with the same spacing

---

packages/base/src/styling/CssSizeVariables.ts
packages/main/src/components/DynamicPage/__snapshots__/DynamicPage.test.tsx.snap
packages/main/src/components/Form/__snapshots__/Form.test.tsx.snap
packages/main/src/components/Form/index.tsx
packages/main/src/components/FormGroup/index.tsx
packages/main/src/components/FormItem/index.tsx

BREAKING CHANGE: __`FormGroup`__: `title` prop is now required.

fix(Form): Adjust spacing and alignment to comply with fiori guidelines

---

packages/main/src/components/ObjectPage/index.tsx

fix(ObjectPage): prevent crash on re-mounting the component

---

packages/main/src/components/MessageBox/MessageBox.stories.mdx

docs(MessageBox): improve docs for custom action handling

---

packages/cra-template-seed/template/src/index.js

fix(cra-template-seed): add InputElementsFormSupport import

---

packages/main/src/components/MessageBox/index.tsx

fix(MessageBox): Allow duplicate action names

---

packages/main/src/components/Toolbar/OverflowPopover.tsx

fix(Toolbar): Prevent event propagation of the overflow button

---

packages/main/src/components/AnalyticalTable/AnalyticalTable.test.tsx
packages/main/src/components/AnalyticalTable/__snapshots__/AnalyticalTable.test.tsx.snap

test(AnalyticalTable): add test for custom cell and header

---

README.md
docs/1-Welcome.stories.mdx
packages/cra-template-seed/README.md

docs(cra-template-seed): use start instead of mock

---

config/jest.config.js
docs/4-TestSetup.stories.mdx
package.json
packages/cra-template-seed/template.json
packages/cra-template-seed/template/.vscode/launch.json
packages/cra-template/template.json
yarn.lock

This additional environment is no longer needed.

test: remove jsdom-sixteen-environment as jest 26 comes with jsdom 16

---

packages/charts/src/components/BarChart/BarChart.stories.mdx
packages/charts/src/components/BarChart/BarChart.tsx
packages/charts/src/components/ColumnChart/ColumnChart.stories.mdx
packages/charts/src/components/ColumnChart/ColumnChart.tsx
packages/charts/src/components/ComposedChart/ComposedChart.stories.mdx
packages/charts/src/components/ComposedChart/index.tsx
packages/charts/src/components/DonutChart/DonutChart.stories.mdx
packages/charts/src/components/LineChart/LineChart.stories.mdx
packages/charts/src/components/LineChart/LineChart.tsx
packages/charts/src/components/MicroBarChart/MicroBarChart.stories.mdx
packages/charts/src/components/PieChart/PieChart.stories.mdx
packages/charts/src/components/PieChart/PieChart.tsx
packages/charts/src/components/RadarChart/RadarChart.stories.mdx
packages/charts/src/components/RadarChart/RadarChart.tsx
packages/charts/src/components/RadialChart/RadialChart.stories.mdx
packages/charts/src/components/RadialChart/RadialChart.tsx
packages/charts/src/components/ScatterChart/ScatterChart.stories.mdx
packages/charts/src/components/ScatterChart/ScatterChart.tsx
packages/charts/src/hooks/useLegendItemClick.ts
packages/charts/src/hooks/useOnClickInternal.ts
packages/charts/src/interfaces/IChartBaseProps.ts

feat(Charts): Add onClick event which is fired when clicked anywhere inside the chart container

---

README.md
docs/1-Welcome.stories.mdx
packages/main/src/interfaces/Ui5DatePickerDomRef.ts
packages/main/src/interfaces/Ui5PickerDomRef.ts

docs: add guide on how to use public interfaces to "Getting Started"

---

packages/main/src/components/AnalyticalTable/AnayticalTable.jss.ts
packages/main/src/components/AnalyticalTable/TableBody/RowSubComponent.tsx
packages/main/src/components/AnalyticalTable/TableBody/VirtualTableBody.tsx
packages/main/src/components/AnalyticalTable/__snapshots__/AnalyticalTable.test.tsx.snap
packages/main/src/components/ObjectPageSubSection/index.tsx

fix(AnalyticalTable): fix focus and keyboard navigation for cells and subcomponents

---

packages/main/src/components/Form/index.tsx
packages/main/src/components/FormItem/index.tsx

fix(Form): prevent crash when a single item within an array is passed as child

---

packages/cra-template-seed/template.json

The seed husky configuration was incorrect, I adjusted it.

fix(cra-template-seed): fix husky pre push hook

---

.reuse/dep5
package.json
packages/base/src/dist/Utils.ts
packages/base/src/index.ts
packages/base/src/utils/debounce.test.ts
packages/base/src/utils/debounce.ts
packages/charts/package.json
packages/charts/src/hooks/useObserveXAxisHeights.ts
packages/main/package.json
packages/main/src/components/AnalyticalTable/index.tsx
packages/main/src/components/ObjectPage/index.tsx
yarn.lock

Copied from https://github.com/jashkenas/underscore/blob/master/modules/debounce.js

chore: replace lodash/debounce with custom util

---

docs/1-Welcome.stories.mdx
yarn.lock

docs: mention community templates

---

packages/main/src/components/AnalyticalTable/TableBody/VirtualTableBody.tsx

feat(AnalyticalTable): allow inline styles for rows in custom hooks

---

.storybook/preview-head.html
packages/main/src/components/ResponsiveGridLayout/ResponsiveGridLayout.jss.ts
packages/main/src/components/ResponsiveGridLayout/ResponsiveGridLayout.stories.mdx
packages/main/src/components/ResponsiveGridLayout/ResponsiveGridLayout.test.tsx
packages/main/src/components/ResponsiveGridLayout/__snapshots__/ResponsiveGridLayout.test.tsx.snap
packages/main/src/components/ResponsiveGridLayout/index.tsx
packages/main/src/dist/ResponsiveGridLayout.ts
packages/main/src/index.ts

feat(ResponsiveGridLayout): initial component implementation

---

packages/main/src/components/AnalyticalTable/TableBody/RowSubComponent.tsx
packages/main/src/components/AnalyticalTable/__snapshots__/AnalyticalTable.test.tsx.snap
packages/main/src/components/FilterBar/index.tsx

fix(FilterBar & AnalyticalTable): display subcomponents and filter items correctly in Safari

---

packages/main/src/components/DynamicPage/index.tsx
packages/main/src/components/DynamicPageTitle/index.tsx
yarn.lock

fix(DynamicPage): only render necessary elements

---

packages/main/src/webComponents/Table/Table.stories.mdx

docs(Table): add example for growing mode

---

package.json
yarn.lock

chore(deps): bump storybook deps from 6.3.3 to 6.3.4

---

packages/main/src/components/ObjectPage/ObjectPage.jss.ts
packages/main/src/components/ObjectPage/__snapshots__/ObjectPage.test.tsx.snap
packages/main/src/components/ObjectPage/index.tsx

fix(ObjectPage): make sure TabBar is always on top of content

---

packages/main/src/components/ObjectPage/ObjectPageAnchorTab.ts

fix(TabContainer): apply ObjectPage styles only in ObjectPage

---

package.json
yarn.lock

chore(deps): update storybook to 6.3.5

---

packages/charts/src/components/RadialChart/RadialChart.tsx

Closes: https://github.com/SAP/ui5-webcomponents-react/issues/1874

feat(RadialChart): add noAnimation prop

---

docs/3-KnowledgeBase.stories.mdx

docs(KnowledgeBase): extend Test Setup with setupTests.js

---

.github/workflows/dependabot-automerge.yml

chore: enable auto merge for dependabot PR's

---

docs/3-KnowledgeBase.stories.mdx
packages/cra-template-seed/template/src/setupTests.js
packages/cra-template/template/src/setupTests.js

fix: improve setupMatchMedia for cra-templates and docs

---

packages/main/src/components/AnalyticalTable/hooks/useSingleRowStateSelection.ts
packages/main/src/components/FilterBar/FilterBar.stories.mdx
packages/main/src/components/FilterBar/utils.tsx

chore: add missing/changed tag-names to `FilterBar` and `AnalyticalTable`

---

packages/main/src/components/ObjectPage/ObjectPage.stories.mdx

docs(ObjectPage): add DynamicPageHeader and DynamicPageTitle as subcomponents

---

packages/main/src/components/AnalyticalTable/hooks/useRowSelectionColumn.tsx

feat(AnalyticalTable): add indeterminate state to select-all checkbox

---

packages/main/src/components/AnalyticalTable/defaults/Column/Expandable.tsx
packages/main/src/components/AnalyticalTable/demo/generateData.ts

Fixes indentation of root level tree items and rtl
fixes #1807

fix(AnalyticalTable): correctly indent root level tree row

---

docs/2-MigrationGuide.stories.mdx
package.json
yarn.lock

chore(deps): update storybook to 6.3.6

---

CHANGELOG.md
packages/main/src/components/FilterBar/FilterBar.test.tsx
packages/main/src/components/FilterBar/FilterDialog.tsx
packages/main/src/components/FilterBar/index.tsx
packages/main/src/components/FilterBar/utils.tsx

fix(FilterBar): pass refs of FilterGroupItems children to rendered component

---

packages/main/src/components/DynamicPageTitle/index.tsx
packages/main/src/components/ObjectPage/ObjectPage.stories.mdx
packages/main/src/components/ObjectPage/__snapshots__/ObjectPage.test.tsx.snap
yarn.lock

fix(DynamicPageTitle): only render actions toolbar if necessary

---

packages/main/src/components/AnalyticalTable/ColumnHeader/ColumnHeaderModal.tsx
packages/main/src/components/AnalyticalTable/ColumnHeader/index.tsx
packages/main/src/components/AnalyticalTable/__snapshots__/AnalyticalTable.test.tsx.snap
packages/main/src/components/AnalyticalTable/hooks/useDynamicColumnWidths.ts
packages/main/src/components/AnalyticalTable/hooks/useKeyboardNavigation.ts
packages/main/src/components/AnalyticalTable/hooks/useRowSelectionColumn.tsx
packages/main/src/components/AnalyticalTable/index.tsx

fix(AnalyticalTable): don't throw errors on empty table

---

docs/4-Internationalization.stories.mdx

docs(i18n): mention that default language should be fetched as well

---

packages/base/codemods/renamePropsV18.js
packages/charts/src/components/BulletChart/BulletChart.stories.mdx
packages/charts/src/components/BulletChart/BulletChart.test.tsx
packages/charts/src/components/BulletChart/BulletChart.tsx
packages/charts/src/components/BulletChart/ComparisonLine.tsx
packages/charts/src/components/BulletChart/Placeholder.tsx
packages/charts/src/components/BulletChart/__snapshots__/BulletChart.test.tsx.snap
packages/charts/src/components/ComposedChart/ComposedChart.stories.mdx
packages/charts/src/dist/BulletChart.ts
packages/charts/src/dist/BulletChartPlaceholder.ts
packages/charts/src/dist/Utils.ts
packages/charts/src/index.ts
packages/charts/src/internal/ChartContainer.tsx
packages/charts/src/internal/Utils.ts
packages/charts/src/internal/XAxisTicks.tsx
packages/charts/src/internal/YAxisTicks.tsx
packages/charts/src/resources/DemoProps.ts
shared/tests/chartUtils.tsx

Support chart type: Bullet Chart
Closes:  https://github.com/SAP/ui5-webcomponents-react/issues/1099

feat(BulletChart): create new type of chart 

---

packages/charts/package.json
yarn.lock

Reverts SAP/ui5-webcomponents-react#1961

Revert "chore(deps): bump recharts from 2.0.10 to 2.1.0"

---

packages/charts/src/internal/ChartDataLabel.tsx

fix(ChartDataLabels): coloring of data labels

---

packages/main/src/components/ObjectPage/ObjectPageAnchorButton.tsx

fix(ObjectPage): respect scoping suffix for custom anchor tab

---

packages/main/src/components/MessageBox/MessageBox.test.tsx
packages/main/src/components/MessageBox/__snapshots__/MessageBox.test.tsx.snap
packages/main/src/components/MessageBox/index.tsx

fix(MessageBox): actions receive unique ids

---

packages/main/src/components/ObjectPage/ObjectPageUtils.ts
packages/main/src/components/ObjectPage/index.tsx

fix(ObjectPage): programatically remove sections without crashing

---

docs/5-Public-Utils.stories.mdx
packages/base/src/dist/hooks.ts
packages/base/src/hooks/useResponsiveContentPadding.ts
packages/main/src/components/DynamicPage/index.tsx
packages/main/src/components/ObjectPage/index.tsx
packages/main/src/components/Toolbar/index.tsx

This PR adds styling hook to set dynamic padding widths to components.
It also adds `cancelAnimationFrame` wherever `requestAnimationFrame` was used.

feat: export `useResponsiveContentPadding` hook in base package

---

packages/main/src/components/ObjectPage/ObjectPageAnchorTab.ts

chore: add js extension to lit-html ifDefined directive

---

packages/main/src/components/DynamicPageTitle/DynamicPageTitle.jss.ts

This PR will break up words and add a hyphen at appropriate hyphenation points for `heading` and `subheading`

feat(DynamicPageTitle): if not enough space is available break words at hyphenation points

---

.storybook/main.cjs
.storybook/preview.js
package.json
yarn.lock

chore(deps): update storybook to 6.4.0

---

packages/main/src/components/Toolbar/OverflowPopover.tsx
packages/main/src/components/Toolbar/Toolbar.test.tsx
packages/main/src/components/Toolbar/index.tsx

This PR adds the `onOverflowChange` callback which is fired every time, the content of the overflow popover changes.

feat(Toolbar): add `onOverflowChange` callback/prop

---

packages/main/src/components/Toolbar/OverflowPopover.tsx
packages/main/src/components/Toolbar/Toolbar.jss.ts
packages/main/src/components/Toolbar/__snapshots__/Toolbar.test.tsx.snap

fix(Toolbar): fix Button alignment in overflow popover (spec compliance)

---

packages/main/src/components/SelectDialog/__snapshots__/SelectDialog.test.tsx.snap
packages/main/src/components/SelectDialog/index.tsx

UX guidelines are outdated, the inforbar should be sticky.
Closes #2492

feat(SelectDialog): make infobar sticky

---

packages/charts/src/hooks/useObserveXAxisHeights.ts
packages/main/src/components/AnalyticalTable/index.tsx
packages/main/src/components/DynamicPage/index.tsx
packages/main/src/components/DynamicPageTitle/index.tsx
packages/main/src/components/FilterBar/index.tsx
packages/main/src/components/Toolbar/index.tsx

fix: cancel debounced functions when component unmounts

---

packages/main/scripts/create-web-components-wrapper.mjs
packages/main/src/webComponents/FlexibleColumnLayout/index.tsx
packages/main/src/webComponents/Link/index.tsx
packages/main/src/webComponents/ShellBar/index.tsx
scripts/web-component-wrappers/utils.js

fix(types): remove object properties from declarative prop types

---

packages/main/src/i18n/messagebundle_pt.properties

fix(i18n): improve translation of cancel and clear

---

packages/main/src/components/ActionSheet/index.tsx
packages/main/src/components/AnalyticalTable/ColumnHeader/ColumnHeaderModal.tsx
packages/main/src/components/DynamicPageAnchorBar/index.tsx
packages/main/src/components/FormItem/index.tsx
packages/main/src/components/ObjectPage/index.tsx
packages/main/src/components/ObjectPageSection/index.tsx
packages/main/src/components/SelectDialog/index.tsx
packages/main/src/components/VariantManagement/ManageViewsDialog.tsx
packages/main/src/internal/addCustomCSSWithScoping.ts
scripts/web-component-wrappers/utils.js

fix: apply custom styles to scoped ui5 web components

---

packages/main/src/components/Toolbar/OverflowPopover.tsx
packages/main/src/components/Toolbar/Toolbar.test.tsx
packages/main/src/components/Toolbar/__snapshots__/Toolbar.test.tsx.snap
packages/main/src/components/Toolbar/index.tsx

fix(Toolbar): show correct value for `aria-expanded`

---

packages/base/src/hooks/useResponsiveContentPadding.ts

fix(useResponsiveContentPadding): calculate paddings based on border box

---

packages/main/src/components/MessageView/MessageView.stories.mdx
packages/main/src/components/MessageView/MessageView.test.tsx
packages/main/src/components/MessageView/__snapshots__/MessageView.test.tsx.snap
packages/main/src/components/MessageView/index.tsx
packages/main/src/i18n/messagebundle.properties

fix(MessageView): fix scroll behaviour and add no data handling

---

packages/main/src/internal/I18nProvider.tsx

fix(i18nProvider): make sure I18nContext is always available

---

yarn.lock

chore: update vulnerable dev dependencies

---

packages/cra-template-seed/template/src/locales/pt/translation.json

fix(cra-template-seed): correct Portugues translations

---

packages/main/src/components/ActionSheet/ActionSheet.jss.ts
packages/main/src/components/ActionSheet/ActionSheet.stories.mdx
packages/main/src/components/ActionSheet/index.tsx

fix(ActionSheet): always align button content to start

---

packages/main/src/components/DynamicPage/DynamicPage.jss.ts
packages/main/src/components/DynamicPage/__snapshots__/DynamicPage.test.tsx.snap
packages/main/src/components/DynamicPage/index.tsx
packages/main/src/components/DynamicPageAnchorBar/index.tsx
packages/main/src/components/DynamicPageTitle/DynamicPageTitle.jss.ts
packages/main/src/components/DynamicPageTitle/index.tsx
packages/main/src/components/ObjectPage/ObjectPage.jss.ts
packages/main/src/components/ObjectPage/__snapshots__/ObjectPage.test.tsx.snap
packages/main/src/components/ObjectPage/index.tsx

fix(DynamicPage/ObjectPage): implement Horizon Theme for Title and Anchor Buttons

---

packages/main/src/components/AnalyticalTable/AnalyticalTable.stories.mdx
packages/main/src/components/AnalyticalTable/AnalyticalTable.test.tsx
packages/main/src/components/AnalyticalTable/__snapshots__/AnalyticalTable.test.tsx.snap
packages/main/src/components/AnalyticalTable/hooks/useA11y.ts
packages/main/src/components/AnalyticalTable/pluginHooks/useRowDisableSelection.tsx

fix(AnalyticalTable - useRowDisableSelection): correct a11y attributes for disabled rows

---

packages/cra-template-seed/template/src/components/Form/Input/Input.js
packages/cra-template-seed/template/src/components/Form/TextArea/TextArea.js

fix(cra-template-seed): improve formik bindings

---

packages/main/src/components/Toolbar/Toolbar.jss.ts
packages/main/src/components/Toolbar/Toolbar.stories.mdx

fix(Toolbar): add margin for first child & fix rtl margins

---

packages/main/src/components/MessageBox/__snapshots__/MessageBox.test.tsx.snap
packages/main/src/components/MessageBox/index.tsx

fix(MessageBox): avoid duplicate aria announcement

---

packages/main/src/components/DynamicPage/__snapshots__/DynamicPage.test.tsx.snap
packages/main/src/components/Form/Form.stories.mdx
packages/main/src/components/Form/__snapshots__/Form.test.tsx.snap
packages/main/src/components/FormItem/index.tsx

fix(Form): fix alignment of last group row

---

packages/main/src/components/AnalyticalTable/AnalyticalTable.stories.mdx
packages/main/src/components/AnalyticalTable/AnalyticalTable.test.tsx
packages/main/src/components/AnalyticalTable/ColumnHeader/index.tsx
packages/main/src/components/AnalyticalTable/__snapshots__/AnalyticalTable.test.tsx.snap

fix(AnalyticalTable): announce column header popover with screen readers

---

docs/1-Welcome.stories.mdx
docs/Styling.stories.mdx
tsconfig.json

docs: fix storybook build

---

packages/main/src/components/ObjectStatus/ObjectStatus.jss.ts

fix(ObjectStatus): correct icon padding in RTL

---

packages/main/src/components/ActionSheet/ActionSheet.jss.ts
packages/main/src/components/ActionSheet/index.tsx
packages/main/src/themes/CustomVariables.ts
packages/main/src/themes/base.ts
packages/main/src/themes/sap_belize.ts
packages/main/src/themes/sap_belize_hcb.ts
packages/main/src/themes/sap_belize_hcw.ts
packages/main/src/themes/sap_fiori_3.ts
packages/main/src/themes/sap_fiori_3_dark.ts
packages/main/src/themes/sap_fiori_3_hcb.ts
packages/main/src/themes/sap_fiori_3_hcw.ts
packages/main/src/themes/sap_horizon.ts
packages/main/src/themes/sap_horizon_dark.ts
packages/main/src/themes/sap_horizon_hcb.ts
packages/main/src/themes/sap_horizon_hcw.ts

Corrected the Dialog padding for Fiori and Horizon theme and updated style for Horizon.

fix(ActionSheet): update to latest design specs for Quartz and Horizon

---

packages/main/src/components/AnalyticalTable/AnalyticalTable.stories.mdx

docs(AnalyticalTable): describe how to allow manual sorting, grouping and filtering

---

packages/main/src/components/AnalyticalTable/ColumnHeader/ColumnHeaderContainer.tsx
packages/main/src/components/AnalyticalTable/ColumnHeader/ColumnHeaderModal.tsx
packages/main/src/components/AnalyticalTable/ColumnHeader/index.tsx
packages/main/src/components/AnalyticalTable/__snapshots__/AnalyticalTable.test.tsx.snap
packages/main/src/components/AnalyticalTable/defaults/FilterComponent/index.tsx
packages/main/src/components/AnalyticalTable/index.tsx

fix(AnalyticalTable): support whitespace input in filter, close column popover on keystroke selection

---

packages/main/src/components/FilterBar/FilterDialog.tsx

fix(FilterBar): use emphasized design for "Save" if "Go" is not set

---

packages/base/src/hooks/index.ts
packages/base/src/hooks/useCurrentTheme.ts
packages/main/src/components/Splitter/index.tsx
packages/main/src/themes/CustomVariables.ts
packages/main/src/themes/base.ts
packages/main/src/themes/sap_belize.ts
packages/main/src/themes/sap_fiori_3.ts
packages/main/src/themes/sap_fiori_3_dark.ts
packages/main/src/themes/sap_fiori_3_hcb.ts
packages/main/src/themes/sap_fiori_3_hcw.ts
packages/main/src/themes/sap_horizon.ts
packages/main/src/themes/sap_horizon_dark.ts
packages/main/src/themes/sap_horizon_hcb.ts
packages/main/src/themes/sap_horizon_hcw.ts

fix(SplitterLayout): adjust design to comply with guidelines

---

packages/base/src/hooks/useSyncRef.ts

fix(useSyncRef): add useCallback to avoid unnecessary rerenders

---

packages/main/src/components/VariantManagement/ManageViewsDialog.tsx
packages/main/src/i18n/messagebundle.properties

fix(VariantManagement): translate "Manage Views" heading

---

packages/main/src/components/AnalyticalTable/pluginHooks/useOnColumnResize.ts

fix(AnalyticalTable - useOnColumnResize): don't crash when more than 6 rows are rendered

---

packages/base/src/hooks/useIsRTL.ts
packages/main/src/components/Splitter/index.tsx

fix(SplitterLayout): correctly detect runtime change of `dir` on component

---

packages/main/src/components/DynamicPage/index.tsx

docs(DynamicPage): add footer note

---

packages/main/src/components/VariantManagement/index.tsx

fix(VariantManagement): always display "Cancel" button in transparent design

---

packages/main/src/components/DynamicPage/DynamicPage.stories.mdx

docs(DynamicPage): outline how to prevent bubbling with variants

---

.storybook/preview.js
.storybook/utils.ts

This PR also changes the default theme to Horizon.

docs(Storybook): use theme names for themes switch

---

README.md

docs: update support title to adhere guidelines

---

docs/Portals.stories.mdx
packages/main/src/components/ActionSheet/index.tsx
packages/main/src/components/AnalyticalTable/index.tsx
packages/main/src/components/FilterBar/index.tsx
packages/main/src/components/Toolbar/index.tsx
packages/main/src/components/VariantManagement/index.tsx

docs: create knowledge base entry covering portals

---

packages/main/src/components/AnalyticalTable/hooks/useKeyboardNavigation.ts

fix(AnalyticalTable): scroll horizontally if focused cell is only partially visible

---

packages/main/src/components/AnalyticalTable/hooks/useRowSelectionColumn.tsx

fix(AnalyticalTable): fix select-all behavior in React18 Strict Mode

---

packages/main/src/components/AnalyticalTable/index.tsx

fix(AnalyticalTable): reduce debounce wait time of height and width observers

---

packages/main/src/components/ObjectPage/ObjectPage.stories.mdx
packages/main/src/components/ObjectPage/__snapshots__/ObjectPage.test.tsx.snap
packages/main/src/components/ObjectPageSubSection/__snapshots__/ObjectPageSubSection.test.tsx.snap
packages/main/src/components/ObjectPageSubSection/index.tsx

feat(ObjectPageSubSection): introduce `actions` prop

---

packages/main/src/components/AnalyticalTable/hooks/useKeyboardNavigation.ts

fix(AnalyticalTable): fix keyboard navigation on columns/data change

---

packages/main/src/components/AnalyticalTable/AnalyticalTable.cy.tsx
packages/main/src/components/AnalyticalTable/index.tsx

docs(AnalyticalTable): `rowHeight` & `headerRowHeight` docs

---

packages/charts/package.json
packages/charts/src/interfaces/ICartesianChartConfig.ts
packages/charts/src/internal/XAxisTicks.tsx
packages/charts/src/internal/YAxisTicks.tsx
packages/main/package.json
yarn.lock

fix(charts): allow formatting y/x-axis ticks w/o changing measure formatter

---

packages/main/src/components/Modals/Modals.test.tsx
packages/main/src/components/Modals/ModalsProvider.tsx
packages/main/src/components/Modals/index.tsx
packages/main/src/interfaces/CommonProps.ts
packages/main/src/internal/ModalsContext.ts

This PR also refactors the Modal class to generally improve tsc support.

fix(Modals - TypeScript): allow typing the container element

---

packages/main/src/components/AnalyticalTable/AnalyticalTable.stories.mdx

docs(AnalyticalTable): outline how to distinguish between click and select on selection-cell

---

packages/main/src/webComponents/Tree/Tree.stories.mdx

docs(Tree): improve docs for TreeItemCustom

---

packages/main/src/components/Grid/index.tsx

fix(Grid): fix React key error

---

.eslintrc.yml
.github/workflows/main.yml
package.json
yarn.lock

- remove unused storybook eslint plugin
- disable some rules

ci(eslint): fix OOM error

---

packages/main/package.json
yarn.lock

fix: restrict base package dependency to be on same minor version as main package

---

packages/main/src/components/ActionSheet/ActionSheet.stories.mdx
packages/main/src/webComponents/Menu/Menu.stories.mdx
packages/main/src/webComponents/Popover/Popover.stories.mdx
packages/main/src/webComponents/ResponsivePopover/ResponsivePopover.stories.mdx

docs: explain how to open popovers by reference

---

packages/charts/src/components/LineChart/LineChart.stories.mdx
packages/charts/src/components/LineChart/LineChart.tsx

feat(LineChart): fully allow customizing the internal `Line` component

---

.storybook/preview.tsx

Workaround according to https://github.com/storybookjs/storybook/issues/21456#issuecomment-1458268788

docs: fix code preview in storybook

---

packages/main/src/components/MessageBox/MessageBox.jss.ts
packages/main/src/components/MessageBox/index.tsx

Fixes https://github.com/SAP/ui5-webcomponents-react/issues/4290

fix(MessageBox): adjust title style and level to latest Design specs

---

packages/main/src/components/DynamicPage/DynamicPage.cy.tsx
packages/main/src/components/DynamicPage/DynamicPage.mdx
packages/main/src/components/DynamicPage/DynamicPage.stories.tsx
packages/main/src/components/DynamicPage/index.tsx

feat(DynamicPage): enable sticky sub-headers support

---

packages/main/src/components/FilterGroupItem/index.tsx

fix(FilterGroupItem): add colon to labels

---

packages/main/src/components/Toolbar/Toolbar.cy.tsx
packages/main/src/components/Toolbar/index.tsx
packages/main/src/webComponents/ComboBox/ComboBox.stories.tsx

fix(Toolbar): recalculate overflow elements on children change

---

packages/main/src/components/MessageBox/index.tsx

fix(MessageBox - a11y): announce message boxes as alert dialog

---

packages/main/src/components/AnalyticalTable/AnalyticalTable.cy.tsx
packages/main/src/components/AnalyticalTable/AnalyticalTable.stories.tsx
packages/main/src/components/AnalyticalTable/TableBody/VirtualTableBodyContainer.tsx
packages/main/src/components/AnalyticalTable/hooks/useToggleRowExpand.ts
packages/main/src/components/AnalyticalTable/index.tsx
packages/main/src/components/AnalyticalTable/tableReducer/stateReducer.ts

fix(AnalyticalTable): don't scroll to top if expandable row is collapsed

---

packages/main/src/components/FilterGroupItem/index.tsx

Related to https://github.com/SAP/ui5-webcomponents/issues/6914

fix(FilterBar): don't show navigated-cell in filters-dialog table

---

packages/main/src/components/VariantManagement/ManageViewsTableRows.tsx
packages/main/src/components/VariantManagement/SaveViewDialog.tsx
packages/main/src/components/VariantManagement/VariantManagement.cy.tsx
packages/main/src/i18n/messagebundle.properties

fix(Variant Management): fix error message for duplicate variant names

---

packages/main/src/components/FilterBar/FilterBar.cy.tsx
packages/main/src/components/FilterGroupItem/index.tsx

fix(FilterGroupItem): don't show colon if label is empty

---

packages/main/src/components/AnalyticalTable/ColumnHeader/index.tsx

fix(AnalyticalTable): allow closing column popover by selection with SPACE key

---

packages/main/src/components/Toolbar/OverflowPopover.tsx
packages/main/src/components/Toolbar/Toolbar.cy.tsx
packages/main/src/components/Toolbar/index.tsx

feat(Toolbar): add `a11yConfig` prop

---

packages/base/src/hooks/useIsomorphicId.ts
packages/main/src/components/AnalyticalTable/pluginHooks/useIndeterminateRowSelection.tsx
packages/main/src/components/AnalyticalTable/pluginHooks/useManualRowSelect.ts
packages/main/src/internal/withWebComponent.tsx

fix(server-components): add missing use client directives

---

packages/main/src/components/Toolbar/Toolbar.stories.tsx

docs(Toolbar): use transparent buttons

---

packages/main/src/components/VariantManagement/ManageViewsTableRows.tsx
packages/main/src/components/VariantManagement/VariantItem.tsx
packages/main/src/components/VariantManagement/VariantManagement.cy.tsx
packages/main/src/components/VariantManagement/VariantManagement.stories.tsx

Spec: https://experience.sap.com/fiori-design-web/variant-management/#apply-view-automatically
This PR also replaces `aria-label` if `accessibleName` is available on the web component.

feat(VariantItem): add `applyAutomaticallyText` prop

---

packages/main/src/components/Toolbar/index.tsx

docs(Toolbar): improve `children` description

---

packages/main/src/webComponents/Dialog/Dialog.stories.tsx

docs(Dialog): fix "with content" story

---

packages/main/src/components/Toolbar/Toolbar.jss.ts

fix(Toolbar): correct child paddings

---

.storybook/preview-head.html
packages/main/src/webComponents/Dialog/Dialog.stories.tsx
packages/main/src/webComponents/Popover/Popover.stories.mdx
packages/main/src/webComponents/ResponsivePopover/ResponsivePopover.stories.mdx

Related to: https://github.com/SAP/ui5-webcomponents/issues/7354

docs(Dialog/Popovers): remove padding if Bar is slotted

---

packages/main/src/components/FormItem/index.tsx

fix(FormItem): apply bottom margin of group on custom Label

---

packages/main/src/components/ObjectStatus/ObjectStatus.jss.ts
packages/main/src/components/ObjectStatus/index.tsx

fix(ObjectStatus): apply latest available specs

---

packages/main/src/components/ThemeProvider/GlobalStyleClasses.jss.ts
packages/main/src/themes/CustomVariables.ts
packages/main/src/themes/base.ts
packages/main/src/themes/sap_belize.ts
packages/main/src/themes/sap_belize_hcb.ts
packages/main/src/themes/sap_belize_hcw.ts

fix: fix scrollbar styles for Belize theme

---

packages/main/src/components/AnalyticalTable/hooks/useKeyboardNavigation.ts
packages/main/src/components/AnalyticalTable/util/index.ts

feat(AnalyticalTable): allow resizing columns via Shift+ArrowLeft/Right

---

packages/main/src/components/DynamicPageTitle/DynamicPageTitle.cy.tsx
packages/main/src/components/DynamicPageTitle/DynamicPageTitle.jss.ts
packages/main/src/components/DynamicPageTitle/index.tsx

fix(DynamicPageTitle): spread `breadcrumbs` if only child

---

packages/main/src/components/VariantManagement/VariantManagement.cy.tsx
packages/main/src/components/VariantManagement/index.tsx

fix(VariantManagement): show search in view list popover if count is over 10

---

packages/main/src/components/DynamicPageTitle/DynamicPageTitle.jss.ts

fix(DynamicPageTitle): apply correct padding for `header`

---

packages/main/src/components/AnalyticalTable/TableBody/RowSubComponent.tsx

fix(AnalyticalTable): fix subcomponents calculation

---

package.json
yarn.lock

See https://github.com/remarkjs/remark-gfm/issues/57

chore(deps): rollback `remark-gfm` to v3

---

.storybook/mockData/generateMessageItems.tsx
packages/main/src/components/MessageView/MessageItem.tsx
packages/main/src/components/MessageView/index.tsx

Fixes #5076
Fixes #5077
Fixes #5078

fix(MessageView): fix overflow behavior and item selection

---

packages/main/src/components/SelectDialog/SelectDialog.mdx
packages/main/src/components/SelectDialog/SelectDialog.stories.tsx

docs(SelectDialog): fix multi-select story

---

packages/main/src/components/AnalyticalTable/AnalyticalTable.cy.tsx
packages/main/src/components/AnalyticalTable/index.tsx

fix(AnalyticalTable): fix horizontal scrolling in rtl reading direction

---

docs/MigrationGuide.archive.md

+ Especially the [How to Contribute](https://github.com/SAP/ui5-webcomponents-react/blob/main/CONTRIBUTING.md#contribute-code) section 
Closes #5159

docs: add delete information of `FilterType` in migration archive doc

---

packages/main/src/components/Form/Form.stories.tsx
packages/main/src/components/FormGroup/index.tsx

feat(FormGroup): make `titleText` optional

---

packages/main/src/webComponents/FileUploader/FileUploader.stories.mdx

docs(FileUploader): remove unnecessary story

---

packages/main/src/components/FilterBar/FilterBar.cy.tsx
packages/main/src/components/FilterBar/FilterDialog.tsx

fix(FilterBar): focus search input when dialog is opened

---

packages/main/src/components/FilterBar/index.tsx

fix(FilterBar): display action buttons in same row as filters if toolbar is hidden

---

examples/nextjs-app/app/components/AppShell.tsx
examples/nextjs-app/app/components/AppShellBar.module.css
examples/nextjs-app/app/components/AppShellBar.tsx
examples/nextjs-app/app/layout.tsx
examples/nextjs-app/app/todos/[id]/page.tsx

This PR also adds a theme-switch popover to the shellbar.

fix(Template - nextjs-app): fix assets import & ThemeProvider position

---

packages/main/src/components/FilterBar/FilterBar.jss.ts
packages/main/src/components/FilterBar/index.tsx
packages/main/src/components/FilterGroupItem/FilterGroupItem.jss.ts

fix(FilterBar): correct width of search field

---

packages/main/src/components/DynamicPage/DynamicPage.cy.tsx
packages/main/src/components/DynamicPage/index.tsx

fix(DynamicPage): smooth header collapse

---

packages/main/src/components/AnalyticalTable/index.tsx

fix(AnalyticalTable): fix endless loop when using next-js app router

---

packages/main/src/components/DynamicPageTitle/DynamicPageTitle.jss.ts

fix(DynamicPageTitle): remove inline-end margin of action items

---

packages/main/src/components/MessageViewButton/index.tsx

docs(MessageViewButton): add note about type `None`

---

packages/main/src/components/MessageView/MessageItem.tsx

missed in https://github.com/SAP/ui5-webcomponents-react/pull/5298

fix(MessageItem): use correct information icon color

---

.storybook/main.ts
package.json
yarn.lock

The changes were created by running the storybook script `npx storybook@latest upgrade`

chore(storybook): update `eslint-plugin-storybook` dep & use recommended `name` config

---

packages/main/src/components/AnalyticalTable/index.tsx

fix(AnalyticalTable): display `columns` correctly after update

---

packages/main/src/components/ObjectPage/index.tsx

fix(ObjectPage): prevent content flickering with single subsection

---

packages/main/src/components/Modals/ModalsProvider.tsx
packages/main/src/internal/ModalsContext.ts

fix(Modals): support multiple `ThemeProvider`

---

packages/main/src/components/AnalyticalTable/AnalyticalTable.cy.tsx
packages/main/src/components/AnalyticalTable/hooks/useKeyboardNavigation.ts

fix(AnalyticalTable): focus first named cell on TAB

---

packages/base/src/hooks/useIsRTL.ts
packages/main/src/components/ActionSheet/index.tsx
packages/main/src/components/Splitter/index.tsx
packages/main/src/components/SplitterLayout/SplitterLayout.cy.tsx
packages/main/src/components/Toolbar/index.tsx

To be aligned with https://github.com/SAP/ui5-webcomponents/pull/8241

refactor: use `:dir` pseudo selector for RTL detection

---

packages/main/src/components/AnalyticalTable/AnayticalTable.jss.ts

fix(AnalyticalTable): correct active styles of table rows

---

.storybook/mockData/Friends500.json
packages/main/src/components/AnalyticalTable/AnalyticalTable.cy.tsx
packages/main/src/components/AnalyticalTable/AnayticalTable.jss.ts
packages/main/src/components/AnalyticalTable/TableBody/VirtualTableBody.tsx
packages/main/src/components/AnalyticalTable/hooks/useRowHighlight.tsx
packages/main/src/components/AnalyticalTable/interfaces.ts
packages/main/src/components/AnalyticalTable/types/index.ts

feat(AnalyticalTable): allow `IndicationColor`s as row highlight color

---

packages/main/src/components/AnalyticalCard/AnalyticalCard.stories.tsx
packages/main/src/components/SplitterLayout/SplitterLayout.stories.tsx

`:dir()` is now supported
https://www.chromatic.com/docs/infrastructure-release-notes/#version-6

test(chromatic): enable chromatic snapshots for components using `:dir` again

---

packages/main/src/components/AnalyticalTable/AnalyticalTable.cy.tsx
packages/main/src/components/AnalyticalTable/AnalyticalTable.stories.tsx
packages/main/src/components/AnalyticalTable/PluginAnnounceEmptyCells.mdx
packages/main/src/components/AnalyticalTable/pluginHooks/AnalyticalTableHooks.ts
packages/main/src/components/AnalyticalTable/pluginHooks/useAnnounceEmptyCells.ts

feat(AnalyticalTable): introduce `useAnnounceEmptyCells` plugin hook

---

packages/main/src/components/FilterBar/FilterDialog.tsx

fix(FilterBar): fix bubbling of `selection-change` event in dialog

---

packages/main/src/components/FilterBar/index.tsx
packages/main/src/components/VariantManagement/ManageViewsDialog.tsx

fix(FilterBar & VariantManagement): fix tablet device detection

---

packages/main/src/components/Form/index.tsx

fix(Form): don't change layout if form has no width

---

.github/workflows/test.yml
packages/main/src/components/VariantManagement/VariantManagement.cy.tsx

test(VariantManagement): fix fuzzy test

---

packages/cli/package.json

chore(cli): publish to npm

---

packages/main/src/components/MessageBox/index.tsx

fix(MessageBox): replace duplicate `footer` and `header` tag

---

packages/main/src/components/FormItem/index.tsx
packages/main/src/types/index.ts

fix(FormItem - TypeScript): improve children type and add note outlining unsupported values

---

packages/main/src/components/ObjectPage/ObjectPage.cy.tsx
packages/main/src/components/ObjectPage/index.tsx

fix(ObjectPage): escape unsupported chars for `id` of sections

---

packages/main/src/components/FormItem/index.tsx

fix(Form): adjust vertical layout padding

---

packages/main/src/components/AnalyticalTable/TableBody/VirtualTableBody.tsx

Fixes #5609
#5659 needs to be merged first

fix(AnalyticalTable): calculate empty cell width correctly

---

packages/main/src/components/Splitter/index.tsx

fix(SplitterLayout): improve drag and drop behavior

---

docs/knowledge-base/Styling.mdx
packages/charts/package.json
packages/main/src/components/ThemeProvider/index.tsx

chore(charts): add `exports` path for `styles.css`

---

packages/main/src/components/ThemeProvider/index.tsx

fix(ThemeProvider): fix style injection and removal in case multiple ThemeProviders are used

---

packages/main/src/components/ObjectStatus/index.tsx

fix(ObjectStatus): always announce state via screen reader

---

packages/main/src/components/VariantManagement/ManageViewsTableRows.tsx

fix(VariantManagement): fix "Manage Views" default validation

---

packages/main/src/components/ObjectStatus/index.tsx

fix(ObjectStatus): don't announce default icons via screen readers

---

packages/main/src/webComponents/RadioButton/RadioButton.stories.tsx

docs(RadioButton): add `radiogroup` role to group container

---

packages/main/src/components/AnalyticalTable/types/index.ts

docs(AnalyticalTable): add `since` note for `highlightField` indication colors

---

packages/main/src/components/DynamicPageTitle/index.tsx

docs(DynamicPageTitle): outline supported `actions` components

---

packages/main/src/components/AnalyticalTable/AnalyticalTable.module.css

fix(AnalyticalTable): improve focus border alignment

---

packages/main/src/components/Form/Form.module.css

fix(Form): use correct container query if width is float

---

packages/main/src/components/AnalyticalTable/pluginHooks/useRowDisableSelection.tsx

fix(AnalyticalTable - `useRowDisableSelection`): remove `title` from select-all cell

---

packages/main/src/components/AnalyticalTable/AnalyticalTable.module.css
packages/main/src/components/AnalyticalTable/Test.module.css

refactor(AnalyticalTable): harmonize cell focus for body & header cells

---

packages/main/src/components/MessageView/MessageView.mdx
packages/main/src/components/MessageView/MessageView.stories.tsx

docs(MessageView): adjust dialog example

---

packages/main/src/components/DynamicPage/DynamicPage.module.css
packages/main/src/components/DynamicPage/index.tsx

fix(DynamicPage): always show focused element when Tabbing in content

---

packages/main/src/components/AnalyticalCardHeader/AnalyticalCardHeader.module.css
packages/main/src/components/ObjectPageAnchorBar/ObjectPageAnchorBar.module.css
packages/main/src/components/ThemeProvider/index.tsx
packages/main/src/components/VariantManagement/ManageViewsDialog.module.css

fix: apply correct scoping for internal ui5wc CSS vars

---

packages/main/src/components/DynamicPageHeader/DynamicPageHeader.module.css

fix(ObjectPage): apply correct height for collapsed header spacing div

---

packages/main/src/components/ObjectPage/ObjectPage.module.css

fix(ObjectPage): increase header z-index

---

packages/main/src/components/AnalyticalTable/hooks/useRowSelectionColumn.tsx

fix(AnalyticalTable): add `aria-hidden` to multi selection checkboxes

---

packages/main/src/components/DynamicPageHeader/DynamicPageHeader.module.css

fix(DynamicPageHeader): remove `width`

---

packages/main/src/components/AnalyticalTable/ColumnHeader/ColumnHeaderModal.module.css
packages/main/src/components/AnalyticalTable/ColumnHeader/ColumnHeaderModal.tsx

fix(AnalyticalTable): add "Filter" text to column popover

---

packages/main/src/components/AnalyticalTable/defaults/Column/PopIn.module.css

fix(AnalyticalTable): fix pop-in content styles

---

packages/main/src/components/DynamicPageHeader/DynamicPageHeader.module.css

fix(DynamicPageHeader): correctly apply width to header

---

packages/main/src/components/AnalyticalTable/ColumnHeader/ColumnHeaderModal.tsx

fix(AnalyticalTable): correct `CustomElementsScope` import path

---

docs/MigrationGuide.mdx
packages/main/src/components/AnalyticalTable/AnalyticalTable.cy.tsx
packages/main/src/components/AnalyticalTable/hooks/useRowSelectionColumn.tsx
packages/main/src/components/AnalyticalTable/hooks/useSelectionChangeCallback.ts

BREAKING CHANGE: `selectedFlatRows` has been removed from the `detail` object of `onRowSelect`.

refactor(AnalyticalTable): remove `selectedFlatRows` & add `rowsById` to `onRowSelect`

---

packages/base/src/index.ts
packages/charts/src/index.ts
packages/compat/src/index.ts
packages/main/src/index.ts

JSON imports are not compatible with all frameworks/build tools.

fix: remove json export from root index files

---

config/layers-plugin.js
config/postcss-config-factory.js

feat: wrap all styles in ui5-webcomponents-react css layer

---

packages/base/src/stores/StyleStore.ts

fix: scope internal style store per Web Components runtime

---

packages/main/src/components/Splitter/Splitter.module.css

fix(SplitterLayout): fix cursor for vertical resize

---

tsconfig.base.json

https://devblogs.microsoft.com/typescript/announcing-typescript-5-6/#the---nouncheckedsideeffectimports-option

chore(TypeScript): enable noUncheckedSideEffectImports option

---

packages/main/src/webComponents/ShellBar/ShellBar.mdx

docs(ShellBar): update popover example

---

.storybook/components/Import.tsx
packages/compat/src/components/Table/Table.mdx

Related issue: https://github.com/SAP/ui5-webcomponents/issues/9920

docs(compat - Table): outline compatibility

---

packages/charts/src/interfaces/IChartBaseProps.ts

docs(charts): improve `dataset` description

---

docs/Welcome.mdx

https://github.com/SAP/ui5-webcomponents/commit/9358e968882214e3a65713f8b7a2ee303817a3f8

docs: update EOS of v1

---

templates/nextjs-app/app/clientAssetsImport.ts
templates/nextjs-app/app/layout.tsx

docs(nextjs-app - template): import assets on client

---

.storybook/components/DocsHeader.tsx
.storybook/tsconfig.json
packages/charts/src/components/BarChart/BarChart.mdx
packages/charts/src/components/BulletChart/BulletChart.mdx
packages/charts/src/components/ColumnChart/ColumnChart.mdx
packages/charts/src/components/ColumnChartWithTrend/ColumnChartWithTrend.mdx
packages/charts/src/components/ComposedChart/ComposedChart.mdx
packages/charts/src/components/DonutChart/DonutChart.mdx
packages/charts/src/components/LineChart/LineChart.mdx
packages/charts/src/components/PieChart/PieChart.mdx
packages/charts/src/components/RadarChart/RadarChart.mdx
packages/charts/src/components/RadialChart/RadialChart.mdx
packages/charts/src/components/ScatterChart/ScatterChart.mdx
packages/charts/src/components/TimelineChart/TimeLineChart.mdx
tsconfig.json

This PR also adds a `tsconfig.json` to the `.storybook` folder and fixes a misconfiguration in the root tsconfig.

docs(charts): outline a11y limitations

---

packages/main/src/components/ObjectPageSubSection/ObjectPageSubSection.module.css

fix(ObjectPageSubSection): update styles to latest specs

---

packages/main/src/components/FilterBar/FilterDialog.tsx

fix(FilterBar): add tooltip for list-view SegmentedButtonItem

---

packages/main/src/components/AnalyticalTable/AnalyticalTable.module.css
packages/main/src/components/AnalyticalTable/hooks/useRowHighlight.tsx

fix(AnalyticalTable): border styles

---

packages/main/src/components/ObjectPage/ObjectPage.mdx
packages/main/src/components/ObjectPage/ObjectPageUtils.ts
packages/main/src/components/ObjectPage/index.tsx

Fixes #6478
Todo: check v1 downport feasibility

fix(ObjectPage): improve selection & scroll behavior

---

.github/workflows/release.yml
packages/compat/package.json
yarn.lock

fix(compat): update `@ui5/webcomponents-react` peer-dep

---

.storybook/manager-head.html
.storybook/preview-head.html

This PR also styles the search input to look more like a Horizon input and improves some general styles.
Related to https://github.com/SAP/ui5-webcomponents/issues/9917

docs(sb): disable `forced-color-adjust` & update styles

---

packages/main/src/components/AnalyticalTable/index.tsx

fix(AnalyticalTable): calculate column width correctly when grouping

---

docs/MigrationGuide.mdx

docs(Migration guide): fix sapUiSmallMarginBeginEnd to sapUiSmallMarginTopBottom in docs

---

packages/main/src/components/AnalyticalTable/defaults/Column/Expandable.tsx

fix(AnalyticalTable): remove unnecessary `aria-expanded`

---

.storybook/mockData/generateMessageItems.tsx
packages/main/src/components/MessageView/MessageView.stories.tsx
packages/main/src/components/MessageViewButton/index.tsx
packages/main/src/i18n/messagebundle.properties

fix(MessageViewButton): add default tooltip & aria-label

---

packages/base/src/stores/StyleStore.ts

fix(StyleStore): fix stale reference leading to memory leak

---

packages/main/src/components/ObjectStatus/ObjectStatus.module.css

fix(ObjectStatus): fix icon alignment in large & inverted mode

---

packages/main/src/webComponents/Page/Page.stories.tsx

Related issue: https://github.com/SAP/ui5-webcomponents/issues/10358

docs(Page): nest footer in div

---

packages/main/src/components/FilterBar/FilterBar.cy.tsx
packages/main/src/components/FilterBar/FilterDialog.tsx

fix(FilterBar): correct callback values for `onFiltersDialogSelectionChange`

---

packages/main/src/components/MessageView/MessageItem.module.css
packages/main/src/components/MessageView/MessageView.stories.tsx
packages/main/src/components/MessageView/index.tsx

fix(MessageView): fix group order

---

packages/main/src/components/MessageViewButton/index.tsx

fix(MessageViewButton): correct tooltips

---

packages/main/src/components/ObjectPage/ObjectPage.cy.tsx
packages/main/src/components/ObjectPage/ObjectPageUtils.ts
packages/main/src/components/ObjectPage/index.tsx

fix(ObjectPage): scroll to section when programmatically selected

---

packages/main/src/components/Modals/Modals.stories.tsx
packages/main/src/webComponents/Dialog/Dialog.stories.tsx

docs(Dialog): fix footer role

---

packages/main/src/components/AnalyticalTable/AnalyticalTable.mdx
packages/main/src/components/AnalyticalTable/AnalyticalTable.stories.tsx
packages/main/src/components/AnalyticalTable/types/index.ts

docs(AnalyticalTable): improve `infiniteScroll` description & story

---

packages/main/src/components/SelectDialog/SelectDialog.mdx
packages/main/src/components/SelectDialog/SelectDialog.stories.tsx

docs(SelectDialog): use `onSelectionChange` event instead of `onItemClick`

---

docs/MigrationGuide.mdx

docs(MigrationGuide): Fix typo

---

packages/main/src/components/Splitter/Splitter.module.css
packages/main/src/components/Splitter/index.tsx

fix(SplitterLayout): implement latest design specs 

---

packages/main/src/webComponents/ColorPalettePopover/ColorPalettePopover.stories.tsx
packages/main/src/webComponents/Popover/Popover.stories.tsx
packages/main/src/webComponents/ResponsivePopover/ResponsivePopover.stories.tsx
packages/main/src/webComponents/UserMenu/UserMenu.stories.tsx
packages/main/src/webComponents/ViewSettingsDialog/ViewSettingsDialog.stories.tsx

docs(popups): allow opening popups via Storybook controls

---

packages/main/src/components/ObjectPageSection/index.tsx
packages/main/src/components/ObjectPageSubSection/index.tsx

docs(ObjectPage): outline when to use subsections

---

packages/base/src/utils/index.ts

fix(base): correct `getEffectiveScopingSuffixForTag` import path

---

packages/compat/src/components/Toolbar/Toolbar.mdx

docs(Toolbar (compat)): update "close overflow popover" docs

---

packages/compat/src/components/Toolbar/OverflowPopover.tsx
packages/compat/src/components/Toolbar/Toolbar.cy.tsx
packages/compat/src/components/Toolbar/index.tsx

fix(Toolbar (compat)): exclude spacer from overflow popover

---

packages/main/src/components/AnalyticalTable/AnalyticalTable.cy.tsx
packages/main/src/components/AnalyticalTable/TableBody/VirtualTableBodyContainer.tsx
packages/main/src/components/AnalyticalTable/scrollbars/VerticalScrollbar.tsx

fix(AnalyticalTable): fix focus behavior when tabbing

---

packages/main/src/components/AnalyticalTable/AnalyticalTable.stories.tsx
packages/main/src/components/AnalyticalTable/defaults/Column/ColumnHeaderModal.tsx
packages/main/src/components/AnalyticalTable/types/index.ts

fix(AnalyticalTable): align column popover based on `hAlign`

---

packages/main/src/components/ObjectPage/ObjectPage.module.css
packages/main/src/components/ObjectPage/index.tsx

fix(ObjectPage): use full width for header content if no image is set

---

packages/main/src/components/FilterBar/FilterDialog.tsx

fix(FilterBar): fix reordering in `StrictMode`

---

packages/main/src/components/MessageBox/index.tsx

cherry-picked: https://github.com/SAP/ui5-webcomponents-react/commit/57b9b5412a527d6e628407c02bb3f807e6adc837

fix(MessageBox): always create valid id for `String` action button 

---

packages/main/src/components/VariantManagement/index.tsx

fix(VariantManagement): allow quotes in VariantItem name

---

packages/main/src/i18n/messagebundle_fr.properties

fix(i18n): update french translation of cancel

---

.storybook/components/languageCodes.json

Related to: https://github.com/SAP/ui5-webcomponents/issues/11233

docs(i18n): update available languages

---

.storybook/manager-head.html
packages/main/src/webComponents/Search/Search.mdx
packages/main/src/webComponents/Table/Table.mdx
packages/main/src/webComponents/Table/Table.stories.tsx

The commit also removes the custom styling of the Storybook search input

docs: outline experimental components & remove deprecated APIs

---

packages/main/src/components/ObjectPage/ObjectPage.cy.tsx
packages/main/src/components/ObjectPage/index.tsx

fix(ObjectPage): fix programmatic section selection in `IconTabBar` `mode`

---

packages/compat/src/components/Toolbar/Toolbar.module.css

fix(Toolbar - compat): apply same bg colors as ui5-webcomponents Toolbar

---

packages/main/src/components/ObjectPage/ObjectPage.cy.tsx
packages/main/src/components/ObjectPage/index.tsx

fix(ObjectPage): fire onSelectedSectionChange correctly in IconTabBar `mode`

---

packages/main/src/components/AnalyticalCardHeader/index.tsx

fix(AnalyticalCardHeader): fix `role`

---

packages/main/src/components/ObjectPage/index.tsx

Fixes #7057
Related Chromium bug: https://issues.chromium.org/issues/41435274

fix(ObjectPage): fix scroll-into-view behavior for Chromium browsers

---

packages/main/src/components/ObjectStatus/ObjectStatus.module.css
packages/main/src/components/ObjectStatus/ObjectStatus.stories.tsx

fix(ObjectStatus): implement focus deltas for hc theme

---

packages/main/src/webComponents/Tag/Tag.stories.tsx

Remnant of v1 `Badge` example.

docs(Tag): remove `Set3` `design` example

---

packages/main/src/components/AnalyticalTable/defaults/Column/ColumnHeaderModal.tsx
packages/main/src/components/AnalyticalTable/defaults/FilterComponent/index.tsx
packages/main/src/components/AnalyticalTable/types/index.ts

fix(AnalyticalTable): improve screen reader announcement for filter input

---

packages/main/src/components/AnalyticalTable/AnalyticalTable.cy.tsx
packages/main/src/components/AnalyticalTable/index.tsx
packages/main/src/components/AnalyticalTable/tableReducer/stateReducer.ts
packages/main/src/components/AnalyticalTable/types/index.ts

feat(AnalyticalTable): introduce `onFilter` callback prop

---

packages/main/src/components/AnalyticalTable/AnalyticalTableHooks.stories.tsx
packages/main/src/components/AnalyticalTable/PluginAnnounceEmptyCells.mdx
packages/main/src/components/AnalyticalTable/PluginDisableRowSelection.mdx
packages/main/src/components/AnalyticalTable/PluginIndeterminateRowSelection.mdx
packages/main/src/components/AnalyticalTable/PluginManualRowSelect.mdx
packages/main/src/components/AnalyticalTable/PluginOnColumnResize.mdx
packages/main/src/components/AnalyticalTable/PluginOrderedMultiSort.mdx
packages/main/src/components/AnalyticalTable/types/index.ts

docs(AnalyticalTable): memoize `tableHooks`

---

packages/main/src/components/MessageViewButton/MessageViewButton.cy.tsx
packages/main/src/components/MessageViewButton/index.tsx

fix(MessageViewButton): remove `counter` restriction

---

packages/main/src/webComponents/Table/Table.stories.tsx

docs(Table): fix selection example

---

packages/main/src/components/SelectDialog/index.tsx

fix(SelectDialog): adjust heading level to `h1`

---

packages/charts/src/components/BarChart/BarChart.tsx
packages/charts/src/components/BulletChart/BulletChart.tsx
packages/charts/src/components/ColumnChart/ColumnChart.tsx
packages/charts/src/components/ComposedChart/index.tsx
packages/charts/src/components/LineChart/LineChart.tsx
packages/charts/src/components/PieChart/PieChart.tsx
packages/charts/src/components/RadarChart/RadarChart.tsx
packages/charts/src/components/ScatterChart/ScatterChart.tsx
packages/charts/src/hooks/useLabelFormatter.cy.tsx
packages/charts/src/hooks/useLabelFormatter.ts
packages/charts/src/interfaces/IChartDimension.ts
packages/charts/src/interfaces/IChartMeasure.ts
packages/charts/src/interfaces/index.ts
packages/charts/src/internal/Utils.ts
packages/charts/src/internal/XAxisTicks.tsx
packages/charts/src/internal/YAxisTicks.tsx

prerequisite for feature #7597

refactor(charts): refactor formatter logic

---

packages/main/src/components/ObjectStatus/ObjectStatus.module.css

fix(ObjectStatus): implement delta styles for Quartz theme

---

packages/main/src/components/ObjectPage/ObjectPage.stories.tsx

docs(ObjectPage): replace navigation actions
