UI5/webcomponents-react

packages/charts/src/components/ChartContainer/withChartContainer.tsx
packages/docs/.storybook/TableComponent.tsx
packages/main/__karma_snapshots__/ActionSheet.md
packages/main/__karma_snapshots__/AnalyticalTable.md
packages/main/__karma_snapshots__/Icon.md
packages/main/__karma_snapshots__/ObjectPage.md
packages/main/__karma_snapshots__/ShellBarItem.md
packages/main/package.json
packages/main/scripts/wrapperGeneration/generateTypingsWeb.js
packages/main/src/components/ActionSheet/index.tsx
packages/main/src/components/AnalyticalTable/columnHeader/ColumnHeaderModal.tsx
packages/main/src/components/ObjectPage/ObjectPageAnchor.tsx
packages/main/src/components/ThemeProvider/index.tsx
packages/main/src/webComponents/Button/index.tsx
packages/main/src/webComponents/Icon/index.tsx
packages/main/src/webComponents/MultiComboBox/index.tsx
packages/main/src/webComponents/Popover/demo.stories.tsx
packages/main/src/webComponents/Popover/index.tsx
packages/main/src/webComponents/Popup/index.tsx
packages/main/src/webComponents/ShellBarItem/index.tsx
scripts/rollup/results.json
yarn.lock

Updated underlying Web Components to `v1.0.0-rc.2`.
**ShellBarItem**: prop `onPress` is renamed to `onClick`
**Dialog**: remove prop `noHeader`
**Popup**: remove prop `noHeader`
Please also check the [UI5 Web Components Release Notes](https://github.com/SAP/ui5-webcomponents/releases/tag/v1.0.0-rc.2)

 feat(WebComponents): Updated to v1.0.0-rc.2

---

packages/main/src/components/ThemeProvider/index.tsx

Every Theme Provider was injecting the fiori3 parameters into the document head. This caused some errors. Therefore we now inject new parameters only if they are not present yet.

fix(ThemeProvider): Only inject theme properties if they are not present

---

packages/main/src/components/ActionSheet/index.tsx
packages/main/src/components/Spinner/Spinner.jss.ts
packages/main/src/components/Spinner/Spinner.test.tsx
packages/main/src/components/Spinner/__snapshots__/Spinner.test.tsx.snap
packages/main/src/components/Spinner/index.tsx

fix(Spinner): Enabled Spinning again

---

packages/main/__karma_snapshots__/FilterBar.md
packages/main/src/components/FilterItem/index.tsx

fix(FilterItem): BusyIndicator is displayed when loading prop is true

---

packages/main/__karma_snapshots__/DayPicker.md
packages/main/__karma_snapshots__/FilterBar.md
packages/main/__karma_snapshots__/VariantManagement.md
packages/main/src/components/VariantManagement/index.tsx

fix(VariantManagemen): removed unused prop enabled

---

packages/main/__karma_snapshots__/ObjectPage.md
packages/main/src/components/ObjectPage/ObjectPage.karma.tsx
packages/main/src/components/ObjectPage/index.tsx

The `ObjectPage` was crashing in case there was only one `ObjectPageSection` provided.

fix(ObjectPage): Don't crash in default mode with only 1 child provided

---

packages/main/__karma_snapshots__/Carousel.md
packages/main/src/components/Carousel/Carousel.jss.ts
packages/main/src/components/Carousel/Carousel.karma.tsx
packages/main/src/components/Carousel/CarouselPagination.jss.ts
packages/main/src/components/Carousel/CarouselPagination.tsx
packages/main/src/components/Carousel/demo.stories.tsx
packages/main/src/components/Carousel/index.tsx

Fixes #95 
The Pagination Bar is now hidden in case the arrowPlacement is in the content and showPagination is set to false.
In addition, the component is now refactored from a HOC implementation to a forwarfRef implementation.

fix(Carousel): Hide Pagination Bar if not required

---

packages/main/__karma_snapshots__/ActionSheet.md
packages/main/__karma_snapshots__/AnalyticalCard.md
packages/main/__karma_snapshots__/AnalyticalTable.md
packages/main/__karma_snapshots__/Avatar.md
packages/main/__karma_snapshots__/Badge.md
packages/main/__karma_snapshots__/BusyIndicator.md
packages/main/__karma_snapshots__/Button.md
packages/main/__karma_snapshots__/Calendar.md
packages/main/__karma_snapshots__/CalendarHeader.md
packages/main/__karma_snapshots__/Card.md
packages/main/__karma_snapshots__/Carousel.md
packages/main/__karma_snapshots__/FilterBar.md
packages/main/__karma_snapshots__/MessageBox.md
packages/main/__karma_snapshots__/ObjectPage.md
packages/main/__karma_snapshots__/ObjectStatus.md
packages/main/__karma_snapshots__/ProgressIndicator.md
packages/main/__karma_snapshots__/SegmentedButtonItem.md
packages/main/__karma_snapshots__/Text.md
packages/main/__karma_snapshots__/VariantManagement.md
packages/main/src/components/ThemeProvider/index.tsx

With the `jss` prop, you can pass a custom JSS instance if required.
With the `noInjectThemeProperties`, you can skip the injection of the UI5 Web Components Theming Variables

feat(ThemeProvider): Add jss and noInjectThemeProperties prop

---

packages/main/__karma_snapshots__/Carousel.md
packages/main/src/components/Carousel/Carousel.jss.ts
packages/main/src/components/Carousel/Carousel.karma.tsx
packages/main/src/components/Carousel/CarouselPagination.jss.ts
packages/main/src/components/Carousel/CarouselPagination.tsx
packages/main/src/components/Carousel/demo.stories.tsx
packages/main/src/components/Carousel/index.tsx

Change active page via Arrow-Left and Arrow-Right. Basic RTL Support
Closes #96

feat(Carousel): Added Keyboard Navigation

---

packages/main/src/components/ThemeProvider/index.tsx

Wrapping injectThemeVariables in requestAnimationFrame so that it won´t interfere with style tag initialization by UI5 Web Components.

fix(ThemeProvider): Css Variable Injection

---

packages/main/src/components/ThemeProvider/index.tsx

create own style tag containing css variables to avoid race conditions with ui5 webcomponents css variables style tag

fix(ThemeProvider): create own style tag containing css variables

---

packages/main/package.json
packages/main/src/components/AnalyticalTable/hooks/utils.ts
packages/main/src/components/AnalyticalTable/index.tsx
packages/main/src/components/AnalyticalTable/virtualization/VirtualTableBody.tsx
yarn.lock

The `AnalyticalTable` component was crashing as soon as there were no columns (empty array) provided.
This PR is also fixing a resizing issue.

fix(AnalyticalTable): Don't crash when no columns provided

---

packages/main/src/internal/withWebComponent.tsx
packages/main/src/webComponents/Dialog/demo.stories.tsx

Removed `innerStyles` prop in favour of css variables and UI5's `addCustomCSS` API
Fixes #181

fix(withWebComponent): Bind unknown events & cleanup

---

packages/base/src/index.ts
packages/base/src/lib/Utils.ts
packages/base/src/utils/index.ts
packages/main/src/components/ObjectPage/ObjectPage.jss.ts
packages/main/src/components/ObjectPage/__snapshots__/ObjectPage.test.tsx.snap
packages/main/src/components/ObjectPage/index.tsx

fix(ObjecPage): fix scrollbar width on windows

---

packages/main/src/components/AnalyticalTable/__snapshots__/AnalyticalTable.test.tsx.snap
packages/main/src/components/AnalyticalTable/demo/demo.stories.tsx
packages/main/src/components/AnalyticalTable/index.tsx
packages/main/src/components/AnalyticalTable/virtualization/Cell.tsx
packages/main/src/components/AnalyticalTable/virtualization/VirtualTableBody.tsx
scripts/rollup/results.json

Fixes Grouping and Aligment for grouped cells
BREAKING CHANGE: If used as a tree table, the prop `isTreeTable` is now mandatory
Closes #117

fix(AnalyticalTable): Fix Grouping

---

README.md

In the readme the sample code for the button doesn't work. 
Changed in: https://github.com/SAP/ui5-webcomponents-react/pull/48

Use onClick instead of onPress for button sample

---

packages/main/src/components/Notification/Notification.jss.ts
packages/main/src/components/Notification/__snapshots__/Notification.test.tsx.snap
packages/main/src/components/Notification/demo.stories.tsx
packages/main/src/components/Notification/index.tsx
packages/main/src/components/NotificationGroup/__snapshots__/Notification.test.tsx.snap
packages/main/src/components/NotificationGroup/demo.stories.tsx

fix(Notification): Added onClose prop, fixed semantic-icon size

---

packages/main/src/components/ThemeProvider/index.tsx

Remove custom theme injection on Theme Provider as all required CSS variables are now injected by the UI5 Web Components.
BREAKING CHANGE: Removed prop `noInjectThemeProperties` as this is now handled by the UI5 Web Components

refactor(ThemeProvider): Remove custom Theme Injection

---

packages/main/src/components/AnalyticalTable/AnalyticalTable.test.tsx
packages/main/src/components/AnalyticalTable/ColumnHeader/ColumnHeaderModal.tsx
packages/main/src/components/AnalyticalTable/__snapshots__/AnalyticalTable.test.tsx.snap
packages/main/src/components/AnalyticalTable/demo/demo.stories.tsx
packages/main/src/components/AnalyticalTable/hooks/useTableCellStyling.ts
packages/main/src/components/AnalyticalTable/hooks/useTableHeaderGroupStyling.ts
packages/main/src/components/AnalyticalTable/hooks/useTableHeaderStyling.ts
packages/main/src/components/AnalyticalTable/hooks/useTableRowStyling.ts
packages/main/src/components/AnalyticalTable/hooks/useTableStyling.ts
packages/main/src/components/AnalyticalTable/hooks/useToggleRowExpand.ts
packages/main/src/components/AnalyticalTable/index.tsx
packages/main/src/components/AnalyticalTable/types/ColumnType.ts
packages/main/src/components/AnalyticalTable/virtualization/VirtualTableBody.tsx
packages/main/src/enums/TableSelectionMode.ts
packages/main/src/index.ts
packages/main/src/lib/TableSelectionMode.ts

Allows different selection modes via `TableSelectionMode` enum with values `NONE`, `SINGLE_SELECT`, `MULTI_SELECT`
BREAKING CHANGE: Replace prop `selectable` with `selectionMode`

feat(AnalyticalTable): Add prop selectionMode

---

packages/main/src/components/Form/CurrentViewportRangeContext.ts
packages/main/src/components/Form/FormItem/index.tsx
packages/main/src/components/Form/index.tsx
packages/main/src/index.ts
packages/main/src/lib/CurrentViewportRangeContext.ts
scripts/rollup/results.json

every form item had his own context as it was part of the bundled file. Now the Form shares a context with the FormItems.
Fixes #274

fix(Form): Use shared context for Form and FormItem

---

packages/main/src/components/Avatar/Avatar.test.tsx
packages/main/src/components/Avatar/index.tsx

fix(Avatar): Don't crash onClick when no handler is passed

---

packages/main/package.json
packages/main/src/components/AnalyticalCard/index.tsx
packages/main/src/components/AnalyticalCardHeader/index.tsx
packages/main/src/components/AnalyticalTable/ColumnHeader/index.tsx
packages/main/src/components/AnalyticalTable/index.tsx
packages/main/src/components/Avatar/index.tsx
packages/main/src/components/Carousel/CarouselPagination.tsx
packages/main/src/components/Carousel/index.tsx
packages/main/src/components/FilterBar/index.tsx
packages/main/src/components/Form/FormGroup/index.tsx
packages/main/src/components/Form/FormItem/index.tsx
packages/main/src/components/Form/index.tsx
packages/main/src/components/Loader/index.tsx
packages/main/src/components/MessageBox/index.tsx
packages/main/src/components/MessageToast/index.tsx
packages/main/src/components/Notification/index.tsx
packages/main/src/components/ObjectPageSection/index.tsx
packages/main/src/components/ObjectPageSubSection/index.tsx
packages/main/src/components/ObjectStatus/index.tsx
packages/main/src/components/Page/index.tsx
packages/main/src/components/ProgressIndicator/index.tsx
packages/main/src/components/SegmentedButtonItem/index.tsx
packages/main/src/components/SideNavigation/index.tsx
packages/main/src/components/SideNavigationListItem/index.tsx
packages/main/src/components/Text/index.tsx
packages/main/src/components/VariantManagement/index.tsx
scripts/rollup/results.json
tsconfig.json
typings/react-jss.d.ts
yarn.lock

Update `react-jss` to `10.0.4` to get rid of all the typescript errors.
This is also re-introducing the `<JSSTheme` type

chore: update react-jss to 10.0.4

---

packages/main/src/components/AnalyticalTable/AnayticalTable.jss.ts
packages/main/src/components/AnalyticalTable/__snapshots__/AnalyticalTable.test.tsx.snap
packages/main/src/components/AnalyticalTable/hooks/useTableRowStyling.ts
packages/main/src/components/AnalyticalTable/index.tsx
packages/main/src/components/AnalyticalTable/virtualization/VirtualTableRow.tsx

Since we switched to the useBlockLayout hook, the visualization of empty rows which are added by the minRows prop was broken, as the cells now need specific styling provided by react-table, which the didn´t get. 
This is now fixed + the logic to determin table body height was adjusted. minRows should only be taken into account here, if the actual number of rows is lower than visibleRows.

fix(AnalyticalTable): fix broken empty row visualization

---

packages/main/src/components/AnalyticalTable/__snapshots__/AnalyticalTable.test.tsx.snap
packages/main/src/components/AnalyticalTable/hooks/useColumnsDependencies.ts
packages/main/src/components/AnalyticalTable/hooks/useDynamicColumnWidths.ts
packages/main/src/components/AnalyticalTable/index.tsx
packages/main/src/components/AnalyticalTable/virtualization/VirtualTableRow.tsx

- if the table doesn´t have data and loading is true, it now shows the Placeholder loading again
- fixed weird looking table headers with scaleWidthMode Grow in loading state
- table cell renderer is now not being called for empty rows which were inserted because of the minRows prop

fix(AnalyticalTable): fix minRows + loading behaviour

---

packages/base/src/styling/CssSizeVariables.ts
packages/main/src/components/Bar/Bar.jss.ts
packages/main/src/components/Bar/__snapshots__/Bar.test.tsx.snap
packages/main/src/components/Bar/demo.stories.tsx
packages/main/src/components/Bar/index.tsx
packages/main/src/components/Page/__snapshots__/Page.test.tsx.snap
packages/main/src/enums/BarDesign.ts
packages/main/src/internal/withWebComponent.tsx
packages/main/src/lib/BarDesign.ts
packages/main/src/webComponents/Icon/demo.stories.tsx

I don't know why the containers were absolute positioned. I refactored them so they are using `space-between` now. If my changes would break functionality feel free to roll them back.
What definitely has to be adjusted is the following line `lineHeight: CssSizeVariables.sapWcrBarHeight` as this breaks the alignment of the label inside of the `Input` and I guess there are even more components affected by this.
Fixes #319

fix(Bar): Alignment

---

.storybook/preview.js
config/jestsetup.ts
packages/base/src/polyfill/IE11.ts
packages/main/package.json
packages/main/src/components/AnalyticalTable/AnalyticalTable.test.tsx
packages/main/src/components/AnalyticalTable/__snapshots__/AnalyticalTable.test.tsx.snap
packages/main/src/components/AnalyticalTable/defaults/Column/Expandable.tsx
packages/main/src/components/AnalyticalTable/defaults/Column/Grouped.tsx
packages/main/src/components/AnalyticalTable/demo/demo.stories.tsx
packages/main/src/components/AnalyticalTable/demo/generateData.ts
packages/main/src/components/AnalyticalTable/hooks/useColumnsDependencies.ts
packages/main/src/components/AnalyticalTable/hooks/useToggleRowExpand.ts
packages/main/src/components/AnalyticalTable/index.tsx
packages/main/src/components/AnalyticalTable/tableReducer/stateReducer.ts
packages/main/src/components/AnalyticalTable/virtualization/VirtualTableRow.tsx
yarn.lock

This PR updates react-table to the stable 7.0.0 version and fixes several issues with the display of the selection column in TreeTable mode.
Closes #333 
Closes #336

fix(AnalyticalTable): Update react-table and fix TreeTable selection columns

---

packages/charts/src/components/BarChart/BarChart.tsx
packages/charts/src/components/ColumnChart/ColumnChart.tsx
packages/charts/src/components/ComposedChart/index.tsx
packages/charts/src/components/LineChart/LineChart.tsx
packages/charts/src/components/PieChart/PieChart.tsx
packages/charts/src/hooks/useLabelElements.ts
packages/charts/src/internal/ChartContainer.tsx
packages/charts/src/internal/CustomElements.tsx

charts/fix: fix(chartContainer): data handling

---

packages/base/src/hooks/usePassThroughHtmlProps.ts
packages/main/src/components/AnalyticalCardHeader/index.tsx
packages/main/src/components/Avatar/index.tsx
packages/main/src/components/Carousel/index.tsx
packages/main/src/components/FlexBox/FlexBox.test.tsx
packages/main/src/components/Form/index.tsx
packages/main/src/components/Notification/index.tsx
packages/main/src/components/SegmentedButtonItem/index.tsx
packages/main/src/components/VariantManagement/index.tsx
packages/main/src/webComponents/Button/demo.stories.tsx

As the events are not part of the typings you have to use ts-ignore in case you are using TypeScript.

feat(All Components): Allow all HTML events to be passed

---

packages/main/src/components/AnalyticalTable/AnayticalTable.jss.ts

z-index on Table Header caused issues when using table in an ObjectPage

fix(AnalyticalTable): remove z-index from Table Header

---

packages/main/src/components/AnalyticalTable/index.tsx

register useRowSelectionColumn before useDynamicColumnWidths hook

fix(AnalyticalTable): prevent overflow if rows are selectable

---

packages/main/src/components/AnalyticalTable/AnalyticalTable.test.tsx
packages/main/src/components/AnalyticalTable/__snapshots__/AnalyticalTable.test.tsx.snap
packages/main/src/components/AnalyticalTable/defaults/Column/Expandable.tsx
packages/main/src/components/AnalyticalTable/demo/demo.stories.tsx
packages/main/src/components/AnalyticalTable/demo/generateData.ts
packages/main/src/components/AnalyticalTable/hooks/useColumnsDependencies.ts
packages/main/src/components/AnalyticalTable/hooks/useDynamicColumnWidths.ts
packages/main/src/components/AnalyticalTable/hooks/useRowHighlight.tsx
packages/main/src/components/AnalyticalTable/hooks/useRowSelectionColumn.tsx
packages/main/src/components/AnalyticalTable/hooks/useTableCellStyling.ts
packages/main/src/components/AnalyticalTable/index.tsx

feat(AnalyticalTable): Add Highlight Column

---

packages/main/src/components/AnalyticalTable/AnayticalTable.jss.ts
packages/main/src/components/AnalyticalTable/__snapshots__/AnalyticalTable.test.tsx.snap
packages/main/src/components/AnalyticalTable/index.tsx
prettier.config.js

Prevents unnecessary rerenders

refactor(AnalyticalTable): declare row height via css variable

---

docs/Guidelines.md
packages/base/src/hooks/useDeprecateRenderMethods.ts
packages/base/src/lib/hooks.ts
packages/base/src/styling/HSLColor.ts
packages/charts/src/components/RadialChart/RadialChart.tsx
packages/charts/src/internal/withChartContainer.tsx
packages/charts/src/util/Utils.ts
packages/main/src/components/AnalyticalTable/AnalyticalTable.test.tsx
packages/main/src/components/AnalyticalTable/demo/demo.stories.tsx
packages/main/src/components/AnalyticalTable/demo/generateData.ts
packages/main/src/components/AnalyticalTable/hooks/useDynamicColumnWidths.ts
packages/main/src/components/AnalyticalTable/index.tsx
packages/main/src/components/Bar/Bar.test.tsx
packages/main/src/components/Bar/demo.stories.tsx
packages/main/src/components/Bar/index.tsx
packages/main/src/components/FilterBar/FilterBar.test.tsx
packages/main/src/components/FilterBar/demo.stories.tsx
packages/main/src/components/FilterBar/index.tsx
packages/main/src/components/FilterItem/index.tsx
packages/main/src/components/MessageBox/MessageBox.test.tsx
packages/main/src/components/ObjectPage/ObjectPage.test.tsx
packages/main/src/components/ObjectPage/ObjectPageHeader.tsx
packages/main/src/components/ObjectPage/demo.stories.tsx
packages/main/src/components/ObjectPage/index.tsx
packages/main/src/components/Page/demo.stories.tsx
packages/main/src/components/Page/index.tsx
packages/main/src/components/VariantManagement/VariantManagement.test.tsx
packages/main/src/internal/WithWebComponent.test.tsx

- introduce `useDeprecateRenderMethods` hook

refactor(render-methods): deprecate renderXYZ methods 

---

packages/charts/src/components/BarChart/BarChart.tsx
packages/charts/src/components/ColumnChart/ColumnChart.tsx
packages/charts/src/components/ComposedChart/index.tsx
packages/charts/src/components/LineChart/LineChart.tsx
packages/charts/src/components/MicroBarChart/MicroBarChart.tsx
packages/charts/src/components/PieChart/PieChart.tsx
packages/charts/src/components/RadarChart/RadarChart.tsx
packages/charts/src/internal/MeasureAxisProps.ts
packages/charts/src/internal/staticProps.ts

fix(Charts New): tooltip supports dark theme

---

packages/main/src/components/AnalyticalTable/ColumnHeader/index.tsx
packages/main/src/components/AnalyticalTable/__snapshots__/AnalyticalTable.test.tsx.snap
packages/main/src/components/AnalyticalTable/hooks/useRTL.ts
packages/main/src/components/AnalyticalTable/hooks/useTableCellStyling.ts
packages/main/src/components/AnalyticalTable/hooks/useTableHeaderStyling.ts
packages/main/src/components/AnalyticalTable/index.tsx
packages/main/src/components/AnalyticalTable/virtualization/VirtualTableBody.tsx

fix(AnalyticalTable): support RTL

---

packages/charts/src/components/BarChart/BarChart.tsx
packages/charts/src/components/ColumnChart/ColumnChart.tsx
packages/charts/src/components/ComposedChart/index.tsx
packages/charts/src/components/LineChart/LineChart.tsx
packages/charts/src/components/MicroBarChart/MicroBarChart.tsx
packages/charts/src/components/PieChart/PieChart.tsx
packages/charts/src/components/RadarChart/RadarChart.tsx
packages/charts/src/hooks/useChartMargin.ts
packages/charts/src/hooks/useLongestYAxisLabel.ts
packages/charts/src/hooks/useObserveXAxisHeights.ts
packages/charts/src/internal/SecondaryDimensionXAxisTick.tsx
packages/charts/src/internal/XAxisTicks.tsx
packages/charts/src/internal/YAxisTicks.tsx
packages/charts/src/internal/defaults.ts
packages/charts/src/internal/staticProps.ts
tsconfig.json

- Legend Position is always bottom, modifiable via `chartConfig.legendPosition`
- Legend Horizontal Align is always Start (Center for Polar Charts), modifiable with `chartConfig.legendHorizontalAlign`
- Calculation of longest y-axis-label, limited to 200px
- adjust legend position based on needed axis size

fix(Charts - New): layouting fixes

---

packages/main/src/components/Text/index.tsx
packages/main/src/interfaces/ThemeOptions.ts

docs(Text): Remove unused prop theme

---

packages/main/src/components/AnalyticalTable/AnayticalTable.jss.ts

fix(AnalyticalTable): use 100% of the parent height

---

packages/main/src/components/AnalyticalTable/hooks/useTableScrollHandles.ts

fix(AnalyticalTable): don't crash if scrollTo methods are not defined

---

packages/main/src/enums/AnalyticalTableScrollMode.ts

fix(AnalyticalTable): remove deprecated AnalyticalTableScrollMode smart

---

packages/main/src/webComponents/Toast/Toast.mdx
packages/main/src/webComponents/Toast/Toast.stories.tsx

docs(Toast): explain how a toast can be shown

---

packages/main/src/components/AnalyticalTable/AnayticalTable.jss.ts
packages/main/src/components/AnalyticalTable/ColumnHeader/index.tsx
packages/main/src/components/AnalyticalTable/__snapshots__/AnalyticalTable.test.tsx.snap
packages/main/src/components/AnalyticalTable/index.tsx

fix(AnalyticalTable): remove padding and scrollbar from select-all header cell

---

packages/main/src/components/AnalyticalTable/AnalyticalTable.mdx

docs(AnalyticalTable): add recipe on how to show less columns of smaller screens

---

packages/main/src/components/AnalyticalTable/__snapshots__/AnalyticalTable.test.tsx.snap
packages/main/src/components/AnalyticalTable/hooks/useDynamicColumnWidths.ts
packages/main/src/components/AnalyticalTable/index.tsx

- The vertical overflow happened, when the table was wrapped in an `absolute` positioned container and the `extension` prop was set.

fix(AnalyticalTable): fix dynamic column width + prevent table from overflowing in some cases

---

packages/base/src/hooks/usePassThroughHtmlProps.ts

Remove `useMemo` here as it had no effect because the returned object is always spreaded.

fix: remove useMemo from usePassThroughHtmlProps

---

packages/main/src/components/AnalyticalTable/hooks/useSingleRowStateSelection.ts
packages/main/src/components/AnalyticalTable/index.tsx
packages/main/src/components/AnalyticalTable/tableReducer/stateReducer.ts

fix(AnalyticalTable): fix subRows selection in tree table mode

---

packages/charts/src/components/BarChart/BarChart.tsx
packages/charts/src/components/ColumnChart/ColumnChart.tsx
packages/charts/src/components/ComposedChart/index.tsx
packages/charts/src/components/LineChart/LineChart.tsx
packages/charts/src/components/PieChart/PieChart.tsx
packages/charts/src/components/RadarChart/RadarChart.tsx
packages/charts/src/hooks/useLabelFormatter.ts

The dimension formatter was only applied to the Tooltip when the dimension accessor was `name`, this was due to a side effect of the `formatter` function of the `Tooltip` component. 

fix(Charts): tooltip respects dimension formatter

---

packages/main/src/components/AnalyticalTable/index.tsx

fix(AnalyticalTable): prevent crash if unsupported rowId is set as selectedRowId

---

packages/main/package.json
packages/main/src/components/AnalyticalTable/index.tsx
yarn.lock

Update to 7.3.2 which includes:
- feat: Add reset column resizing
- fix: bug in subRows sortData
- fix: enforce `useColumnOrder` before `useGroupBy`

fix(AnalyticalTable): update react-table

---

packages/main/src/components/AnalyticalTable/AnalyticalTable.stories.mdx
packages/main/src/components/AnalyticalTable/AnalyticalTable.test.tsx
packages/main/src/components/AnalyticalTable/index.tsx

BREAKING CHANGE: remove  prop `busyIndicatorEnabled` as it is somehow duplicate to `loading`. The visibility of the busy indicator is now solely controlled by the prop `loading`.

chore(AnalyticalTable): remove busyIndicatorEnabled prop

---

packages/main/src/components/FilterBar/index.tsx

fix(FilterBar): after opening the filters-dialog, enable manual control of filters again

---

packages/main/src/components/FilterBar/FilterDialog.tsx
packages/main/src/components/FilterBar/index.tsx
packages/main/src/components/FilterGroupItem/index.tsx

fix(FilterBar): add event properties to onFiltersDialogSave + fix manually controlled visibleInFilterBar prop

---

package.json
packages/main/src/components/AnalyticalTable/index.tsx
packages/main/src/components/AnalyticalTable/tableReducer/stateReducer.ts
yarn.lock

fix(AnalyticalTable): only apply selectedRowIds prop if its value has changed

---

docs/2-MigrationGuide.stories.mdx

docs: add migration guide for 0.10.0 to 0.11.0

---

packages/main/src/webComponents/Badge/Badge.stories.mdx

docs(Badge): enhance story

---

packages/main/src/components/AnalyticalTable/AnalyticalTable.test.tsx
packages/main/src/components/AnalyticalTable/ColumnHeader/ColumnHeaderModal.tsx
packages/main/src/components/AnalyticalTable/ColumnHeader/index.tsx

fix(AnalyticalTable): mount filters popover only when it's opened

---

packages/main/src/components/Form/Form.test.tsx
packages/main/src/components/Form/__snapshots__/Form.test.tsx.snap

rewrite form test

---

packages/main/src/components/Grid/Grid.test.tsx
packages/main/src/components/Grid/__snapshots__/Grid.test.tsx.snap

rewrite grid test

---

packages/base/src/hooks/useI18nBundle.ts

This fixes the `Can't perform a React state update on an unmounted component.` warning of some components. (E.g.: VariantManagement, Toolbar)

fix(useI18nBundle): prevent state transition if the component has been unmounted

---

docs/2-MigrationGuide.stories.mdx

docs: update migration guide

---

packages/main/src/components/Form/Form.stories.mdx
packages/main/src/components/Form/index.tsx
packages/main/src/components/FormGroup/index.tsx
packages/main/src/components/FormItem/index.tsx

docs(Form): add JSDoc comments

---

packages/charts/src/internal/ChartContainer.tsx

fix(Charts): use ErrorBoundary to prevent errors when components are re-mounted

---

packages/main/src/components/AnalyticalTable/defaults/Column/Expandable.tsx
packages/main/src/components/MessageBox/__snapshots__/MessageBox.test.tsx.snap
packages/main/src/components/Page/__snapshots__/Page.test.tsx.snap
packages/main/src/internal/__snapshots__/withWebComponent.test.tsx.snap
packages/main/src/internal/withWebComponent.tsx
packages/main/src/webComponents/Bar/__snapshots__/Bar.test.tsx.snap
packages/main/src/webComponents/NotificationListItem/__snapshots__/NotificationListItem.test.tsx.snap
packages/main/src/webComponents/SideNavigation/__snapshots__/SideNavigation.test.tsx.snap

Previously handling slots in our Web Components required some attention from the developer, e.g.:
- accept and handle the `slot` prop when using a Custom Component as Slot
- Only top level fragments were supported
This PR is now wrapping all slots with a div with `style:"display: contents;"` in order to allow any element as slot value.
As IE11 does not support the display: contents style this feature is not available there and you can't use nested fragments and have to make sure you are handling the slot prop correctly when using Custom Components.

feat(Web Components): allow nested fragments in slots (not available for IE11)

---

docs/2-MigrationGuide.stories.mdx
packages/base/src/hooks/useI18nBundle.ts
packages/base/src/lib/hooks.ts

BREAKING CHANGE: `useI18nText` is replaced by `useI18nBundle`. For more details please consult our [migration guide](https://sap.github.io/ui5-webcomponents-react/?path=/docs/migration-guide--page#deleted-hooks).

chore: delete deprecated useI18nText hook

---

packages/main/src/components/AnalyticalTable/AnalyticalTable.stories.mdx
packages/main/src/components/AnalyticalTable/AnalyticalTable.test.tsx
packages/main/src/components/AnalyticalTable/__snapshots__/AnalyticalTable.test.tsx.snap
packages/main/src/components/AnalyticalTable/index.tsx

The `visibleRowCountMode="Auto"` now supports elements rendered above the table in the same container.
E.g.
```jsx
<div style={{ height: '600px' }}>
<div style={{ height: '100px', width: '100%' }} />
<AnalyticalTable data={data} columns={columns} visibleRowCountMode={TableVisibleRowCountMode.AUTO} />
</div>
```
This implementation will no longer lead to a vertical overflow of the outer container.

feat(AnalyticalTable): add offset-top support to visibleRowCountMode "Auto"

---

packages/main/src/components/AnalyticalTable/TableBody/VirtualTableBodyContainer.tsx
packages/main/src/components/AnalyticalTable/index.tsx

- Add `totalRowCount` property to `onLoadMore` event (`e.detail.totalRowCount`) that returns the total number of rows, which includes expanded rows in, for example, a tree table.
- Fix `rowCount` property of the `onLoadMore` event (`e.detail.rowCount`) to only show the number of root rows. Therefore, it does not return the number of expanded rows.

fix(AnalyticalTable): add totalRowCount to event.detail param of onLoadMore event, fix rowCount number for expandable rows

---

packages/main/src/components/MessageBox/MessageBox.jss.ts
packages/main/src/components/MessageBox/__snapshots__/MessageBox.test.tsx.snap
packages/main/src/components/MessageBox/index.tsx

Use `h2` instead of `h5` for the Message Box Title and update the icons to match the latest specs:
Closes #1453

fix(MessageBox): a11y - use correct title level

---

packages/base/.gitignore
packages/base/package.json
packages/charts/.gitignore
packages/charts/package.json
packages/main/.gitignore
packages/main/package.json
scripts/rollup/configFactory.js

BREAKING CHANGE: `@ui5/webcomponents-react`, `@ui5/webcomponents-react-base` and `@ui5/webcomponents-react-charts` are no longer publishing the `lib` folder. Please use `dist` instead. More details can be found in our [MigrationGuide](https://sap.github.io/ui5-webcomponents-react/?path=/docs/migration-guide--page#replaced-lib-folder-with-dist-folder).

chore: don't publish lib folder anymore

---

packages/main/src/components/Breadcrumbs/__snapshots__/Breadcrumbs.test.tsx.snap
packages/main/src/components/Breadcrumbs/index.tsx
packages/main/src/components/DynamicPage/__snapshots__/DynamicPage.test.tsx.snap
packages/main/src/components/ObjectPage/__snapshots__/ObjectPage.test.tsx.snap

- Add missing aria labels
- Use unordered list to display items
- Only focus first or previously focused item with tab
- Allow right and left navigation between breadcrumbs with arrow keys

fix(Breadcrumbs): add missing aria labels & allow navigation with arrow keys

---

packages/charts/src/components/ComposedChart/index.tsx
packages/charts/src/dist/ComposedChartPlaceholder.ts
packages/charts/src/dist/components/ComposedChartPlaceholder.ts
packages/charts/src/index.ts

BREAKING CHANGE: `ComposedChartPlaceholder`: The import path has changed. You can now import the placeholder from `@ui5/webcomponents-react-charts/dist/ComposedChartPlaceholder` or directly from `@ui5/webcomponents-react-charts`.

fix(charts): Export `ComposedChart` and `ComposedChartPlaceholder` in root export as well

---

packages/main/src/components/Form/Form.stories.mdx
packages/main/src/components/Form/index.tsx

Negative values set for the `labelSpan` crashed the storybook demo, that's why it's now restricted to only accept number in defined range.

docs(Form): add min & max option to labelSpans & columns

---

packages/main/src/components/MessageBox/__snapshots__/MessageBox.test.tsx.snap
packages/main/src/components/MessageBox/index.tsx

The initial focus when opening a `MessageBox` is now the first focusable element. This can be changed with the `initialFocus` property or by calling `focus()` on the corresponding element within the `onBeforeOpen` or `onAfterOpen` callback.

feat(MessageBox): add `initialFocus`, `onBeforeOpen`, `onAfterOpen` props

---

packages/main/src/components/FilterBar/FilterBar.jss.ts
packages/main/src/components/FilterBar/FilterBar.stories.mdx
packages/main/src/components/FilterBar/__snapshots__/FilterBar.test.tsx.snap
packages/main/src/components/FilterBar/index.tsx
packages/main/src/components/FilterGroupItem/FilterGroupItem.jss.ts
packages/main/src/components/FilterGroupItem/index.tsx
packages/main/src/i18n/messagebundle.properties
yarn.lock

When Toolbar is not displayed:
- fixes padding for FilterBar action buttons 
- replaces "Filters" button label with "Adapt Filters" 
- remove padding and boxShadow around filter section
- spread filters to available width
- align FilterBar action buttons with filter items

feat(FilterBar): FilterBar without Toolbar spreads filters to available width

---

packages/main/src/components/MessageBox/__snapshots__/MessageBox.test.tsx.snap
packages/main/src/components/MessageBox/index.tsx

This PR also changes the "Close" button design of the error type dialog to transparent.
The default `emphasizedAction` is `MessageBoxActions.OK`.

feat(MessageBox): add `emphasizedAction` prop

---

.github/workflows/stale.yml

We're now watching only issues with the label `author action`, mark them as stale after 14 days and close them after another 7 days.

chore: update stale bot

---

packages/charts/src/components/DonutChart/DonutChart.stories.mdx
packages/charts/src/components/PieChart/PieChart.stories.mdx
packages/charts/src/components/PieChart/PieChart.tsx
packages/charts/src/resources/DemoProps.ts

Enables passing a callback to `hideDataLabel` of the `PieChart` and `DonutChart` .
With this it is now possible to e.g. hide data labels depending on the percentage of space allocated to the individual segments.
```
hideDataLabel: (chartConfig) => {
if (chartConfig.percent < 0.01) {
return true;
}
}
```

feat(PieChart & DonutChart): add callback to `hideDataLabel` measure prop

---

packages/main/src/components/ActionSheet/ActionSheet.jss.ts
packages/main/src/components/ActionSheet/index.tsx

The `ActionSheet` had an unexpected margin on its bottom when less than 3 actions were contained on a phone.
Fixes #1748

fix(ActionSheet):  consistent button padding and placement on phones

---

packages/charts/src/components/BarChart/BarChart.tsx
packages/charts/src/components/ColumnChart/ColumnChart.tsx
packages/charts/src/components/ComposedChart/index.tsx
packages/charts/src/components/LineChart/LineChart.tsx
packages/charts/src/components/MicroBarChart/MicroBarChart.tsx
packages/charts/src/components/PieChart/PieChart.tsx
packages/charts/src/components/RadarChart/RadarChart.tsx
packages/charts/src/components/ScatterChart/ScatterChart.tsx
packages/charts/src/interfaces/IChartBaseProps.ts

This PR adds the possibility to control the position, behavior and appearance of the tooltip popover that is shown when hovering over data points.

feat(charts): add `tooltipConfig` prop to allow control of Tooltip

---

packages/main/src/internal/useResponsiveContentPadding.ts

fix(useResponsiveContentPadding): don't crash in Safari

---

packages/main/src/components/Form/index.tsx

fix(Form): don't crash when range detection returns null

---

packages/base/src/hooks/useIsRTL.ts
packages/main/src/components/DynamicPageTitle/index.tsx
packages/main/src/internal/useResponsiveContentPadding.ts

fix(DynamicPage): fix memory leaks when unmounted during resize

---

packages/main/src/components/DynamicPage/__snapshots__/DynamicPage.test.tsx.snap
packages/main/src/components/FilterBar/__snapshots__/FilterBar.test.tsx.snap
packages/main/src/components/ObjectPage/__snapshots__/ObjectPage.test.tsx.snap
packages/main/src/components/Toolbar/Toolbar.jss.ts
packages/main/src/components/Toolbar/__snapshots__/Toolbar.test.tsx.snap
packages/main/src/components/Toolbar/index.tsx

Also fixes/adds: 
- border not adding height to the component, previously height was `sapWcrToolbarHeight + 0.0625rem`
- add data attributes to simplify querying elements for css selection
Fixes: #1843

fix(Toolbar): always align items in the center

---

packages/main/src/components/DynamicPageAnchorBar/index.tsx
packages/main/src/components/DynamicPageTitle/DynamicPageTitle.jss.ts
packages/main/src/components/DynamicPageTitle/index.tsx

- navigation actions are now moved to top if `headerTitle` width is smaller than 1280
- use `Toolbar` instead of `FlexBox` to wrap nav actions, so an overflow button is displayed when overflowing
- add missing pushpin icon import
Fixes: #1841

fix(DynamicPageTitle): correct responsive positioning of nav and global actions

---

packages/base/codemods/renamePropsV18.js
packages/main/src/components/ObjectPage/ObjectPage.stories.mdx
packages/main/src/components/ObjectPage/ObjectPage.test.tsx
packages/main/src/components/ObjectPage/ObjectPageAnchorButton.tsx
packages/main/src/components/ObjectPage/index.tsx
packages/main/src/components/ObjectPageSection/ObjectPageSection.test.tsx
packages/main/src/components/ObjectPageSection/index.tsx
packages/main/src/components/ObjectPageSubSection/ObjectPageSubSection.test.tsx
packages/main/src/components/ObjectPageSubSection/index.tsx

BREAKING CHANGE: **ObjectPageSection**: `heading` has been renamed to `titleText` and `headingUppercase` to `titleTextUppercase`
BREAKING CHANGE: **ObjectPageSubSection**: `heading` has been renamed to `titleText`

refactor(ObjectPage): rename `heading` to `titleText`

---

packages/base/codemods/renamePropsV18.js
packages/main/src/components/AnalyticalCard/AnalyticalCard.stories.mdx
packages/main/src/components/DynamicPage/DynamicPage.stories.mdx
packages/main/src/components/DynamicPage/DynamicPage.test.tsx
packages/main/src/components/DynamicPage/__snapshots__/DynamicPage.test.tsx.snap
packages/main/src/components/DynamicPageTitle/index.tsx
packages/main/src/components/ObjectPage/ObjectPage.stories.mdx
packages/main/src/components/ObjectPage/__snapshots__/ObjectPage.test.tsx.snap
packages/main/src/components/ObjectPage/index.tsx
packages/main/src/components/ObjectPageSection/__snapshots__/ObjectPageSection.test.tsx.snap
packages/main/src/components/ObjectPageSection/index.tsx
packages/main/src/components/ObjectPageSubSection/__snapshots__/ObjectPageSubSection.test.tsx.snap
packages/main/src/components/ObjectPageSubSection/index.tsx

BREAKING CHANGE: `heading` has been renamed to `header`,  `subheading` to `subHeader` and `showSubheadingRight` to `showSubHeaderRight`
Closes #1600

refactor(DynamicPageTitle): rename props

---

packages/main/src/components/AnalyticalTable/hooks/useRowSelectionColumn.tsx
packages/main/src/components/AnalyticalTable/hooks/useSingleRowStateSelection.ts
packages/main/src/components/AnalyticalTable/index.tsx

- Fixes selection of rows in `MULTI_SELECT` mode and with `ROW_SELECTOR` only behavior.
- In `SINGLE_SELECT` mode, it is now possible to unselect a selected row by clicking on it (or the respective row-selector)
Fixes #1907

fix(AnalyticalTable): unselect rows in single-select mode & correctly select rows with row-selector only behavior

---

packages/charts/src/components/BarChart/BarChart.stories.mdx
packages/charts/src/components/BulletChart/BulletChart.stories.mdx
packages/charts/src/components/ColumnChart/ColumnChart.stories.mdx
packages/charts/src/components/ColumnChartWithTrend/ColumnChartWithTrend.stories.mdx
packages/charts/src/components/ComposedChart/ComposedChart.stories.mdx
packages/charts/src/components/DonutChart/DonutChart.stories.mdx
packages/charts/src/components/MicroBarChart/MicroBarChart.stories.mdx

This prevents the deprecation warning:
```
browser.js:39 Importing from '@storybook/addon-docs/blocks' is deprecated, import directly from '@storybook/addon-docs' instead:
https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-scoped-blocks-imports
```

chore(charts):remove unused or deprecated imports from stories

---

packages/main/src/components/ObjectPage/index.tsx

Fixes:
- event not firing when scrolling or programatically changing sections
- programatically changing sections now scrolls to respective section
Fixes #1952

fix(ObjectPage): fire `onSelectedSectionChange` on every section change

---

packages/base/types/Theme.d.ts

Hey, following what I've seen in #1057 and #1136, I believe we could follow the same approach we did for  `UI5Devices.d.ts` and create a type definition for the base Theming config. 
I'm using these types in my project (internally at SAP).
I created the themes as an interface only so the user can use https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation to add a new theme in their project without disrupting the already established themes, like so:
```ts
declare module "@ui5/webcomponents-base/dist/config/Theme" {
export interface ThemeKeys {
my_new_theme: never;
}
}
```
The only issue is with the themes themselves, since that when a new theme is created this file here will have to be updated.

chore(base): create type definitions for theme configuration

---

packages/main/src/components/FilterBar/index.tsx

Enforces that children receive an update on each dialog save, otherwise refs won't be updated.
Fixes #2008

fix(FilterBar): update filter item refs on every dialog save

---

packages/base/src/hooks/usePassThroughHtmlProps.ts
packages/main/src/components/ActionSheet/ActionSheet.stories.mdx
packages/main/src/components/ActionSheet/__snapshots__/ActionSheet.test.tsx.snap
packages/main/src/components/ActionSheet/index.tsx
packages/main/src/components/DynamicPage/DynamicPage.stories.mdx
packages/main/src/components/DynamicPage/index.tsx
packages/main/src/components/DynamicPageAnchorBar/index.tsx
packages/main/src/components/ObjectPage/ObjectPage.stories.mdx
packages/main/src/components/ObjectPage/index.tsx

This PR adds the `a11yConfig` prop to the `ObjectPage`, `DynamicPage` and `ActionSheet` component.
Closes: #2031

feat: add `a11yConfig` prop to customize a11y properties

---

packages/main/src/components/AnalyticalTable/defaults/FilterComponent/index.tsx

`undefined` as `Input` `value` shows undefined as string instead of clearing the input, that's why we need to set it to an empty string manually. (See https://github.com/SAP/ui5-webcomponents/issues/2616)
Fixes #2073

fix(AnalyticalTable): remove filter without showing `undefined`

---

packages/main/src/internal/withWebComponent.tsx

This PR adds a workaround to the React wrapper to fix the double triggering `onClick` event. (See https://github.com/SAP/ui5-webcomponents/issues/3786)

fix(CardHeader): fire `onClick` only once

---

packages/main/src/components/ObjectPage/index.tsx

This PR introduces a timeout to the scroll behavior of 500ms after the user manually expanded/collapsed the header by either clicking on the corresponding button or on the DynamicPageTitle.
Fixes #2119

fix(ObjectPage): consistently toggle header after scrolling 

---

packages/main/src/components/DynamicPageTitle/DynamicPageTitle.jss.ts

This PR adds text wrapping to the `header` and `subHeader` of the `DynamicPageTitle`. This prevents the `actions` from moving outside of the container.
Fixes #2160

fix(DynamicPageTitle): wrap `header` and `subHeader` if not enough space is available

---

packages/main/src/components/MessageBox/MessageBox.jss.ts
packages/main/src/components/MessageBox/__snapshots__/MessageBox.test.tsx.snap
packages/main/src/components/MessageBox/index.tsx

This PR adds a spacer between the icon and the header title to support RTL.

fix(MessageBox): correct spacing of header items in rtl mode

---

packages/main/src/components/ActionSheet/index.tsx
packages/main/src/components/AnalyticalTable/ColumnHeader/ColumnHeaderContainer.tsx
packages/main/src/components/AnalyticalTable/ColumnHeader/ColumnHeaderModal.tsx
packages/main/src/components/AnalyticalTable/ColumnHeader/index.tsx
packages/main/src/components/AnalyticalTable/VerticalResizer.tsx
packages/main/src/components/AnalyticalTable/index.tsx
packages/main/src/components/FilterBar/FilterDialog.tsx
packages/main/src/components/FilterBar/index.tsx
packages/main/src/components/ObjectPage/index.tsx
packages/main/src/components/Toolbar/OverflowPopover.tsx
packages/main/src/components/Toolbar/index.tsx
packages/main/src/components/VariantManagement/ManageViewsDialog.tsx
packages/main/src/components/VariantManagement/index.tsx

This PR adds the `portalContainer` prop to components wich are using `React.createPortal` to render modals or other elements outside of the DOM hierarchy. With `portalContainer` it is possible to change the element the modal is rendered into.

feat: add `portalContainer` prop for elements rendered via `createPortal`

---

packages/main/src/components/DynamicPage/index.tsx

In some cases the observed element of the IntersectionObserver was not 100% intersecting (~0.99xxx), to prevent this the threshold was adjusted to `0.98`. Also the intersection observer is now debounced.
Fixes #2200

fix(DynamicPage): correctly display footer in FCL

---

packages/main/src/components/DynamicPageTitle/index.tsx
packages/main/src/components/Toolbar/index.tsx

This PR adds the `onToolbarOverflowChange` callback to the `DynamicPageTitle` component. The callback is fired when the content  of one of the toolbars overflow popover changes. All properties of `onOverflowChange` are inherited and `origin`, which can be used to easily identify which toolbar has fired the corresponding event, is added.
Additionally the `target` property has been incorporated in the `onOverflowChange` event of the `Toolbar`.
Closes #2375

feat(DynamicPageTitle): add `onToolbarOverflowChange` callback/prop

---

packages/main/src/components/MessageView/MessageItem.tsx

This PR changes the type of `titleText` and `subtitleText` to `ReactNode`, because in some cases users may need to pass a component e.g. a `Link` to the respective prop.

refactor(MessageItem): allow `ReactNode` to be passed as `titleText` and `subtitleText`

---

packages/cra-template-seed/template/src/index.js
packages/cra-template/template/src/index.js
packages/main/src/components/VariantManagement/ManageViewsDialog.tsx

Not using fully specified paths might cause issues in e.g. rollup builds.

fix: use fully specified paths for all web component imports

---

packages/main/src/components/MessageBox/MessageBox.stories.mdx
packages/main/src/components/MessageBox/MessageBox.test.tsx
packages/main/src/components/MessageBox/__snapshots__/MessageBox.test.tsx.snap
packages/main/src/components/MessageBox/index.tsx

This PR enhances the MessageBox by allowing `Button` components to be passed to the "actions" array. 
Closes #2424

feat(MessageBox): allow passing `Button`s as actions

---

packages/charts/src/components/RadialChart/RadialChart.stories.mdx
packages/charts/src/components/RadialChart/RadialChart.tsx
packages/charts/src/components/RadialChart/__snapshots__/RadialChart.test.tsx.snap
packages/charts/src/internal/ChartContainer.tsx

We should make the `RadialBarChart` customizable by users.
Before we merge this PR we should discuss:

feat(RadialChart): introduce `chartConfig` & `displayValueStyle` prop, adjust default margin of internal chart

---

packages/main/src/components/SelectDialog/SelectDialog.stories.mdx
packages/main/src/components/SelectDialog/SelectDialog.test.tsx
packages/main/src/components/SelectDialog/index.tsx

This PR adds the `numberOfSelectedItems` prop to support programatically setting the counter in `MultiSelection` mode in combination with searching. It also fixes an issue concerning programatically selected items not being recognized by the component.
Fixes #2492

feat(SelectDialog): add `numberOfSelectedItems` prop to support `MultiSelect` mode

---

packages/main/src/components/ActionSheet/__snapshots__/ActionSheet.test.tsx.snap
packages/main/src/components/ActionSheet/index.tsx

This PR removes the `role` (already set internally on the web component) and `aria-modal` (wrong for popover as it doesn't prevent the user from interacting with other content) prop from the `ResponsivePopover.

fix(ActionSheet): only announce aria role once

---

packages/main/src/components/ActionSheet/__snapshots__/ActionSheet.test.tsx.snap
packages/main/src/components/ActionSheet/index.tsx

This PR changes the role of the actions container to `application`, preventing screen readers like JAWS from intercepting the standard input events like `key-down` or `focus`.
Fixes #2646

fix(ActionSheet): allow key navigation between action buttons with screen readers

---

packages/main/src/components/Toolbar/__snapshots__/Toolbar.test.tsx.snap
packages/main/src/components/Toolbar/index.tsx

This is the easier and shorter way I found to fix the bug explained [here](https://github.com/SAP/ui5-webcomponents-react/issues/2032).
```diff
- style: { visibility: 'hidden' }
+ style: { visibility: 'hidden', position: 'absolute', pointerEvents: 'none' }
```
The elements inside the toolbar can be hidden based on the size of the window, when they're hidden the CSS property `visibility` is set to `hidden` - But even if they are NOT visible though, they still occupy space, and this is the cause of the bug.
In my solution, other than `visibility: hidden` I also set `position: absolute`, this way we can be sure that the hidden elements don't occupy space, `pointer-events: none` ensures that they will not be clickable in any case.
Instead of `visibility: hidden` I tried using `display: none`, …

fix(Toolbar): spacings between elements

---

packages/main/src/internal/withWebComponent.tsx

In some test scenarios the `ref` is initially not defined, which resulted in an error. This PR adds optional chaining to prevent this.

fix(withWebcomponent): add optional chaining for event listener registration

---

packages/main/src/components/DynamicPage/index.tsx

This PR fixes an error in React Strict Mode. It was thrown while hovering the toggle button of the anchor bar when no `DynamicPageTitle` was set.

fix(DynamicPage): prevent error in React Strict Mode

---

packages/main/src/components/AnalyticalTable/__snapshots__/AnalyticalTable.test.tsx.snap
packages/main/src/components/AnalyticalTable/index.tsx
packages/main/src/components/AnalyticalTable/scrollbars/VerticalScrollbar.tsx

The scrollbar container wasn't updated when the body changed its height on runtime, leading to an unnecessary overflow. Also if `TableVisibleRowCountMode.Auto` is used, the table now always shows at least one row.

fix(AnalyticalTable): update table body height when changed on runtime

---

packages/main/src/components/DynamicPage/DynamicPage.test.tsx
packages/main/src/components/DynamicPage/__snapshots__/DynamicPage.test.tsx.snap
packages/main/src/components/DynamicPage/index.tsx

This PR adds the `dynamicPageFooter` entry to the `a11yConfig` prop, making it possible to change the role of the footer.
Closes #2421

feat(DynamicPage): make role of footer customizable

---

packages/base/src/hooks/useIsRTL.ts
packages/main/src/components/Toolbar/OverflowPopover.tsx
packages/main/src/components/Toolbar/Toolbar.jss.ts
packages/main/src/components/Toolbar/Toolbar.stories.mdx
packages/main/src/components/Toolbar/__snapshots__/Toolbar.test.tsx.snap
packages/main/src/components/Toolbar/index.tsx
packages/main/src/interfaces/Ui5DomRef.ts

This PR stretches the overflow popover of the Toolbar to the available screen width. It also improves the `useIsRtl` hook by allowing UI5DomRef elements to be passed to it.
Fixes #2735

fix(Toolbar): stretch overflow popover to available screen width on phones

---

packages/main/src/components/AnalyticalTable/index.tsx

This PR makes it possible to select all sub-rows when a row is selected and a custom `subRowsKey` is used.

fix(AnalyticalTable): support custom `subRowsKey` in combination with `selectSubRows`

---

packages/base/src/hooks/useResponsiveContentPadding.ts
packages/main/src/components/Form/index.tsx

This PR adds a fallback for the rare (and strange) case that the window range is initially not available. 
Fixes #2799

fix(Form): prevent crash if window range is initially not available

---

packages/main/src/components/Form/Form.jss.ts
packages/main/src/components/Form/Form.stories.mdx
packages/main/src/components/Form/index.tsx
packages/main/src/components/ObjectPage/ObjectPage.stories.mdx

In ui5-wc v1.3.0 `alignItems: "baseline"` on the form doesn;t behave the same anymore for input fields. This PR centers the labels per default and adds a comment on how the alignment can be changed by app developers.

fix(Form): correct alignment

---

packages/main/src/components/ObjectPage/ObjectPageAnchorButton.tsx
packages/main/src/components/ObjectPage/ObjectPageAnchorTab.ts
packages/main/src/components/ObjectPage/__snapshots__/ObjectPage.test.tsx.snap

Fixes the error with the custom `Tab` in v1.3.0 of `@ui5/webcomponents`.
Fixes #2826

fix(ObjectPage): don't crash on tab select after ui5-wc update

---

package.json
yarn.lock

`@types/react` and `browserslist` don't need to be resolved to a specific version anymore

chore(deps): remove outdated resolution dependencies

---

packages/main/src/components/AnalyticalTable/hooks/useDynamicColumnWidths.ts

This PR disables the logic within the internally used `useDynamicColumnWidths` hook when using a different `scaleWidthMode` than the ones specified in the `TableScaleWidthMode` enum.

chore(AnalyticalTable): don't execute column scale logic if undefined `scaleWidthMode` is used

---

packages/main/src/components/VariantManagement/ManageViewsDialog.tsx
packages/main/src/components/VariantManagement/MangeViewsTableRows.tsx
packages/main/src/components/VariantManagement/VariantManagement.test.tsx
packages/main/src/components/VariantManagement/index.tsx

Adds a hideCreatedBy property to the VariantManagement component in order to hide the 'Created By' column on the manage view dialog.
Fixes #2891

feat(VariantManagement): add hideCreatedBy property

---

packages/cra-template-seed/template/.prettierrc
packages/cra-template-seed/template/src/components/Form/Input/Input.js
packages/cra-template-seed/template/src/components/Form/TextArea/TextArea.js

This behaviour comes closer to the standard react [`onChange` handling](https://reactjs.org/docs/dom-elements.html#onchange).
Fixes #2911

fix(cra-template-seed): use `onInput` for react change events

---

packages/main/src/components/AnalyticalTable/TableBody/VirtualTableBodyContainer.tsx
packages/main/src/components/AnalyticalTable/index.tsx

This PR fixes the issue of expandable rows making the table scroll to top when collapsed. `scrollTop` is now only set to zero if in the updated `data` array there are less entries than before. Previously, this depended on the rows of the table, which changed each time a row was collapsed.

fix(AnalyticalTable): don't scroll to top when collapsing rows

---

packages/main/src/components/AnalyticalTable/ColumnHeader/index.tsx
packages/main/src/components/AnalyticalTable/__snapshots__/AnalyticalTable.test.tsx.snap

Components passed as `Header` in the columns configuration array are now not rendered inside a `Text` component. Also the icon container receives `data-component-name` to make it easier accessible by DOM selectors.

fix(AnalyticalTable): don't wrap Header elements inside `Text`

---

packages/main/src/components/AnalyticalTable/hooks/useDynamicColumnWidths.ts

fix(AnalyticalTable): don't reset column widths on data load if data already exists

---

packages/main/src/components/AnalyticalTable/ColumnHeader/ColumnHeaderModal.tsx

This PR prevents the table header popover's click event to bubble up to the th itself, preventing users from opening it again.

fix(AnalyticalTable): don't bubble up click event of th popover

---

docs/3-KnowledgeBase.stories.mdx
packages/main/src/components/AnalyticalTable/__snapshots__/AnalyticalTable.test.tsx.snap
packages/main/src/components/AnalyticalTable/index.tsx
packages/main/src/components/AnalyticalTable/scrollbars/VerticalScrollbar.tsx

To use the default browser styling of the scrollbar it is now possible to use `data-native-scrollbar` for the `AnalyticalTable` as well.

fix(AnalyticalTable): allow disabling custom scrollbar styles w/o using CSS

---

.storybook/mockData/FriendsManualSelect25.json
packages/main/src/components/AnalyticalTable/AnalyticalTable.stories.mdx
packages/main/src/components/AnalyticalTable/AnalyticalTable.test.tsx
packages/main/src/components/AnalyticalTable/pluginHooks/AnalyticalTableHooks.ts
packages/main/src/components/AnalyticalTable/pluginHooks/useManualRowSelect.ts

This PR adds the `useManualRowSelect` plugin hook. With it it's possible to change selected rows by setting a key in the data array.

feat(AnalyticalTable): add `useManualRowSelect` plugin hook

---

packages/main/src/components/DynamicPage/__snapshots__/DynamicPage.test.tsx.snap
packages/main/src/components/DynamicPage/index.tsx
packages/main/src/components/ObjectPage/__snapshots__/ObjectPage.test.tsx.snap
packages/main/src/components/ObjectPage/index.tsx

This currently only applies for themes from the Horizon family, as in other themes the font size stays the same in collapsed and expanded state.

fix(DynamicPageTitle): use "large" font size for title if no `headerContent` is set

---

packages/main/src/components/DynamicPage/DynamicPage.test.tsx
packages/main/src/components/DynamicPage/index.tsx

This PR adds `aria-label` and `aria-labelledby` to `a11yConfig.dynamicPageFooter`
Closes #3239

feat(DynamicPage): add more aria options to `a11yConfig`

---

packages/main/src/components/AnalyticalTable/AnalyticalTable.stories.mdx
packages/main/src/components/AnalyticalTable/index.tsx

This PR replaces react-table links to v7 and adds a note that the `groupable` prop is not supported when rendering a tree table or when subcomponents are used.
Closes #3247

docs(AnalyticalTable): update links & outline `groupable` support

---

packages/main/src/components/AnalyticalTable/TableBody/VirtualTableBody.tsx

Removed empty grouped rows when minRows exceeds number of data rows (Issue #3266 )
+ Especially the [How to Contribute](https://github.com/SAP/ui5-webcomponents-react/blob/main/CONTRIBUTING.md#contribute-code) section 
Fixes #3266

fix(AnalyticalTable):Remove empty grouped rows 

---

packages/main/src/components/AnalyticalTable/hooks/useDynamicColumnWidths.ts

`visibleColumns` is never updated in the `columns` hook, that's why we have to use `columns` here and check for visibility ourself.
Fixes #3295

fix(AnalyticalTable): allow adding columns in runtime

---

packages/main/src/components/DynamicPage/DynamicPage.stories.mdx
packages/main/src/components/DynamicPage/DynamicPage.test.tsx
packages/main/src/components/DynamicPageTitle/index.tsx
packages/main/src/components/ObjectPage/ObjectPage.stories.mdx

This PR deprecates the `actionsOverflowButton`, `navigationActionsOverflowButton` and `onToolbarOverflowChange` props. Depending on which toolbar should be configured, all props should be passed to either the `actionsToolbarProps` or `navigationActionsToolbarProps`.
Closes #3353

feat(DynamicPageTitle): allow a subset of `Toolbar` props to be passed to each toolbar

---

.storybook/components/TableOfContent.tsx
.storybook/preview-head.html
.storybook/preview.js
package.json

Known drawbacks compared to "native" mdx/md anchors:
- The anchor icon is now always visible for mdx anchors
- If duplicate heading texts are used (e.g. `Code`) only the first heading is selected when clicking on the toc. (Would imo be too much effort to implement this)
This workaround should be removed when sb v7 is ready for consumption or [this issue](https://github.com/storybookjs/storybook/issues/18395) is fixed in v6 as well.

docs(Storybook): implement workaround for anchors

---

packages/charts/src/components/BarChart/BarChart.tsx
packages/charts/src/components/BulletChart/BulletChart.tsx
packages/charts/src/components/ColumnChart/ColumnChart.tsx
packages/charts/src/components/ComposedChart/index.tsx
packages/charts/src/components/LineChart/LineChart.tsx
packages/charts/src/components/PieChart/PieChart.tsx
packages/charts/src/components/RadarChart/RadarChart.tsx
packages/charts/src/components/ScatterChart/ScatterChart.tsx

It is now possible again to hide tooltips by setting `tooltipConfig.active` to `false`.
Workaround for: https://github.com/recharts/recharts/issues/2703

fix(charts): allow hiding of tooltips 

---

packages/main/src/components/MessageBox/MessageBox.jss.ts
packages/main/src/components/MessageBox/__snapshots__/MessageBox.test.tsx.snap
packages/main/src/components/MessageBox/index.tsx
packages/main/src/enums/MessageBoxTypes.ts
packages/main/src/i18n/messagebundle.properties

BREAKING CHANGE: `MessageBoxTypes.Highlight` has been removed as it was not specified by the Fiori guidelines.
fixes #3480
fixes #3431
fixes #3375

fix(MessageBox): use Dialog `state` for better accessibility

---

packages/main/src/components/DynamicPage/index.tsx

The margin wasn't the root cause of the issue, so the "fix" just shifted the problem and did not solve it.

Revert "fix(DynamicPage): prevent footer from "jumping" in rare cases (#3486)"

---

packages/main/src/components/DynamicPage/__snapshots__/DynamicPage.test.tsx.snap
packages/main/src/components/Form/Form.jss.ts
packages/main/src/components/Form/Form.stories.mdx
packages/main/src/components/Form/__snapshots__/Form.test.tsx.snap
packages/main/src/components/Form/index.tsx
packages/main/src/components/FormGroup/index.tsx
packages/main/src/enums/FormBackgroundDesign.ts
packages/main/src/enums/index.ts

This PR also replaces all CSS properties with physical direction mapping with the corresponding logical one.

feat(Form): introduce `backgroundDesign` prop

---

docs/MigrationGuide.stories.mdx
packages/main/src/components/ActionSheet/index.tsx
packages/main/src/components/AnalyticalTable/AnalyticalTable.stories.mdx
packages/main/src/components/AnalyticalTable/index.tsx
packages/main/src/components/DynamicPage/__snapshots__/DynamicPage.test.tsx.snap
packages/main/src/components/DynamicPageTitle/DynamicPageTitle.jss.ts
packages/main/src/components/DynamicPageTitle/index.tsx
packages/main/src/components/ObjectPage/__snapshots__/ObjectPage.test.tsx.snap

BREAKING CHANGE: **ActionSheet**: The prop `alwaysShowHeader` has been removed.
BREAKING CHANGE: **ActionSheet**: The prop `a11yConfig.actionSheetMobileContent.ariaLabel` has been removed. Please use `accessibleName` instead.
BREAKING CHANGE: **AnalyticalTable**: The props `onRowSelected` and `onColumnsReordered` have been removed. Please use `onRowSelect` and `onColumnsReorder` instead.
BREAKING CHANGE: **DynamicPageTitle**: The props `actionsOverflowButton`, `navigationActionsOverflowButton` and `onToolbarOverflowChange` have been removed. Please use the `overflowButton` and `onOverflowChange` properties of the `actionsToolbarProps` and `navigationActionsToolbarProps` props instead. More details can be found in our [Migration Guide](https://sap.github.io/ui5-webcomponents-react/?path=/do …

chore: remove deprecated props

---

packages/main/src/components/AnalyticalTable/AnalyticalTable.stories.mdx
packages/main/src/components/AnalyticalTable/index.tsx

`autoResetResize` is available even though it's not mentioned in the react-table docs.

docs(AnalyticalTable): Remove typo, add info about `autoResetResize`

---

packages/charts/src/components/BarChart/BarChart.tsx
packages/charts/src/components/BulletChart/BulletChart.tsx
packages/charts/src/components/ColumnChart/ColumnChart.tsx
packages/charts/src/components/ColumnChartWithTrend/ColumnChartWithTrend.tsx
packages/charts/src/components/ComposedChart/index.tsx
packages/charts/src/components/DonutChart/DonutChart.tsx
packages/charts/src/components/LineChart/LineChart.tsx
packages/charts/src/components/MicroBarChart/MicroBarChart.tsx
packages/charts/src/components/PieChart/PieChart.tsx
packages/charts/src/components/RadarChart/RadarChart.tsx
packages/charts/src/components/RadialChart/RadialChart.tsx
packages/charts/src/components/ScatterChart/ScatterChart.tsx
packages/charts/src/internal/ChartContainer.tsx
packages/charts/src/internal/ChartDataLabel.tsx
packages/charts/src/internal/XAxisTicks.tsx
packages/charts/src/internal/YAxisTicks.tsx
packages/main/src/components/SelectDialog/index.tsx
packages/main/src/interfaces/CommonProps.ts
packages/main/src/internal/withWebComponent.tsx

The `ref` prop will automatically be added by the `forwardRef` function, there is no need to specify this manually. This also leads to way simpler types and looses the coupling to specific `@types/react` versions.

fix(typescript): don't include `ref` in all component props

---

packages/main/src/components/AnalyticalTable/index.tsx

In the docs of AnalyticalTable, there was a mention of a "visibleRowCount" prop, which doesn't exist. Change that reference to "visibleRows", which is a prop that exists.

docs: Fix copy/paste mistake in docs

---

packages/base/src/hooks/useResponsiveContentPadding.ts
packages/main/src/components/ObjectPage/ObjectPage.jss.ts
packages/main/src/components/ObjectPage/__snapshots__/ObjectPage.test.tsx.snap
packages/main/src/components/ObjectPage/index.tsx

The responsive padding of the `TabContainer` does not include the scrollbar, whereas the header and content section of the ObjectPage do. This resulted in discrepancy of the padding. This PR applies the same padding used for the rest of the ObjectPage to the TabContainer as well.
Fixes #3551

fix(ObjectPage): adjust responsive padding of tab-bar to header padding

---

packages/main/src/components/FilterBar/FilterBar.cy.tsx
packages/main/src/components/FilterBar/FilterDialog.tsx
packages/main/src/components/FilterGroupItem/index.tsx

fix(FilterBar): fix alignment of table cells in dialog

---

packages/main/src/components/FlexBox/FlexBox.jss.ts
packages/main/src/components/FlexBox/index.tsx

and refactor styling to use `:where` selector.
The `:where` selector has 0 specificity which makes it very easy to apply other styles to the component

refactor(FlexBox): move defaultProps to es6 defaults

---

packages/main/src/components/FilterBar/FilterBar.stories.mdx
packages/main/src/components/FilterBar/FilterDialog.tsx

The `selection-change` events are bubbling up to the `Table` component, leading to an error. 
This PR fixes this, by checking for the target of the event. If it's not invoked by the table, then it's ignored.

fix(FilterBar): don't fire bubbled up selection-change event of `Table`

---

tsconfig.base.json

UI5 Web Components are also building for ES2021, so we should do the same.
Browser Support is given in all our supported browsers: https://kangax.github.io/compat-table/es2016plus/

chore: increase ts target to ES2021

---

.storybook/components/Import.tsx
docs/5-Public-Utils.stories.mdx
package.json
yarn.lock

In some cases the `react-syntax-highlighter` failed to return a string, resulting in `[object Object]` to be displayed in stories. With this PR the dependency is removed and the appropriate styles are implemented with plain CSS and HTML.
Fixes #4035

docs: fix import statements

---

packages/main/src/components/Toolbar/index.tsx

docs(Toolbar): outline popover is only mounted when open

---

packages/main/src/components/ActionSheet/index.tsx
packages/main/src/components/MessageViewButton/index.tsx
packages/main/src/components/Toolbar/OverflowPopover.tsx
packages/main/src/components/Toolbar/index.tsx
packages/main/src/internal/ssr.ts
packages/main/src/internal/useServerSideEffect.ts
packages/main/src/internal/withWebComponent.tsx

refactor(Toolbar): make Toolbar SSR ready

---

packages/main/src/components/ActionSheet/index.tsx
packages/main/src/components/AnalyticalTable/ColumnHeader/index.tsx
packages/main/src/components/AnalyticalTable/__snapshots__/AnalyticalTable.test.tsx.snap
packages/main/src/components/AnalyticalTable/hooks/useRowSelectionColumn.tsx

Currently there is no `::part` support for the `CheckBox`, therefore we have to use `addCustomCSS`. --> https://github.com/SAP/ui5-webcomponents/issues/6461
Fixes #3732

fix(AnalyticalTable): center align select checkboxes

---

packages/main/src/components/DynamicPage/DynamicPage.stories.mdx
packages/main/src/components/Toolbar/Toolbar.cy.tsx
packages/main/src/components/Toolbar/index.tsx

fix(Toolbar): only fire `onClick` on SPACE/ENTER if toolbar is focused

---

packages/main/src/components/AnalyticalTable/AnalyticalTable.cy.tsx
packages/main/src/components/AnalyticalTable/ColumnHeader/ColumnHeaderModal.tsx
packages/main/src/components/AnalyticalTable/ColumnHeader/index.tsx
packages/main/src/components/AnalyticalTable/hooks/useA11y.ts
packages/main/src/components/AnalyticalTable/index.tsx
packages/main/src/i18n/messagebundle.properties

fix(AnalyticalTable): announce grouped, filtered and sorted columns with screen readers

---

packages/main/src/components/Form/Form.cy.tsx
packages/main/src/components/FormItem/index.tsx

It's sometimes necessary to set the `id` on controls yourself, e.g. when displaying a popover.

fix(FormItem): allow `id`s on `children`

---

packages/main/src/internal/useObserveHeights.ts

fix(DynamicPage & ObjectPage): prevent empty area on top of content when scrolling

---

packages/main/src/components/FormItem/index.tsx

fix(FormItem): fix react unique key error when using multiple children in FormItem

---

packages/main/src/components/Toolbar/OverflowPopover.tsx
packages/main/src/components/Toolbar/Toolbar.cy.tsx

fix(Toolbar): make ids unique for overflow items

---

packages/main/src/components/AnalyticalTable/ColumnHeader/index.tsx

This PR centers the icons shown for filtering, sorting, etc. in the column header. It also replaces some CSS properties with their logical counterpart which is using logical direction and dimension mappings.

fix(AnalyticalTable): center align indicator icons of columns

---

packages/main/src/components/Toolbar/OverflowPopover.tsx
packages/main/src/components/Toolbar/Toolbar.cy.tsx
packages/main/src/components/Toolbar/index.tsx

This PR also fixes an issue where `onOverflowChange` was called indefinitely.

fix(Toolbar): return correct value for `overflowElements` in `onOverflowChange`

---

packages/main/src/components/AnalyticalTable/AnalyticalTable.stories.tsx
packages/main/src/components/SplitterLayout/SplitterLayout.stories.tsx

I tested the threshold via [this page](https://6262c53f521620003ac2ff49-ukmsdlppcb.chromatic.com/?path=/story/stories-diff-threshold-check--test-yours-out) and for the ignored stories, the threshold would have to be set to over 0.8 and therefore the snapshot is useless.

test(chromatic): increase threshold or ignore flaky AnalyticalTable stories

---

packages/main/src/components/AnalyticalTable/AnalyticalTable.cy.tsx
packages/main/src/components/AnalyticalTable/AnalyticalTable.stories.tsx
packages/main/src/components/AnalyticalTable/PluginDisableRowSelection.mdx
packages/main/src/components/AnalyticalTable/PluginIndeterminateRowSelection.mdx
packages/main/src/components/AnalyticalTable/PluginManualRowSelect.mdx
packages/main/src/components/AnalyticalTable/PluginOnColumnResize.mdx
packages/main/src/components/AnalyticalTable/PluginOrderedMultiSort.mdx
packages/main/src/components/AnalyticalTable/Recipes.mdx
packages/main/src/components/AnalyticalTable/pluginHooks/AnalyticalTableHooks.ts
packages/main/src/components/AnalyticalTable/pluginHooks/useOrderedMultiSort.ts

feat(AnalyticalTable - `useOrderedMultiSort`): introduce new plugin hook

---

packages/main/src/components/Toolbar/index.tsx

fix(Toolbar): only prevent keydown default actions in `onClick`

---

packages/main/src/components/Form/index.tsx

docs(Form): add note about width calculation

---

packages/main/package.json

This should fix #4676.
Jest prefers the `browser` condition when using the `jsdom` environment: https://jestjs.io/docs/configuration#testenvironmentoptions-object

fix: add browser condition to package exports

---

packages/main/src/i18n/messagebundle_pt.properties

fix(translations): fix "default" translation in Portuguese

---

packages/main/src/webComponents/Popover/Popover.stories.mdx

docs(Popover): add missing `onAfterClose`

---

packages/main/src/components/AnalyticalTable/PluginIndeterminateRowSelection.mdx

Plugin hooks don't get their story description via JSDoc.

docs(AnalyticalTable - useIndeterminateRowSelection): add performance warning to story

---

packages/main/src/components/AnalyticalTable/AnayticalTable.jss.ts
packages/main/src/components/AnalyticalTable/scrollbars/VerticalScrollbar.tsx

Note: Firefox lacks capabilities for customizing scrollbars, that's why there might be discrepancies noticeable between browsers.
Fixes #4379

fix(AnalyticalTable): fix scrollbars for Firefox and Safari

---

packages/cypress-commands/src/commands.ts
packages/cypress-commands/test/UI5WebComponentsChild.cy.tsx

feat(cypress-commands): add clearUi5Input to cypress commands

---

packages/main/src/components/Toolbar/Toolbar.jss.ts
packages/main/src/components/Toolbar/Toolbar.stories.tsx

- Only apply styles to immediate children in overflow popover
- Use correct margin for buttons
- Replace physical with logical CSS properties

fix(Toolbar): fix overflow popover margins

---

packages/main/src/components/ActionSheet/ActionSheet.cy.tsx
packages/main/src/components/ActionSheet/index.tsx

feat(ActionSheet): add keyboard navigation for `PageUp/Down`, `Home`, `End`

---

packages/main/src/components/AnalyticalTable/AnalyticalTable.cy.tsx
packages/main/src/components/AnalyticalTable/AnalyticalTable.stories.tsx
packages/main/src/components/AnalyticalTable/hooks/useA11y.ts
packages/main/src/components/AnalyticalTable/index.tsx

This PR adds the `headerLabel` column offering a way to define a label for custom headers.
Fixes #3121
Fixes #3189

feat(AnalyticalTable): add `headerLabel` column property

---

packages/main/src/components/Text/Text.cy.tsx
packages/main/src/components/Text/Text.jss.ts
packages/main/src/components/Text/index.tsx

feat(Text): add `maxLines` prop

---

packages/main/src/components/ObjectPage/index.tsx

If `showTitleInHeaderContent` is set, it should be possible rendering an empty `DynamicPagerHeader` with only the `headerTitle` and `image` inside of it.

fix(ObjectPage): allow rendering `headerTitle` only in `headerContent` section

---

packages/cypress-commands/package.json

Some tools like `eslint-plugin-import` rely on the presence of the `main` field in the package.json.
Fixes #5049

fix(cypress-commands): add main entrypoint

---

packages/main/src/components/VariantManagement/index.tsx

fix(VariantManagement): fix type extraction for button click handler

---

packages/main/src/components/AnalyticalTable/index.tsx

This causes the deprecation warning to always show up

fix(AnalyticalTable): remove default prop for `alwaysShowSubComponent`

---

packages/main/src/components/MessageViewButton/index.tsx

The `MessageViewButton` shouldn't be used as submit button of a form, that's why we should omit the deprecated `submits` prop of the `Button` from inheritance.

fix(MessageViewButton - TypeScript): omit inherited `submits` prop

---

packages/main/src/components/ObjectStatus/ObjectStatus.jss.ts

fix(ObjectStatus): fix border issue of None variant of inverted ObjectStatus

---

packages/main/src/components/AnalyticalTable/hooks/useToggleRowExpand.ts

fix(AnalyticalTable): return consistent values across all envs in`onRowExpandChange`

---

packages/main/src/components/AnalyticalTable/AnalyticalTable.mdx

docs(AnalyticalTable): add note about `cell` property of popped-in cells

---

.storybook/mockData/generateMessageItems.tsx
packages/main/src/components/MessageView/MessageView.cy.tsx
packages/main/src/components/MessageView/MessageView.stories.tsx
packages/main/src/components/MessageView/index.tsx

fix(MessageView): don't show unnecessary scrollbar in details view

---

packages/main/src/components/ObjectStatus/ObjectStatus.cy.tsx
packages/main/src/components/ObjectStatus/ObjectStatus.jss.ts
packages/main/src/components/ObjectStatus/index.tsx
tsconfig.base.json

fix(ObjectStatus): fire `onClick` on SPACE or ENTER press

---

packages/base/src/utils/index.ts
packages/main/src/components/ObjectPage/ObjectPage.cy.tsx
packages/main/src/components/ObjectPage/ObjectPage.jss.ts
packages/main/src/components/ObjectPage/index.tsx
packages/main/src/components/ObjectPageSection/index.tsx

fix(ObjectPage): always allow scrolling to (sub)sections

---

packages/main/src/components/AnalyticalTable/AnalyticalTable.cy.tsx
packages/main/src/components/AnalyticalTable/TableBody/VirtualTableBody.tsx
packages/main/src/components/AnalyticalTable/types/index.ts

fix(AnalyticalTable): calculate subcomponents correctly in tree table

---

packages/main/src/components/DynamicPage/index.tsx
packages/main/src/components/DynamicPageHeader/index.tsx
packages/main/src/components/DynamicPageTitle/index.tsx
packages/main/src/components/ObjectPage/index.tsx

docs(DynamicPageHeader & DynamicPageTitle): outline mandatory passing through props

---

packages/main/src/components/AnalyticalTable/Recipes.mdx

docs(AnalyticalTable): correct how to distinguish between `onRowClick` and `onRowSelect`

---

packages/main/src/components/AnalyticalTable/AnalyticalTable.cy.tsx
packages/main/src/components/AnalyticalTable/hooks/useA11y.ts

fix(AnalyticalTable): set `aria-label` correctly for non-interactive tables

---

packages/main/src/components/ObjectPage/ObjectPage.cy.tsx
packages/main/src/components/ObjectPage/index.tsx

This PR also renames some constants to improve readability. The relevant change for the fix is in line 238.
Fixes #5600

fix(ObjectPage): prevent initially mounting all children in `IconTabBar` mode

---

packages/base/src/context/StyleContext.ts
packages/base/src/hooks/useStylesheet.cy.tsx
packages/base/src/hooks/useStylesheet.ts
packages/main/src/components/ThemeProvider/index.tsx

fix(useStylesheet): only remove styles when all components are unmounted

---

packages/main/src/components/Splitter/index.tsx

fix(SplitterLayout): improve drag and drop behavior

---

packages/main/src/components/AnalyticalTable/AnalyticalTable.cy.tsx
packages/main/src/components/AnalyticalTable/index.tsx
packages/main/src/components/AnalyticalTable/types/index.ts
packages/main/src/i18n/messagebundle.properties

This commit also enables i18n for the text placeholders.

feat(AnalyticalTable): show `noDataText` if table is filtered and no rows are returned

---

.storybook/utils.ts

`attachedCSFFile` was changed to `attachedCSFFiles` and is a set now.

docs(Storybook): fix subcomponent generation

---

packages/main/src/components/Form/Form.cy.tsx
packages/main/src/components/Form/Form.stories.tsx
packages/main/src/components/Form/index.tsx
packages/main/src/components/Form/types.ts

When a `Form` contains only `FormItems` and no `FormGroups`, the reading and tab order of the form items should be first top to bottom, then start to end.
Part of #5704

fix(Form): fix reading and tab order when only FormItems are used

---

packages/main/src/components/OverflowToolbarButton/index.tsx
packages/main/src/components/OverflowToolbarToggleButton/index.tsx
packages/main/src/components/Toolbar/OverflowPopover.tsx
packages/main/src/internal/OverflowPopoverContext.ts

This PR fixes #5738 by make the context `OverflowPopoverContext` to a singleton, to make it works for multiple UI5 instanced introduced by UI5 scoping. The singleton solution is copied from `packages/base/src/context/StyleContext.ts`:
```Typescript
const SYMBOL = Symbol.for('@ui5/webcomponents-react/StyleContext');
//...
export function getStyleContext(): typeof StyleContext {
globalThis[SYMBOL] ??= StyleContext;
return globalThis[SYMBOL];
}
```
Before:
After:

fix(OverflowPopover): make OverflowPopoverContext to a single to issue on multiple instances (#5738)

---

packages/charts/src/components/BarChart/BarChart.cy.tsx
packages/charts/src/components/BarChart/BarChart.tsx
packages/charts/src/components/BulletChart/BulletChart.tsx
packages/charts/src/components/ColumnChart/ColumnChart.tsx
packages/charts/src/components/ComposedChart/index.tsx
packages/charts/src/components/LineChart/LineChart.tsx
packages/charts/src/components/RadarChart/RadarChart.tsx
packages/charts/src/components/ScatterChart/ScatterChart.tsx
packages/charts/src/hooks/usePrepareDimensionsAndMeasures.cy.tsx
packages/charts/src/hooks/usePrepareDimensionsAndMeasures.ts

fix(charts): correctly apply React `key` with function `accessor`s

---

packages/main/src/internal/withWebComponent.tsx

As UI5 Web Components are adding some attributes while being rendered on the client (like their own tag name), we should suppress hydration warnings for all UI5 Web Components.

fix: suppress hydration warnings for web components

---

packages/main/src/components/Toolbar/Toolbar.cy.tsx
packages/main/src/components/ToolbarSeparator/index.tsx

fix(ToolbarSeparator): use "separator" `role` to announce separator

---

packages/main/src/components/AnalyticalTable/ColumnHeader/ColumnHeaderModal.tsx
packages/main/src/components/AnalyticalTable/hooks/useKeyboardNavigation.ts

fix(AnalyticalTable): trap focus inside column header popover while open

---

packages/main/src/components/Form/Form.module.css
packages/main/src/components/Form/index.tsx

fix(Form): fix vertical alignment of FormItems for `labelSpan=12`

---

packages/main/src/components/Loader/index.tsx

This component is a remnant of temporary design guidelines and is not recommended to be used anymore. The `BusyIndicator` should be the only loading indicator available. Therefore, we will remove this component in favor of the `BusyIndicator` with our next release.
For further information see [Fiori for Web Design Guidelines](https://experience.sap.com/fiori-design-web/busy-handling/)

fix(Loader): deprecate component

---

.storybook/preview-head.html
packages/main/src/components/Form/Form.cy.tsx
packages/main/src/components/Form/Form.mdx
packages/main/src/components/Form/Form.stories.tsx
packages/main/src/components/Form/index.tsx
packages/main/src/components/FormGroup/FormGroupTitle.tsx
packages/main/src/components/FormGroup/index.tsx
packages/main/src/components/FormItem/FormItem.module.css
packages/main/src/components/FormItem/index.tsx

fix(Form): improve a11y of ui5 web component inputs

---

docs/MigrationGuide.mdx
packages/cli/src/scripts/codemod/transforms/v2/codemodConfig.json
packages/cli/src/scripts/codemod/transforms/v2/main.cts
packages/main/src/components/ActionSheet/ActionSheet.cy.tsx
packages/main/src/components/ActionSheet/ActionSheet.mdx
packages/main/src/components/ActionSheet/ActionSheet.stories.tsx
packages/main/src/components/ActionSheet/index.tsx

BREAKING CHANGE: the `portalContainer` prop has been removed as it's not needed anymore
BREAKING CHANGE: the `showCancelButton` has been renamed to `hideCancelButton` and the logic has been inverted.

refactor(ActionSheet): api alignment

---

docs/MigrationGuide.mdx
packages/main/src/components/MessageBox/MessageBox.cy.tsx
packages/main/src/components/MessageBox/index.tsx

BREAKING CHANGE: `onClose` is now a plain callback and not a `CustomEvent` event anymore. It now receives two params: `action` & `escPressed`.

refactor(MessageBox): refactor `onClose` event

---

packages/main/src/components/ObjectStatus/index.tsx

BREAKING CHANGE: **TypeScript**: the `HTMLDivElement` type has been removed from the `onClick` handler.

fix(ObjectStatus): remove `HTMLDivElement` from `onClick` type

---

docs/MigrationGuide.mdx
packages/main/src/components/ObjectPage/ObjectPage.cy.tsx
packages/main/src/components/ObjectPageSection/index.tsx
packages/main/src/components/ObjectPageSubSection/index.tsx

BREAKING CHANGE: **ObjectPageSection**: the prop `titleText` is now required.
BREAKING CHANGE: **ObjectPageSection**: the default value `true` for the prop `titleTextUppercase` has been removed.
BREAKING CHANGE: **ObjectPageSubSection**: the prop `titleText` is now required.

refactor: make titleText required for object page sections

---

packages/main/src/components/MessageView/MessageItem.tsx
packages/main/src/components/MessageView/MessageView.mdx
packages/main/src/components/MessageView/MessageView.stories.tsx

fix(MessageViewItem): enable details view if `titleText` is overflowing

---

docs/MigrationGuide.mdx
docs/knowledge-base/Portals.mdx
packages/main/src/components/AnalyticalTable/ColumnHeader/ColumnHeaderContainer.tsx
packages/main/src/components/AnalyticalTable/ColumnHeader/ColumnHeaderModal.tsx
packages/main/src/components/AnalyticalTable/ColumnHeader/index.tsx
packages/main/src/components/AnalyticalTable/Recipes.mdx
packages/main/src/components/AnalyticalTable/VerticalResizer.tsx
packages/main/src/components/AnalyticalTable/index.tsx
packages/main/src/components/AnalyticalTable/types/index.ts
packages/main/src/components/MessageBox/MessageBox.mdx
packages/main/src/components/MessageBox/MessageBox.stories.tsx
packages/main/src/components/MessageBox/index.tsx
packages/main/src/components/MessageView/MessageView.stories.tsx
packages/main/src/webComponents/ColorPalettePopover/ColorPalettePopover.stories.tsx
packages/main/src/webComponents/Dialog/Dialog.mdx
packages/main/src/webComponents/Dialog/Dialog.stories.tsx
packages/main/src/webComponents/Popover/Popover.mdx
packages/main/src/webComponents/Popover/Popover.stories.tsx
packages/main/src/webComponents/ResponsivePopover/ResponsivePopover.mdx
packages/main/src/webComponents/ResponsivePopover/ResponsivePopover.stories.tsx
packages/main/src/webComponents/ViewSettingsDialog/ViewSettingsDialog.stories.tsx

Additionally, this PR removes all mentions of `createPortal` or `portalContainer`.
BREAKING CHANGE: `portalContainer` has been removed as it's no longer needed due to the [Popover API](https://developer.mozilla.org/en-US/docs/Web/API/Popover_API).

refactor(AnalyticalTable): remove unnecessary `portalContainer` prop

---

docs/MigrationGuide.mdx
package.json
packages/cli/src/scripts/codemod/transforms/v2/codemodConfig.json
packages/main/src/components/ActionSheet/ActionSheet.stories.tsx
packages/main/src/components/ActionSheet/index.tsx
packages/main/src/components/AnalyticalTable/AnalyticalTable.cy.tsx
packages/main/src/components/AnalyticalTable/AnalyticalTable.mdx
packages/main/src/components/AnalyticalTable/AnalyticalTable.stories.tsx
packages/main/src/components/AnalyticalTable/AnalyticalTableHooks.stories.tsx
packages/main/src/components/AnalyticalTable/PluginDisableRowSelection.mdx
packages/main/src/components/AnalyticalTable/PluginIndeterminateRowSelection.mdx
packages/main/src/components/AnalyticalTable/PluginManualRowSelect.mdx
packages/main/src/components/AnalyticalTable/hooks/useRowSelectionColumn.tsx
packages/main/src/components/AnalyticalTable/hooks/useSelectionChangeCallback.ts
packages/main/src/components/AnalyticalTable/hooks/useSingleRowStateSelection.ts
packages/main/src/components/AnalyticalTable/hooks/useStyling.ts
packages/main/src/components/AnalyticalTable/pluginHooks/useIndeterminateRowSelection.tsx
packages/main/src/components/AnalyticalTable/pluginHooks/useRowDisableSelection.tsx
packages/main/src/components/AnalyticalTable/types/index.ts
packages/main/src/components/MessageBox/index.tsx
packages/main/src/components/ObjectPage/ObjectPage.stories.tsx
packages/main/src/components/ObjectPage/index.tsx
packages/main/src/components/ObjectPageAnchorBar/index.tsx
packages/main/src/components/ObjectStatus/ObjectStatus.cy.tsx
packages/main/src/components/ObjectStatus/ObjectStatus.stories.tsx
packages/main/src/components/ObjectStatus/index.tsx
packages/main/src/enums/AnalyticalTableSelectionMode.ts
yarn.lock

BREAKING CHANGE: __ActionSheet:__ `a11yConfig` has been renamed to `accessibilityAttributes`.
BREAKING CHANGE: __AnalyticalTable:__ The properties and values for the `AnalyticalTableSelectionMode` enum has been changed.  `SingleSelect` is now `Single` and `MultiSelect` is now `Multiple`.
BREAKING CHANGE: __AnalyticalTable:__ `a11yConfig` has been renamed to `accessibilityAttributes`.
BREAKING CHANGE: __ObjectPage:__ `a11yConfig` has been renamed to `accessibilityAttributes`.
BREAKING CHANGE: __ObjectStatus:__ `active` has been renamed to `interactive`.

refactor: harmonize prop/enum names

---

packages/main/src/components/DynamicPage/DynamicPage.module.css
packages/main/src/components/DynamicPageTitle/DynamicPageTitle.module.css
packages/main/src/components/ObjectPage/ObjectPage.module.css

Prevents that parts of some Web Components (e.g. `Slider`) are shining through the header content
Fixes #6107

fix(DynamicPage/ObjectPage): increase header z-index

---

packages/main/src/types/Ui5CustomEvent.ts

fix(UI5CustomEvent - TypeScript): correctly `currentTarget` type

---

packages/main/src/components/AnalyticalTable/AnalyticalTable.cy.tsx
packages/main/src/components/AnalyticalTable/ColumnHeader/index.tsx
packages/main/src/components/AnalyticalTable/hooks/useKeyboardNavigation.ts
packages/main/src/components/AnalyticalTable/hooks/useRowSelectionColumn.tsx

fix(AnalyticalTable): allow selecting all rows via keyboard

---

packages/main/src/components/MessageBox/MessageBox.cy.tsx
packages/main/src/components/MessageBox/index.tsx

fix(MessageBox): don't throw error if onClose is not passed

---

docs/knowledge-base/BringYourOwnWebComponents.mdx

This PR adds the documentation for the `@ui5/webcomponents-react-cli` package and describes how to create web components wrappers on the fly.
Closes #5046

feat: expose CLI package for creating web component wrappers

---

docs/MigrationGuide.mdx
packages/main/src/components/Modals/index.tsx

BREAKING CHANGE: modals are now rendered as children of the `Modals` component instead of being rendered into `document.body`

refactor(Modals): avoid unnecessary use of `createPortal`

---

packages/main/src/components/AnalyticalTable/AnalyticalTable.module.css
packages/main/src/components/AnalyticalTable/index.tsx

fix(AnalyticalTable): ensure loading indicator displays correctly across all browsers

---

README.md
docs/MigrationGuide.mdx
docs/Welcome.mdx
docs/knowledge-base/Public-Utils.mdx

Adjustments:
- mention ui5wc MigrationGuide
- order of breaking changes
- ThemingParameters in "Public Utils"
- 1.x support

docs: general docs adjustments

---

.github/workflows/release-custom-tag.yml
.github/workflows/release-snapshot.yml
.github/workflows/release.yml
.gitignore
package.json
packages/base/package.json
packages/base/src/index.ts
packages/charts/package.json
packages/charts/src/index.ts
packages/compat/package.json
packages/compat/src/index.ts
packages/main/package.json
packages/main/src/components/ThemeProvider/index.tsx
packages/main/src/index.ts
scripts/generate-version-info.js

fix: generate version info during build

---

packages/main/src/components/Grid/index.tsx

docs(Grid): outline limitations

---

.storybook/components/DocsHeader.tsx
.storybook/components/Import.tsx
packages/compat/package.json

fix(compat): allow file/deep imports for components

---

packages/main/src/components/AnalyticalTable/AnalyticalTable.cy.tsx
packages/main/src/components/AnalyticalTable/hooks/useA11y.ts
packages/main/src/components/AnalyticalTable/hooks/useRowSelectionColumn.tsx
packages/main/src/components/AnalyticalTable/index.tsx
packages/main/src/components/AnalyticalTable/types/index.ts
packages/main/src/i18n/messagebundle.properties

fix(AnalyticalTable): announce select-all cell for screen readers

---

.storybook/main.ts
cypress.config.ts
packages/charts/src/components/BarChart/BarChart.mdx
packages/charts/src/components/BarChart/BarChart.stories.tsx
packages/charts/src/components/BulletChart/BulletChart.mdx
packages/charts/src/components/BulletChart/BulletChart.stories.tsx
packages/charts/src/components/ColumnChart/ColumnChart.mdx
packages/charts/src/components/ColumnChart/ColumnChart.stories.tsx
packages/charts/src/components/ColumnChartWithTrend/ColumnChartWithTrend.tsx
packages/charts/src/components/ComposedChart/ComposedChart.mdx
packages/charts/src/components/ComposedChart/ComposedChart.stories.tsx
packages/charts/src/components/DonutChart/DonutChart.mdx
packages/charts/src/components/DonutChart/DonutChart.stories.tsx
packages/charts/src/components/LineChart/LineChart.mdx
packages/charts/src/components/LineChart/LineChart.stories.tsx
packages/charts/src/components/PieChart/PieChart.mdx
packages/charts/src/components/PieChart/PieChart.stories.tsx
packages/charts/src/components/RadarChart/RadarChart.mdx
packages/charts/src/components/RadarChart/RadarChart.stories.tsx
packages/charts/src/components/ScatterChart/ScatterChart.mdx
packages/charts/src/components/ScatterChart/ScatterChart.stories.tsx
packages/charts/src/resources/DemoProps.ts
packages/charts/src/resources/TooltipConfig.mdx

docs(charts): improve documentation & add `tooltipConfig` stories

---

packages/main/src/components/AnalyticalTable/TableBody/VirtualTableBodyContainer.tsx
packages/main/src/components/AnalyticalTable/index.tsx
packages/main/src/components/AnalyticalTable/types/index.ts

Using `infiniteScroll` with a grouped table can result in an odd user experience. For example, when rows are lazy-loaded via scrolling, new rows might only be added to existing groups. This won't change the scroll container's height, potentially forcing the user to scroll down again to load more rows.
Therefore (and as we don't have a concept for this behavior) __it's not recommended using a grouped table in combination with `infiniteScroll`__!

fix(AnalyticalTable): offer limited support for `infiniteScroll` combined with a grouped table

---

packages/main/src/components/Text/Text.cy.tsx
packages/main/src/components/Text/Text.stories.tsx
packages/main/src/components/Text/index.tsx

fix(Text): only break words if text can wrap

---

packages/charts/src/components/BarChart/BarChart.tsx
packages/charts/src/components/BulletChart/BulletChart.tsx
packages/charts/src/components/ColumnChart/ColumnChart.tsx
packages/charts/src/components/ColumnChartWithTrend/ColumnChartWithTrend.tsx
packages/charts/src/components/ComposedChart/index.tsx
packages/charts/src/components/LineChart/LineChart.tsx
packages/charts/src/components/PieChart/PieChart.tsx
packages/charts/src/components/RadarChart/RadarChart.tsx
packages/charts/src/components/ScatterChart/ScatterChart.tsx
packages/charts/src/interfaces/IChartBaseProps.ts

[Recharts documentation](https://recharts.org/en-US/storybook) udner the "Accessibility" section
Closes #6446

feat(charts): allow rechart's `accessibilityLayer` prop

---

packages/cypress-commands/src/queries.ts
packages/cypress-commands/test/UI5WebComponentsChild.cy.tsx
packages/main/src/components/FilterBar/FilterBar.cy.tsx
packages/main/src/components/FilterBar/index.tsx

#6463 needs to be merged first.
Fixes #6461

fix(FilterBar): show FilterBar buttons if `hideToolbar` is active

---

packages/main/src/components/ObjectPage/ObjectPageUtils.ts
packages/main/src/components/ObjectPage/index.tsx

fix(ObjectPage): improve selection & scroll behavior (#6492)

---

packages/main/src/components/ObjectPage/ObjectPage.cy.tsx
packages/main/src/components/ObjectPage/ObjectPage.mdx
packages/main/src/components/ObjectPage/ObjectPage.module.css
packages/main/src/components/ObjectPage/index.tsx

Also fixes two flaky ObjectPage tests

fix(ObjectPage): support section selection in iframe (#6535)

---

packages/compat/src/components/Toolbar/OverflowPopover.tsx
packages/compat/src/components/Toolbar/Toolbar.mdx
packages/compat/src/components/Toolbar/Toolbar.stories.tsx
packages/compat/src/components/Toolbar/index.tsx

fix(Toolbar - compat): announce number of items in overflow popover

---

packages/main/src/components/VariantManagement/index.tsx

fix(VariantManagement): fix dirty-state and `readOnly` behavior

---

packages/main/src/components/VariantManagement/VariantManagement.cy.tsx
packages/main/src/components/VariantManagement/index.tsx

Add tests for data-attributes in React 19

fix(VariantManagement): support React 19

---

packages/charts/src/components/DonutChart/DonutChart.mdx
packages/charts/src/components/DonutChart/DonutChart.stories.tsx
packages/charts/src/components/DonutChart/DonutChart.tsx
packages/charts/src/components/PieChart/PieChart.module.css
packages/charts/src/components/PieChart/PieChart.stories.tsx
packages/charts/src/components/PieChart/PieChart.tsx

fix(Pie- & DonutChart): improve `activeSegment` handling & fix focus behavior

---

packages/main/src/components/ObjectPage/ObjectPage.mdx
packages/main/src/webComponents/DynamicPage/DynamicPage.mdx
packages/main/src/webComponents/Toolbar/Toolbar.mdx
packages/main/src/webComponents/Toolbar/Toolbar.stories.tsx

docs(Toolbar): outline how to open popovers

---

docs/Welcome.mdx
docs/knowledge-base/CustomComponentsSlots.mdx
docs/knowledge-base/Internationalization.mdx
packages/main/src/components/MessageView/MessageView.stories.tsx

https://github.com/SAP/ui5-webcomponents/issues/10386#issuecomment-2547706212

docs: update links & improve custom slot knowledge base entry

---

.storybook/components/DomRefTable.tsx
packages/main/src/components/Toolbar/Toolbar.mdx

docs(Toolbar): outline `part` attributes

---

packages/main/src/components/AnalyticalTable/index.tsx

fix(AnalyticalTable): apply correct column width when hiding columns

---

packages/main/src/components/MessageView/MessageItem.tsx
packages/main/src/components/MessageView/MessageView.cy.tsx
packages/main/src/components/MessageView/MessageView.stories.tsx
packages/main/src/webComponents/Link/Link.stories.tsx

Also outline that `wrappingType="None"` is required if a `Link` is used as `titleText`.
Fixes #6857

fix(MessageItem): enable details view if Link overflows

---

packages/main/src/components/AnalyticalTable/AnalyticalTable.cy.tsx
packages/main/src/components/AnalyticalTable/hooks/useSingleRowStateSelection.ts

Previously this was only possible by calling `event.stopPropagation()` in the respective handler.

fix(AnalyticalTable): allow typing SPACE in custom cell content

---

packages/main/src/components/FlexBox/FlexBox.cy.tsx
packages/main/src/components/FlexBox/index.tsx

feat(FlexBox): introduce `gap` prop

---

packages/main/src/components/ObjectPage/ObjectPage.cy.tsx
packages/main/src/components/ObjectPage/index.tsx

fix(ObjectPage): scroll to section when programmatically selected

---

packages/main/src/components/Toolbar/OverflowPopover.tsx
packages/main/src/components/Toolbar/Toolbar.cy.tsx
packages/main/src/components/Toolbar/index.tsx

Fixes #6933
part cherry-pick of #6962

fix(Toolbar): exclude spacer from overflow popover

---

packages/main/src/components/ObjectPage/ObjectPage.module.css
packages/main/src/components/ObjectPage/index.tsx

fix(ObjectPage): use full width for header content if no `image` is set

---

packages/main/src/components/ObjectStatus/ObjectStatus.cy.tsx
packages/main/src/components/ObjectStatus/index.tsx

fix(ObjectStatus): screen readers announce "button" only once

---

packages/main/src/components/ObjectPage/ObjectPage.cy.tsx
packages/main/src/components/ObjectPageAnchorBar/index.tsx

This PR also improves the types of the `ObjectPageAnchorBar` component.

fix(ObjectPage): fire `onPinButtonToggle` only when required

---

yarn.lock

Reverts SAP/ui5-webcomponents-react#7065
Storybook build error.

Revert "chore(deps): bump @babel/runtime from 7.20.13 to 7.26.10"

---

package.json
yarn.lock

Storybook currently only supports `typescript` < `5.8.0`

chore(deps): downgrade TypeScript to `v5.7.3`

---

packages/main/src/components/AnalyticalTable/ColumnHeader/ColumnHeaderContainer.tsx
packages/main/src/components/AnalyticalTable/TableBody/VirtualTableBody.tsx

This warning was introduced in React v18.3.
Fixes #7093

fix(AnalyticalTable): fix React `key` warning

---

packages/compat/README.md

docs(compat): better outline legacy table pitfalls

---

packages/main/src/components/VariantManagement/index.tsx

fix(VariantManagement): allow quotes in `VariantItem` name

---

packages/main/src/components/ObjectStatus/ObjectStatus.stories.tsx
packages/main/src/components/ObjectStatus/index.tsx

fix(ObjectStatus): use `IconMode.Decorative` instead of `aria-hidden`

---

packages/main/src/components/ObjectPage/ObjectPage.module.css
packages/main/src/components/ObjectPage/index.tsx

fix(ObjectPage): always show focused elements in content

---

packages/main/src/components/ObjectPage/ObjectPage.cy.tsx
packages/main/src/components/ObjectPage/ObjectPage.module.css
packages/main/src/components/ObjectPage/ObjectPage.stories.tsx
packages/main/src/components/ObjectPageTitle/index.tsx

fix(ObjectPage): announce first section heading with screen readers

---

packages/main/src/components/MessageView/MessageItem.module.css
packages/main/src/components/MessageView/MessageItem.tsx
packages/main/src/components/MessageView/MessageView.cy.tsx
packages/main/src/components/MessageView/MessageView.stories.tsx
packages/main/src/components/MessageView/index.tsx
packages/main/src/components/MessageView/utils.ts
packages/main/src/i18n/messagebundle.properties
packages/main/src/internal/MessageViewContext.ts

Fixes #7076
Fixes #7087
Fixes #7059

fix(MessageView): improve accessibility

---

packages/compat/src/components/Toolbar/Toolbar.cy.tsx
packages/compat/src/components/Toolbar/index.tsx

If only `ToolbarSeparator` or `ToolbarSpacer` components are passed to the `Toolbar`, the components won't be rendered to prevent an empty overflow popover to show up if the width of the Toolbar is very small.

fix(Toolbar - compat): prevent empty overflow popover

---

packages/main/src/components/AnalyticalTable/ColumnHeader/index.tsx
packages/main/src/components/AnalyticalTable/TableBody/VirtualTableBody.tsx
packages/main/src/components/AnalyticalTable/TableBody/VirtualTableBodyContainer.tsx
packages/main/src/components/AnalyticalTable/VerticalResizer.tsx
packages/main/src/components/AnalyticalTable/defaults/Column/ColumnHeaderModal.tsx
packages/main/src/components/AnalyticalTable/defaults/Column/Expandable.tsx
packages/main/src/components/AnalyticalTable/hooks/useResizeColumnsConfig.ts
packages/main/src/components/AnalyticalTable/hooks/useToggleRowExpand.ts
packages/main/src/components/AnalyticalTable/index.tsx
packages/main/src/components/AnalyticalTable/types/index.ts
packages/main/src/i18n/messagebundle.properties

This PR i.a. improves accessibility for tree tables, but also adds general a11y improvements.
__Note:__ To prevent flooding the console with warnings, translations for the "expand/collapse row" announcement will be added once they are available.
Fixes #6515
Fixes #7147

fix(AnalyticalTable): improve accessibility

---

packages/main/src/components/ObjectPage/index.tsx
packages/main/src/components/ObjectPage/types/index.ts

feat(ObjectPage): allow customizing `role` of `footerArea` container

---

packages/charts/src/components/ColumnChartWithTrend/ColumnChartWithTrend.cy.tsx
packages/charts/src/components/ColumnChartWithTrend/ColumnChartWithTrend.module.css
packages/charts/src/components/ColumnChartWithTrend/ColumnChartWithTrend.tsx

fix(ColumnChartWithTrend): correct height calculation

---

packages/base/src/wrapper/withWebComponent.tsx

fix: attach ui5-webcomponents event handlers before browser paint

---

packages/main/src/components/AnalyticalTable/AnalyticalTable.mdx
packages/main/src/components/AnalyticalTable/AnalyticalTable.module.css
packages/main/src/components/AnalyticalTable/AnalyticalTable.stories.tsx
packages/main/src/components/AnalyticalTable/defaults/LoadingComponent/TablePlaceholder.module.css
packages/main/src/components/AnalyticalTable/defaults/LoadingComponent/TablePlaceholder.tsx
packages/main/src/components/AnalyticalTable/defaults/NoDataComponent/index.tsx
packages/main/src/components/AnalyticalTable/hooks/useKeyboardNavigation.ts
packages/main/src/components/AnalyticalTable/index.tsx

fix(AnalyticalTable): allow focusing "no-data" & placeholder components

---

packages/main/src/components/AnalyticalTable/AnalyticalTable.cy.tsx
packages/main/src/components/AnalyticalTable/ColumnHeader/index.tsx
packages/main/src/components/AnalyticalTable/defaults/Column/ColumnHeaderModal.tsx

fix(AnalyticalTable): restore focus when ungrouping a column

---

packages/main/src/components/ObjectPage/types/index.ts

docs(ObjectPage): adjust description of `onBeforeNavigate`

---

packages/cypress-commands/src/commands.ts

In the last commit for `cypress-commands/src/commands.ts`, new `options` parameter is added as a mandatory parameter for function `clickUi5ListItemByText` but it's not used.
It should be optional as other functions and the default value should be `{}`.

fix(cypress-commands): make the options optional for clickUi5ListItemByText

---

packages/main/src/components/SelectDialog/index.tsx

fix(SelectDialog): use `headerText` as `accessibleName` per default

---

package.json
yarn.lock

`@eslint/js` provides its own type definitions, so we don't need this installed.

chore: remove `@types/eslint__js`

---

packages/base/src/hooks/useSyncRef.ts

This PR now only adds the JsDoc comment, as replacing the deprecated `MutableRefObject` type is leading to ts-errors in React18

docs(useSyncRef): add jsdoc

---

packages/main/scripts/generateI18n.mjs

fix(Assets): exclude `-fetch` assets & remove unsupported `Assets-static.js`

---

packages/main/src/components/FilterGroupItem/types.ts

docs(FilterGroupItem): improve description of `required` prop

---

packages/main/src/components/ObjectPage/ObjectPage.module.css
packages/main/src/components/ObjectPage/index.tsx
packages/main/src/internal/useObserveHeights.ts

Also removes the redundant `anchorBarHeight` as it's always `0`.
Fixes #7362

fix(ObjectPage): correct position of header feature buttons

---

package.json
yarn.lock

The Storybook build throws an error for ts version > `5.7.3`

chore(deps): rollback ts version

---

packages/main/src/components/ObjectPage/ObjectPage.cy.tsx
packages/main/src/components/ObjectPage/ObjectPage.module.css
packages/main/src/components/ObjectPage/ObjectPageUtils.ts
packages/main/src/components/ObjectPage/context.ts
packages/main/src/components/ObjectPage/index.tsx
packages/main/src/components/ObjectPage/useHandleTabSelect.ts
packages/main/src/components/ObjectPageSection/ObjectPageSection.module.css
packages/main/src/components/ObjectPageSection/index.tsx
packages/main/src/components/ObjectPageSubSection/index.tsx

Closes #7386
Closes #7268
Closes #7548

feat(ObjectPage): implement keyboard-navigation & focus handling for sections

---

packages/main/src/components/SelectDialog/SelectDialog.cy.tsx
packages/main/src/components/SelectDialog/index.tsx

#7594 needs to be merged first.
Closes #7593
Related to: #7568

feat(SelectDialog): add `headerTextLevel` prop

---

packages/main/src/components/ObjectPage/ObjectPage.cy.tsx
packages/main/src/components/ObjectPage/index.tsx
packages/main/src/components/ObjectPageSection/index.tsx

fix(ObjectPage): handle `scrollPaddingBlock` when `relatedTarget` is `null`

---

packages/main/src/webComponents/Dialog/Dialog.stories.tsx

It seems Storybook can't handle JSX as control value anymore. As it doesn't really make sense to make it controllable anyways, disabling it is fine (imo).

docs(Dialog): fix docs (controls) crash

---

packages/main/src/components/MessageView/MessageView.cy.tsx
packages/main/src/components/MessageView/MessageView.module.css
packages/main/src/components/MessageView/index.tsx

fix(MessageView): fix rtl behavior & allow disabling animations
